class DriverTripOffer {
  const DriverTripOffer({required this.offerId,required this.bookingId,required this.bookingReference,required this.customerName,required this.pickupLabel,required this.destinationLabel,required this.pickupAt,required this.passengerCount,required this.bookingType,required this.vehicle,required this.registrationNumber,required this.expiresAt,this.notes});
  final String offerId,bookingId,bookingReference,customerName,pickupLabel,destinationLabel,bookingType,vehicle,registrationNumber;final DateTime pickupAt,expiresAt;final int passengerCount;final String? notes;
  factory DriverTripOffer.fromJson(Map<String,dynamic> j)=>DriverTripOffer(offerId:j['offerId'].toString(),bookingId:j['bookingId'].toString(),bookingReference:j['bookingReference']?.toString()??'',customerName:j['customerName']?.toString()??'',pickupLabel:j['pickupLabel']?.toString()??'',destinationLabel:j['destinationLabel']?.toString()??'',pickupAt:DateTime.parse(j['pickupAt'].toString()),passengerCount:(j['passengerCount'] as num?)?.toInt()??1,bookingType:j['bookingType']?.toString()??'',vehicle:j['vehicle']?.toString()??'',registrationNumber:j['registrationNumber']?.toString()??'',expiresAt:DateTime.parse(j['expiresAt'].toString()),notes:j['notes']?.toString());
}

class MobileTrip {
  const MobileTrip({required this.bookingId,required this.bookingReference,required this.customerName,required this.customerPhone,this.driverName,this.driverPhone,this.vehicle,this.registrationNumber,required this.pickupLabel,required this.destinationLabel,required this.pickupAt,this.returnAt,required this.passengerCount,required this.bookingType,required this.fare,required this.paymentStatus,required this.tripStatus,required this.operationalStatus,this.instructions,required this.lastActivityAt});
  final String bookingId,bookingReference,customerName,customerPhone,pickupLabel,destinationLabel,bookingType,paymentStatus,tripStatus,operationalStatus;final String? driverName,driverPhone,vehicle,registrationNumber,instructions;final DateTime pickupAt,lastActivityAt;final DateTime? returnAt;final int passengerCount;final double fare;
  factory MobileTrip.fromJson(Map<String,dynamic> j)=>MobileTrip(bookingId:j['bookingId'].toString(),bookingReference:j['bookingReference']?.toString()??'',customerName:j['customerName']?.toString()??'',customerPhone:j['customerPhone']?.toString()??'',driverName:j['driverName']?.toString(),driverPhone:j['driverPhone']?.toString(),vehicle:j['vehicle']?.toString(),registrationNumber:j['registrationNumber']?.toString(),pickupLabel:j['pickupLabel']?.toString()??'',destinationLabel:j['destinationLabel']?.toString()??'',pickupAt:DateTime.parse(j['pickupAt'].toString()),returnAt:j['returnAt']==null?null:DateTime.parse(j['returnAt'].toString()),passengerCount:(j['passengerCount'] as num?)?.toInt()??1,bookingType:j['bookingType']?.toString()??'',fare:(j['fare'] as num?)?.toDouble()??0,paymentStatus:j['paymentStatus']?.toString()??'Pending',tripStatus:j['tripStatus']?.toString()??'Pending',operationalStatus:j['operationalStatus']?.toString()??'',instructions:j['instructions']?.toString(),lastActivityAt:DateTime.parse(j['lastActivityAt'].toString()));
}

class TrackingPoint {
  const TrackingPoint({required this.latitude,required this.longitude,this.accuracy,this.heading,this.speedKph,this.batteryLevel,required this.deviceTimestamp,required this.serverTimestamp,required this.stale,required this.online,required this.emergency});
  final double latitude,longitude;final double? accuracy,heading,speedKph;final int? batteryLevel;final DateTime deviceTimestamp,serverTimestamp;final bool stale,online,emergency;
  factory TrackingPoint.fromJson(Map<String,dynamic> j)=>TrackingPoint(latitude:(j['latitude'] as num).toDouble(),longitude:(j['longitude'] as num).toDouble(),accuracy:(j['accuracy'] as num?)?.toDouble(),heading:(j['heading'] as num?)?.toDouble(),speedKph:(j['speedKph'] as num?)?.toDouble(),batteryLevel:(j['batteryLevel'] as num?)?.toInt(),deviceTimestamp:DateTime.parse(j['deviceTimestamp'].toString()),serverTimestamp:DateTime.parse(j['serverTimestamp'].toString()),stale:j['stale']==true,online:j['online']==true,emergency:j['emergency']==true);
}

class TripTracking {
  const TripTracking({required this.bookingId,required this.bookingReference,required this.tripStatus,required this.pickupLabel,required this.destinationLabel,this.pickupLatitude,this.pickupLongitude,this.destinationLatitude,this.destinationLongitude,this.driverName,this.vehicle,this.registrationNumber,this.vehicleCategory,this.driverLocation,required this.recentPath});
  final String bookingId,bookingReference,tripStatus,pickupLabel,destinationLabel;final double? pickupLatitude,pickupLongitude,destinationLatitude,destinationLongitude;final String? driverName,vehicle,registrationNumber,vehicleCategory;final TrackingPoint? driverLocation;final List<TrackingPoint> recentPath;
  factory TripTracking.fromJson(Map<String,dynamic> j)=>TripTracking(bookingId:j['bookingId'].toString(),bookingReference:j['bookingReference']?.toString()??'',tripStatus:j['tripStatus']?.toString()??'',pickupLabel:j['pickupLabel']?.toString()??'',destinationLabel:j['destinationLabel']?.toString()??'',pickupLatitude:(j['pickupLatitude'] as num?)?.toDouble(),pickupLongitude:(j['pickupLongitude'] as num?)?.toDouble(),destinationLatitude:(j['destinationLatitude'] as num?)?.toDouble(),destinationLongitude:(j['destinationLongitude'] as num?)?.toDouble(),driverName:j['driverName']?.toString(),vehicle:j['vehicle']?.toString(),registrationNumber:j['registrationNumber']?.toString(),vehicleCategory:j['vehicleCategory']?.toString(),driverLocation:j['driverLocation'] is Map?TrackingPoint.fromJson(Map<String,dynamic>.from(j['driverLocation'] as Map)):null,recentPath:(j['recentPath'] as List? ?? const []).whereType<Map>().map((x)=>TrackingPoint.fromJson(Map<String,dynamic>.from(x))).toList());
}
