-- Reference data: the places UDrive serves, and what a seat and a kilometre cost.
--
-- This is NOT demo content. The 35 destinations are real places in Azad Jammu
-- and Kashmir, and the rate card is what every fare quote is built from. With
-- either of them missing the customer app has an empty tourism catalogue and
-- cannot price a single ride.
--
-- WHY THIS FILE EXISTS AT ALL
--
-- "Add / refresh demo data" used to re-run two migration files as its seed:
-- 023 for the rate card and 010 for the destinations. A migration is written
-- against the schema of the moment it was written, and replaying one against
-- today's schema eventually breaks. It did: migration 025 later added
-- service_vehicle_rates.per_km_rate as NOT NULL with no default, and 023's
-- INSERT does not supply it. So the seed threw 23502 on its very first
-- statement, the whole transaction rolled back, and NOTHING was seeded --
-- not the rate card, not the destinations, not the demo hotels. The button
-- could not work, and it said so only as a 500.
--
-- So the seed no longer replays migrations. This file is data only, written
-- against the current schema, and it names every NOT NULL column it inserts.
-- Migrations own the schema; this owns the rows. Keep it that way.
--
-- Safe to run as often as you like: every statement is ON CONFLICT DO UPDATE.

-- ---------------------------------------------------------------------------
-- The vehicle rate card.
--
-- per_km_rate values are the ones migration 025 itself backfilled, so a
-- re-seed cannot quietly move a fare: bike 32, car 65, rickshaw 40,
-- coster 160.
-- ---------------------------------------------------------------------------
INSERT INTO udrive.service_vehicle_rates
    (service_type, vehicle_category, per_seat_rate, whole_vehicle_rate, per_km_rate)
VALUES
    ('City',           'Bike',      250, 250,   32),
    ('City',           'Car',       450, 1600,  65),
    ('City',           'Rickshaw',  300, 850,   40),
    ('City',           'Coster',    350, 7500,  160),
    ('PrivateVehicle', 'Bike',      300, 300,   32),
    ('PrivateVehicle', 'Car',       550, 2000,  65),
    ('PrivateVehicle', 'Rickshaw',  350, 1000,  40),
    ('PrivateVehicle', 'Coster',    450, 9000,  160)
ON CONFLICT (service_type, vehicle_category) DO UPDATE SET
    per_seat_rate      = EXCLUDED.per_seat_rate,
    whole_vehicle_rate = EXCLUDED.whole_vehicle_rate,
    per_km_rate        = EXCLUDED.per_km_rate,
    currency           = 'PKR',
    is_active          = true,
    updated_at         = now();

-- ---------------------------------------------------------------------------
-- The 35 destinations, lifted unchanged from migration 010.
--
-- Unchanged on purpose. These exact statements are already proven against the
-- live schema, and each one keys on the slug, so a re-seed refreshes a row
-- rather than duplicating it and never changes a destination's id -- which
-- matters, because tour packages point at these ids.
-- ---------------------------------------------------------------------------

INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000001','muzaffarabad','Muzaffarabad','مظفرآباد','Explore Muzaffarabad, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','مظفرآباد آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.4711,34.37),4326)::geography,'Muzaffarabad','March to November','Sedan / SUV','Good',92,88,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000002','neelum-valley','Neelum Valley','وادی نیلم','Explore Neelum Valley, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','وادی نیلم آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.8943,34.5843),4326)::geography,'Neelum','April to October','SUV / 4x4','Limited in upper areas',90,78,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000003','athmuqam','Athmuqam','آٹھمقام','Explore Athmuqam, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','آٹھمقام آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9077,34.5885),4326)::geography,'Neelum','March to November','Sedan / SUV','Good',88,82,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000004','keran','Keran','کیرن','Explore Keran, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','کیرن آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9476,34.6491),4326)::geography,'Neelum','April to October','SUV','Limited',91,79,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000005','upper-neelum','Upper Neelum','اپر نیلم','Explore Upper Neelum, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','اپر نیلم آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9647,34.6617),4326)::geography,'Neelum','May to October','SUV / 4x4','Limited',86,73,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000006','kutton-jagran','Kutton / Jagran','کٹن / جاگراں','Explore Kutton / Jagran, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','کٹن / جاگراں آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.79,34.535),4326)::geography,'Neelum','April to October','SUV','Limited',90,78,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000007','sharda','Sharda','شاردا','Explore Sharda, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','شاردا آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.1863,34.7939),4326)::geography,'Neelum','May to October','SUV / 4x4','Limited',86,72,'https://commons.wikimedia.org/wiki/Special:FilePath/Sharda%2C%20Neelum%20Valley%2C%20Kashmir.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000008','kel','Kel','کیل','Explore Kel, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','کیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.3502,34.8262),4326)::geography,'Neelum','May to October','4x4 recommended','Limited',82,68,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%2C%20Neelum%20Valley%2C%20Azad%20Khashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000009','arang-kel','Arang Kel','ارنگ کیل','Explore Arang Kel, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','ارنگ کیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.3462,34.8148),4326)::geography,'Neelum','May to September','4x4 + hiking','Very limited',80,62,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%2C%20Neelum%20Valley%2C%20Azad%20Khashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000010','taobat','Taobat','تاؤبٹ','Explore Taobat, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','تاؤبٹ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.7124,34.9459),4326)::geography,'Neelum','June to September','4x4 required','Very limited',76,58,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000011','ratti-gali-lake','Ratti Gali Lake','رتی گلی جھیل','Explore Ratti Gali Lake, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','رتی گلی جھیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.0602,34.8245),4326)::geography,'Neelum','July to September','4x4 + hiking','No reliable network',72,55,'https://commons.wikimedia.org/wiki/Special:FilePath/Ratti%20Gali%20Lake%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000012','chitta-katha-lake','Chitta Katha Lake','چٹہ کٹھہ جھیل','Explore Chitta Katha Lake, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','چٹہ کٹھہ جھیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.3446,34.9441),4326)::geography,'Neelum','July to September','4x4 + trekking','No reliable network',65,48,'https://commons.wikimedia.org/wiki/Special:FilePath/Ratti%20Gali%20Lake%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000013','baboon-valley','Baboon Valley','بابون ویلی','Explore Baboon Valley, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','بابون ویلی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.8845,34.6974),4326)::geography,'Neelum','June to September','4x4 required','Very limited',70,55,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000014','leepa-valley','Leepa Valley','وادی لیپہ','Explore Leepa Valley, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','وادی لیپہ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9266,34.3078),4326)::geography,'Jhelum Valley','May to October','SUV / 4x4','Limited',90,72,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000015','reshian','Reshian','ریشیاں','Explore Reshian, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','ریشیاں آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.8211,34.2794),4326)::geography,'Jhelum Valley','April to October','SUV','Variable',84,72,'https://commons.wikimedia.org/wiki/Special:FilePath/Sharda%2C%20Neelum%20Valley%2C%20Azad%20Jammu%20Kashmir.JPG?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000016','dao-khan','Dao Khan','داؤ کھن','Explore Dao Khan, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','داؤ کھن آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9686,34.3208),4326)::geography,'Jhelum Valley','May to October','SUV / 4x4','Limited',86,68,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000017','chakothi','Chakothi','چکوٹھی','Explore Chakothi, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','چکوٹھی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9863,34.1169),4326)::geography,'Jhelum Valley','March to November','Sedan / SUV','Good',82,78,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000018','pir-chinasi','Pir Chinasi','پیر چناسی','Explore Pir Chinasi, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','پیر چناسی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.5363,34.3168),4326)::geography,'Muzaffarabad','April to October','SUV recommended','Variable',82,70,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000019','shaheed-gali','Shaheed Gali','شہید گلی','Explore Shaheed Gali, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','شہید گلی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.542,34.2451),4326)::geography,'Muzaffarabad','March to November','Sedan / SUV','Good',88,82,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000020','rawalakot','Rawalakot','راولاکوٹ','Explore Rawalakot, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','راولاکوٹ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.7604,33.8578),4326)::geography,'Poonch','March to November','Sedan / SUV','Good',94,87,'https://commons.wikimedia.org/wiki/Special:FilePath/Sharda%2C%20Neelum%20Valley%2C%20Azad%20Jammu%20Kashmir.JPG?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000021','banjosa-lake','Banjosa Lake','بنجوسہ جھیل','Explore Banjosa Lake, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','بنجوسہ جھیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.8168,33.8162),4326)::geography,'Poonch','March to November','Sedan / SUV','Good',96,90,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000022','toli-pir','Toli Pir','تولی پیر','Explore Toli Pir, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','تولی پیر آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.8941,33.9278),4326)::geography,'Poonch','April to October','SUV recommended','Variable',88,72,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000023','poonch-river','Poonch River','دریائے پونچھ','Explore Poonch River, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','دریائے پونچھ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.7765,33.7672),4326)::geography,'Poonch','March to November','Sedan / SUV','Good',88,84,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000024','ganga-choti','Ganga Choti','گنگا چوٹی','Explore Ganga Choti, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','گنگا چوٹی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.5382,34.0138),4326)::geography,'Bagh','May to October','SUV + hiking','Limited',82,66,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%2C%20Neelum%20Valley%2C%20Azad%20Khashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000025','sudhan-gali','Sudhan Gali','سدھن گلی','Explore Sudhan Gali, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','سدھن گلی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.59,34.024),4326)::geography,'Bagh','April to October','SUV','Variable',89,75,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000026','las-danna','Las Danna','لس ڈنہ','Explore Las Danna, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','لس ڈنہ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.6274,33.9631),4326)::geography,'Bagh','April to October','SUV','Variable',84,70,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%2C%20Neelum%20Valley%2C%20Azad%20Khashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000027','haveli-kahuta','Haveli Kahuta','حویلی کہوٹہ','Explore Haveli Kahuta, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','حویلی کہوٹہ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9412,33.9462),4326)::geography,'Haveli','April to October','SUV','Limited',82,68,'https://commons.wikimedia.org/wiki/Special:FilePath/Sharda%2C%20Neelum%20Valley%2C%20Azad%20Jammu%20Kashmir.JPG?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000028','mirpur','Mirpur','میرپور','Explore Mirpur, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','میرپور آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.7516,33.1484),4326)::geography,'Mirpur','All year','Sedan / SUV','Good',92,90,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000029','mangla-lake','Mangla Lake','منگلا جھیل','Explore Mangla Lake, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','منگلا جھیل آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.645,33.142),4326)::geography,'Mirpur','October to April','Sedan / SUV','Good',94,90,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000030','ramkot-fort','Ramkot Fort','رام کوٹ قلعہ','Explore Ramkot Fort, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','رام کوٹ قلعہ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.6179,33.2255),4326)::geography,'Mirpur','October to April','SUV + boat access','Variable',78,68,'https://commons.wikimedia.org/wiki/Special:FilePath/Sharda%2C%20Neelum%20Valley%2C%20Kashmir.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000031','bhimber','Bhimber','بھمبر','Explore Bhimber, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','بھمبر آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.078,32.9747),4326)::geography,'Bhimber','October to April','Sedan / SUV','Good',88,86,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000032','samahni-valley','Samahni Valley','وادی سماہنی','Explore Samahni Valley, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','وادی سماہنی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(74.191,32.987),4326)::geography,'Bhimber','October to April','Sedan / SUV','Good',90,84,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000033','jhelum-valley','Jhelum Valley','وادی جہلم','Explore Jhelum Valley, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','وادی جہلم آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.73,34.17),4326)::geography,'Jhelum Valley','March to November','Sedan / SUV','Good',90,82,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000034','dhirkot','Dhirkot','دھیرکوٹ','Explore Dhirkot, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','دھیرکوٹ آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.602,33.969),4326)::geography,'Bagh','March to November','Sedan / SUV','Good',90,82,'https://commons.wikimedia.org/wiki/Special:FilePath/Arang%20Kel%20Valley%2C%20Neelum%20Valley%2C%20Azad%20Kashmir%2C%20Pakistan.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
INSERT INTO udrive.destinations (id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at)
VALUES ('11000000-0000-0000-0000-000000000035','kotli','Kotli','کوٹلی','Explore Kotli, one of Azad Jammu and Kashmir''s scenic tourism destinations. Check local weather and road conditions before departure.','کوٹلی آزاد جموں و کشمیر کا خوبصورت سیاحتی مقام ہے۔ روانگی سے پہلے موسم اور سڑک کی صورتحال ضرور دیکھیں۔',ST_SetSRID(ST_MakePoint(73.9022,33.5184),4326)::geography,'Kotli','October to April','Sedan / SUV','Good',90,88,'https://commons.wikimedia.org/wiki/Special:FilePath/Neelum%20River%20at%20Sharda%2C%20Neelum%20Valley.jpg?width=1200',true,now(),now())
ON CONFLICT (slug) DO UPDATE SET name_en=EXCLUDED.name_en,name_ur=EXCLUDED.name_ur,summary_en=EXCLUDED.summary_en,summary_ur=EXCLUDED.summary_ur,location=EXCLUDED.location,district=EXCLUDED.district,best_season=EXCLUDED.best_season,recommended_vehicle=EXCLUDED.recommended_vehicle,network_status=EXCLUDED.network_status,family_suitability_score=EXCLUDED.family_suitability_score,route_safety_score=EXCLUDED.route_safety_score,cover_image_url=EXCLUDED.cover_image_url,is_active=true,updated_at=now();
