'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,LocateFixed,Radio,RefreshCw,Search,Signal,SignalZero} from 'lucide-react';
import {AdminFrame} from '../components/admin-frame';
import {apiFetch,when} from '../lib/admin-api';

type Active={bookingId:string;bookingReference:string;driverName:string;vehicle:string;registrationNumber:string;tripStatus:string;city:string;lastUpdate?:string;stale:boolean;emergency:boolean;speedKph?:number;heading?:number;accuracy?:number};
type Point={latitude:number;longitude:number;accuracy?:number;heading?:number;speedKph?:number;batteryLevel?:number;deviceTimestamp:string;serverTimestamp:string;stale:boolean;online:boolean;emergency:boolean};
type Tracking={bookingId:string;bookingReference:string;tripStatus:string;pickupLabel:string;destinationLabel:string;pickupLatitude?:number;pickupLongitude?:number;destinationLatitude?:number;destinationLongitude?:number;driverName?:string;vehicle?:string;registrationNumber?:string;driverLocation?:Point;recentPath:Point[]};

export default function LiveTrackingPage(){const[list,setList]=useState<Active[]>([]);const[selected,setSelected]=useState<string>('');const[tracking,setTracking]=useState<Tracking|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[city,setCity]=useState('');const[emergency,setEmergency]=useState(false);const[stale,setStale]=useState(false);
 const loadList=useCallback(async()=>{try{const q=new URLSearchParams();if(search)q.set('search',search);if(status)q.set('status',status);if(city)q.set('city',city);if(emergency)q.set('emergencyOnly','true');if(stale)q.set('staleOnly','true');const result=await apiFetch<Active[]>(`/api/v1/tracking/admin/active?${q}`);setList(result);if(!selected&&result[0])setSelected(result[0].bookingId);}catch(e){setError(e instanceof Error?e.message:'Tracking list failed.')}finally{setLoading(false)}},[search,status,city,emergency,stale,selected]);
 const loadTracking=useCallback(async()=>{if(!selected){setTracking(null);return}try{setTracking(await apiFetch<Tracking>(`/api/v1/tracking/admin/${selected}`));setError('')}catch(e){setError(e instanceof Error?e.message:'Trip tracking failed.')}},[selected]);
 useEffect(()=>{const t=setTimeout(loadList,200);return()=>clearTimeout(t)},[loadList]);useEffect(()=>{loadTracking();const timer=setInterval(()=>{loadList();loadTracking()},15000);return()=>clearInterval(timer)},[loadTracking,loadList]);
 return <AdminFrame title="Live Tracking" subtitle="Active drivers, stale-location warnings and emergency visibility." actions={<button className="secondaryButton" onClick={()=>{loadList();loadTracking()}}><RefreshCw/>Refresh</button>}>
  <div className="trackingLayout"><section className="panel trackingList"><div className="trackingFilters"><label className="searchBox"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Driver, booking or registration"/></label><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All active statuses</option>{['DriverAccepted','DriverEnRoute','DriverArrived','TripStarted','Emergency'].map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={emergency} onChange={e=>setEmergency(e.target.checked)}/> Emergency only</label><label><input type="checkbox" checked={stale} onChange={e=>setStale(e.target.checked)}/> Stale only</label></div>{loading?<div className="loading"><span/><span/><span/></div>:list.length===0?<div className="empty"><LocateFixed size={40}/><h3>No active tracked trips</h3></div>:<div className="trackingRows">{list.map(x=><button key={x.bookingId} className={`${selected===x.bookingId?'selected':''} ${x.emergency?'emergency':''}`} onClick={()=>setSelected(x.bookingId)}><div className="trackingStatusIcon">{x.stale?<SignalZero/>:<Signal/>}</div><div><strong>{x.bookingReference} · {x.driverName}</strong><span>{x.vehicle} · {x.registrationNumber}</span><small>{x.city} · {x.tripStatus}</small></div><div><span className={`badge ${x.emergency?'badge-critical':x.stale?'badge-pending':'badge-active'}`}>{x.emergency?'Emergency':x.stale?'Stale':'Live'}</span><small>{x.lastUpdate?when(x.lastUpdate):'No location'}</small></div></button>)}</div>}</section>
  <section className="panel trackingMapPanel">{error&&<div className="errorBox">{error}</div>}{tracking?<><div className="panelHeader"><div><h2>{tracking.bookingReference}</h2><p>{tracking.driverName||'Driver'} · {tracking.vehicle||'Vehicle'} · {tracking.registrationNumber||'—'}</p></div><span className={`badge badge-${tracking.tripStatus.toLowerCase()}`}>{tracking.tripStatus}</span></div><TrackingMap tracking={tracking}/><div className="trackingMetrics"><div><span>Last update</span><strong>{tracking.driverLocation?when(tracking.driverLocation.serverTimestamp):'No location'}</strong></div><div><span>Speed</span><strong>{tracking.driverLocation?.speedKph?.toFixed(0)??'—'} km/h</strong></div><div><span>Heading</span><strong>{tracking.driverLocation?.heading?.toFixed(0)??'—'}°</strong></div><div><span>Accuracy</span><strong>{tracking.driverLocation?.accuracy?.toFixed(0)??'—'} m</strong></div><div><span>Connection</span><strong>{tracking.driverLocation?.online?'Online':'Offline / stale'}</strong></div><div><span>Battery</span><strong>{tracking.driverLocation?.batteryLevel??'—'}%</strong></div></div><div className="routeSummary"><div><MapDot/><span><strong>Pickup</strong>{tracking.pickupLabel}</span></div><div><MapDot destination/><span><strong>Destination</strong>{tracking.destinationLabel}</span></div></div></>:<div className="empty"><Radio size={45}/><h3>Select an active trip</h3><p>Live location and route details will appear here.</p></div>}</section></div></AdminFrame>}

function TrackingMap({tracking}:{tracking:Tracking}){const all=useMemo(()=>{const pts=[...tracking.recentPath];if(tracking.pickupLatitude!=null&&tracking.pickupLongitude!=null)pts.push({latitude:tracking.pickupLatitude,longitude:tracking.pickupLongitude} as Point);if(tracking.destinationLatitude!=null&&tracking.destinationLongitude!=null)pts.push({latitude:tracking.destinationLatitude,longitude:tracking.destinationLongitude} as Point);return pts},[tracking]);const bounds=useMemo(()=>{if(!all.length)return{minLat:33,minLng:73,maxLat:35,maxLng:75};let minLat=Math.min(...all.map(p=>p.latitude)),maxLat=Math.max(...all.map(p=>p.latitude)),minLng=Math.min(...all.map(p=>p.longitude)),maxLng=Math.max(...all.map(p=>p.longitude));if(maxLat-minLat<.01){minLat-=.01;maxLat+=.01}if(maxLng-minLng<.01){minLng-=.01;maxLng+=.01}return{minLat,minLng,maxLat,maxLng}},[all]);const project=(lat:number,lng:number)=>({x:30+((lng-bounds.minLng)/(bounds.maxLng-bounds.minLng))*740,y:30+(1-(lat-bounds.minLat)/(bounds.maxLat-bounds.minLat))*390});const path=tracking.recentPath.map(p=>project(p.latitude,p.longitude));const driver=tracking.driverLocation?project(tracking.driverLocation.latitude,tracking.driverLocation.longitude):null;const pickup=tracking.pickupLatitude!=null&&tracking.pickupLongitude!=null?project(tracking.pickupLatitude,tracking.pickupLongitude):null;const destination=tracking.destinationLatitude!=null&&tracking.destinationLongitude!=null?project(tracking.destinationLatitude,tracking.destinationLongitude):null;
 return <div className="liveMap"><svg viewBox="0 0 800 450" role="img" aria-label="Live trip map"><defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" strokeWidth=".6"/></pattern></defs><rect width="800" height="450" rx="18" className="mapBackground"/><rect width="800" height="450" rx="18" fill="url(#grid)" className="mapGrid"/>{path.length>1&&<polyline points={path.map(p=>`${p.x},${p.y}`).join(' ')} className="routePolyline"/>}{pickup&&<g transform={`translate(${pickup.x} ${pickup.y})`}><circle r="10" className="pickupMarker"/><text y="-16">Pickup</text></g>}{destination&&<g transform={`translate(${destination.x} ${destination.y})`}><circle r="10" className="destinationMarker"/><text y="-16">Destination</text></g>}{driver&&<g transform={`translate(${driver.x} ${driver.y})`}><circle r="18" className={tracking.driverLocation?.emergency?'driverPulse emergencyPulse':'driverPulse'}/><circle r="9" className="driverMarker"/><text y="-25">Driver</text></g>}</svg>{tracking.driverLocation?.stale&&<div className="staleOverlay"><AlertTriangle/>Location is stale</div>}</div>}
function MapDot({destination=false}:{destination?:boolean}){return <i className={destination?'destinationDot':'pickupDot'}/>}
