import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../../core/state/app_controller.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/common_widgets.dart';

class LiveCreatePackageScreen extends StatefulWidget{const LiveCreatePackageScreen({super.key});@override State<LiveCreatePackageScreen> createState()=>_LiveCreatePackageScreenState();}
class _LiveCreatePackageScreenState extends State<LiveCreatePackageScreen>{
 static const destinations=<String,String>{'10000000-0000-0000-0000-000000000001':'Muzaffarabad','10000000-0000-0000-0000-000000000002':'Neelum Valley','10000000-0000-0000-0000-000000000003':'Sharda','10000000-0000-0000-0000-000000000004':'Rawalakot','10000000-0000-0000-0000-000000000005':'Banjosa Lake','10000000-0000-0000-0000-000000000006':'Pir Chinasi'};
 final _form=GlobalKey<FormState>();final _title=TextEditingController(text:'3-Day Neelum Valley Family Tour');final _start=TextEditingController(text:'Muzaffarabad');final _pickup=TextEditingController(text:'Ghari Pan Pickup Point');final _seatPrice=TextEditingController(text:'12000');final _vehiclePrice=TextEditingController(text:'95000');final _description=TextEditingController(text:'A safe family tourism package with a verified local Driver.');final _itinerary=TextEditingController(text:'Day 1: Muzaffarabad to Keran\nDay 2: Sharda and local sightseeing\nDay 3: Return to Muzaffarabad');
 String? _vehicleId;String _destinationId=destinations.keys.elementAt(1);DateTime _departure=DateTime.now().add(const Duration(days:14));DateTime _return=DateTime.now().add(const Duration(days:17));int _seats=7;bool _family=true;bool _women=false;bool _offers=true;bool _fuel=true;bool _toll=true;bool _hotel=false;bool _meals=false;bool _guide=false;bool _jeep=false;bool _busy=false;
 @override void dispose(){for(final c in [_title,_start,_pickup,_seatPrice,_vehiclePrice,_description,_itinerary]){c.dispose();}super.dispose();}
 @override Widget build(BuildContext context){final vehicles=AppControllerScope.of(context).liveVehicles.where((v)=>v.status=='Verified').toList();_vehicleId??=vehicles.isEmpty?null:vehicles.first.id;return Scaffold(appBar:AppBar(title:const Text('Create live package')),body:Form(key:_form,child:ListView(padding:const EdgeInsets.fromLTRB(18,6,18,30),children:[
   PremiumCard(color:const Color(0xFFF1FAF6),child:const Row(children:[Icon(Icons.admin_panel_settings_rounded,color:AppColors.primaryDark),SizedBox(width:10),Expanded(child:Text('Package remains private until Admin approves route, vehicle, pricing and safety readiness.',style:TextStyle(color:AppColors.primaryDark,fontWeight:FontWeight.w700,height:1.35)))])),const SizedBox(height:14),
   TextFormField(controller:_title,decoration:const InputDecoration(labelText:'Package title',prefixIcon:Icon(Icons.luggage_rounded)),validator:_required),const SizedBox(height:10),
   DropdownButtonFormField<String>(initialValue:_destinationId,decoration:const InputDecoration(labelText:'Destination',prefixIcon:Icon(Icons.landscape_rounded)),items:destinations.entries.map((e)=>DropdownMenuItem(value:e.key,child:Text(e.value))).toList(),onChanged:(v)=>setState(()=>_destinationId=v!)),const SizedBox(height:10),
   if(vehicles.isEmpty)PremiumCard(color:const Color(0xFFFFF5E5),child:const Text('No verified vehicle is available. Admin must verify a vehicle first.',style:TextStyle(color:AppColors.warning,fontWeight:FontWeight.w800)))else DropdownButtonFormField<String>(initialValue:_vehicleId,decoration:const InputDecoration(labelText:'Verified vehicle',prefixIcon:Icon(Icons.directions_car_rounded)),items:vehicles.map((v)=>DropdownMenuItem(value:v.id,child:Text('${v.make} ${v.model} · ${v.registrationNumber}'))).toList(),onChanged:(v)=>setState(()=>_vehicleId=v)),const SizedBox(height:10),
   TextFormField(controller:_start,decoration:const InputDecoration(labelText:'Starting city',prefixIcon:Icon(Icons.location_city_rounded)),validator:_required),const SizedBox(height:10),TextFormField(controller:_pickup,decoration:const InputDecoration(labelText:'Pickup point',prefixIcon:Icon(Icons.trip_origin_rounded)),validator:_required),const SizedBox(height:10),
   Row(children:[Expanded(child:_DateField(label:'Departure',date:_departure,onTap:()=>_pick(true))),const SizedBox(width:10),Expanded(child:_DateField(label:'Return',date:_return,onTap:()=>_pick(false)))]),const SizedBox(height:10),
   PremiumCard(child:Row(children:[const Expanded(child:Text('Total passenger seats',style:TextStyle(fontWeight:FontWeight.w900))),IconButton(onPressed:_seats>1?()=>setState(()=>_seats--):null,icon:const Icon(Icons.remove_circle_outline_rounded)),Text('$_seats',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18)),IconButton(onPressed:()=>setState(()=>_seats++),icon:const Icon(Icons.add_circle_outline_rounded))])),const SizedBox(height:10),
   Row(children:[Expanded(child:TextFormField(controller:_seatPrice,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Price per seat',prefixText:'PKR '),validator:_required)),const SizedBox(width:10),Expanded(child:TextFormField(controller:_vehiclePrice,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Whole vehicle',prefixText:'PKR '),validator:_required))]),const SizedBox(height:10),
   TextFormField(controller:_description,maxLines:3,decoration:const InputDecoration(labelText:'Description',prefixIcon:Icon(Icons.description_rounded))),const SizedBox(height:10),TextFormField(controller:_itinerary,maxLines:5,decoration:const InputDecoration(labelText:'Itinerary — one item per line',prefixIcon:Icon(Icons.route_rounded))),const SizedBox(height:12),
   PremiumCard(child:Column(children:[SwitchListTile.adaptive(contentPadding:EdgeInsets.zero,value:_family,onChanged:(v)=>setState(()=>_family=v),title:const Text('Family-only departure',style:TextStyle(fontWeight:FontWeight.w800))),SwitchListTile.adaptive(contentPadding:EdgeInsets.zero,value:_women,onChanged:(v)=>setState(()=>_women=v),title:const Text('Women-only departure',style:TextStyle(fontWeight:FontWeight.w800))),SwitchListTile.adaptive(contentPadding:EdgeInsets.zero,value:_offers,onChanged:(v)=>setState(()=>_offers=v),title:const Text('Allow customer offers',style:TextStyle(fontWeight:FontWeight.w800)))])),const SizedBox(height:12),
   PremiumCard(child:Wrap(spacing:8,runSpacing:8,children:[_Flag(label:'Fuel',value:_fuel,onChanged:(v)=>setState(()=>_fuel=v)),_Flag(label:'Toll',value:_toll,onChanged:(v)=>setState(()=>_toll=v)),_Flag(label:'Hotel',value:_hotel,onChanged:(v)=>setState(()=>_hotel=v)),_Flag(label:'Meals',value:_meals,onChanged:(v)=>setState(()=>_meals=v)),_Flag(label:'Guide',value:_guide,onChanged:(v)=>setState(()=>_guide=v)),_Flag(label:'Jeep transfer',value:_jeep,onChanged:(v)=>setState(()=>_jeep=v))])),const SizedBox(height:16),
   FilledButton.icon(onPressed:_busy||_vehicleId==null?null:_save,icon:_busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.save_rounded),label:const Text('Save live draft')),
 ])));
 }
 Future<void> _pick(bool departure)async{final current=departure?_departure:_return;final date=await showDatePicker(context:context,initialDate:current,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:500)));if(date!=null)setState((){if(departure){_departure=DateTime(date.year,date.month,date.day,7);if(_return.isBefore(_departure))_return=_departure.add(const Duration(days:2));}else{_return=DateTime(date.year,date.month,date.day,18);}});}
 Future<void> _save()async{if(!_form.currentState!.validate())return;setState(()=>_busy=true);try{final p=await AppControllerScope.of(context).createLiveDriverPackage({'vehicleId':_vehicleId,'destinationId':_destinationId,'title':_title.text.trim(),'startingCity':_start.text.trim(),'pickupPoint':_pickup.text.trim(),'departureAt':_departure.toUtc().toIso8601String(),'returnAt':_return.toUtc().toIso8601String(),'totalSeats':_seats,'pricePerSeat':double.parse(_seatPrice.text),'wholeVehiclePrice':double.parse(_vehiclePrice.text),'familyOnly':_family,'womenOnly':_women,'customerOffersAllowed':_offers,'description':_description.text.trim(),'cancellationPolicy':'Free cancellation before 48 hours. Admin-approved policy applies.','passengerPolicy':_family?'Verified family passengers only':'Verified passengers only','luggageAllowance':'One standard bag per passenger','routeStops':['Kohala','Keran','Sharda'],'inclusions':[if(_fuel)'Fuel',if(_toll)'Toll',if(_hotel)'Hotel',if(_meals)'Meals',if(_guide)'Local guide',if(_jeep)'Jeep transfer'],'exclusions':['Personal expenses'],'itinerary':_itinerary.text.split('\n').where((e)=>e.trim().isNotEmpty).toList(),'fuelIncluded':_fuel,'tollIncluded':_toll,'hotelIncluded':_hotel,'mealsIncluded':_meals,'guideIncluded':_guide,'jeepTransferIncluded':_jeep,'driverAccommodationIncluded':true});if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Draft ${p.title} saved.')));Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>_busy=false);}}
 String? _required(String? v)=>v==null||v.trim().isEmpty?'Required':null;
}
class _DateField extends StatelessWidget{const _DateField({required this.label,required this.date,required this.onTap});final String label;final DateTime date;final VoidCallback onTap;@override Widget build(BuildContext context)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(16),child:InputDecorator(decoration:InputDecoration(labelText:label,prefixIcon:const Icon(Icons.calendar_month_rounded)),child:Text(DateFormat('dd MMM yyyy').format(date))));}
class _Flag extends StatelessWidget{const _Flag({required this.label,required this.value,required this.onChanged});final String label;final bool value;final ValueChanged<bool> onChanged;@override Widget build(BuildContext context)=>FilterChip(label:Text(label),selected:value,onSelected:onChanged);}
