'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeftRight,CalendarClock,Car,CheckCircle2,Clock3,MapPin,Search,Send,UserRoundCheck,X} from 'lucide-react';
import {AdminFrame} from '../components/admin-frame';
import {apiFetch,when,money} from '../lib/admin-api';

type Summary={upcoming:number;pendingAssignments:number;awaitingDriverResponse:number;active:number;completed:number;cancelled:number;emergency:number;disputed:number};
type Row={id:string;bookingReference:string;customerName:string;customerPhone:string;driverName?:string;driverPhone?:string;vehicle?:string;vehicleRegistration?:string;pickupLabel?:string;destinationLabel?:string;pickupAt:string;returnAt?:string;bookingType:string;passengerCount:number;paymentStatus:string;tripStatus:string;operationalStatus:string;lastActivityAt:string;emergency:boolean};
type Dashboard={summary:Summary;bookings:{items:Row[];page:number;pageSize:number;totalCount:number;totalPages:number}};
type Driver={driverProfileId:string;driverName:string;phone:string;verificationStatus:string;isOnline:boolean;activeTrips:number;rating:number;city:string;vehicleId?:string;vehicle?:string;registration?:string;capacity?:number;vehicleStatus:string;distanceKm?:number;available:boolean;unavailableReason?:string};
type Detail={booking:Row;customer:{fullName:string;phoneNumber:string;email?:string};driver?:{fullName:string;phoneNumber:string};vehicle?:{id:string;make:string;model:string;registrationNumber:string;category:string;passengerCapacity:number;status:string};tourismPackage?:string;fare:number;specialInstructions?:string;emergencyContact?:string;timeline:Array<{status:string;previousStatus?:string;source:string;reason?:string;changedBy?:string;createdAt:string}>;notes:Array<{id:string;noteType:string;note:string;author:string;isCustomerVisible:boolean;createdAt:string}>;offers:Array<{id:string;driverName:string;vehicle?:string;status:string;expiresAt:string;rejectionReason?:string}>;version:number};

const states=['','Pending','Confirmed','DriverAssigned','DriverAccepted','DriverEnRoute','DriverArrived','TripStarted','TripCompleted','Cancelled','NoShow','Disputed','Emergency','Suspended','PendingAssignment','OfferSent','DriverRejected','ReassignmentRequired'];

export default function OperationsPage(){
 const [data,setData]=useState<Dashboard|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<string|null>(null);
 const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [payment,setPayment]=useState('');const [city,setCity]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(25);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const q=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(search)q.set('search',search);if(status)q.set('status',status);if(payment)q.set('paymentStatus',payment);if(city)q.set('city',city);if(from)q.set('from',new Date(`${from}T00:00:00`).toISOString());if(to)q.set('to',new Date(`${to}T23:59:59`).toISOString());setData(await apiFetch<Dashboard>(`/api/v1/admin/trip-operations?${q}`));}catch(e){setError(e instanceof Error?e.message:'Operations could not be loaded.')}finally{setLoading(false)}},[page,pageSize,search,status,payment,city,from,to]);
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 const cards=useMemo(()=>data?[['Upcoming',data.summary.upcoming,CalendarClock],['Pending assignment',data.summary.pendingAssignments,UserRoundCheck],['Awaiting response',data.summary.awaitingDriverResponse,Clock3],['Active trips',data.summary.active,Car],['Completed',data.summary.completed,CheckCircle2],['Emergency',data.summary.emergency,AlertTriangle],['Disputed',data.summary.disputed,ArrowLeftRight],['Cancelled',data.summary.cancelled,X]] as const:[],[data]);
 return <AdminFrame title="Operations & Dispatch" subtitle="Live booking control, driver assignment and end-to-end trip lifecycle.">
  <div className="operationsStats">{cards.map(([label,value,Icon])=><button key={label} className="operationStat" onClick={()=>{setStatus(label==='Emergency'?'Emergency':'');setPage(1)}}><Icon/><span>{label}</span><strong>{value}</strong></button>)}</div>
  <section className="panel"><div className="operationsFilters"><label className="searchBox"><Search/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Booking, customer, driver or registration"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{states.map(x=><option key={x} value={x}>{x||'All statuses'}</option>)}</select><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">All payments</option>{['Pending','Authorized','Paid','Failed','Refunded','PartiallyRefunded'].map(x=><option key={x}>{x}</option>)}</select><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City / destination"/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[25,50,100].map(x=><option key={x} value={x}>{x} rows</option>)}</select></div>
  {error&&<div className="errorBox">{error}</div>}{loading?<div className="loading"><span/><span/><span/></div>:!data?.bookings.items.length?<div className="empty"><h3>No operational bookings</h3><p>Try changing the filters.</p></div>:<div className="tableWrap"><table className="operationsTable"><thead><tr><th>Reference</th><th>Customer</th><th>Driver / Vehicle</th><th>Route</th><th>Pickup</th><th>Type</th><th>Passengers</th><th>Payment</th><th>Trip</th><th>Last activity</th></tr></thead><tbody>{data.bookings.items.map(row=><tr key={row.id} className={`clickable ${row.emergency?'emergencyRow':''}`} onClick={()=>setSelected(row.id)}><td><strong>{row.bookingReference}</strong></td><td>{row.customerName}<small>{row.customerPhone}</small></td><td>{row.driverName||'Not assigned'}<small>{row.vehicleRegistration||row.vehicle||'—'}</small></td><td>{row.pickupLabel||'—'}<small>→ {row.destinationLabel||'—'}</small></td><td>{when(row.pickupAt)}</td><td>{row.bookingType}</td><td>{row.passengerCount}</td><td><span className={`badge badge-${row.paymentStatus.toLowerCase()}`}>{row.paymentStatus}</span></td><td><span className={`badge badge-${row.tripStatus.toLowerCase()}`}>{row.tripStatus}</span><small>{row.operationalStatus}</small></td><td>{when(row.lastActivityAt)}</td></tr>)}</tbody></table></div>}
  {data&&<div className="pager"><span>{data.bookings.totalCount} records</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><strong>Page {page} of {Math.max(1,data.bookings.totalPages)}</strong><button disabled={page>=data.bookings.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</section>
  {selected&&<OperationsDrawer bookingId={selected} onClose={()=>setSelected(null)} onChanged={load}/>}</AdminFrame>
}

function OperationsDrawer({bookingId,onClose,onChanged}:{bookingId:string;onClose:()=>void;onChanged:()=>void}){const[detail,setDetail]=useState<Detail|null>(null);const[drivers,setDrivers]=useState<Driver[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[selectedDriver,setSelectedDriver]=useState('');const[note,setNote]=useState('');const[reason,setReason]=useState('');const[nextStatus,setNextStatus]=useState('');
 const load=useCallback(async()=>{setError('');try{const[d,ds]=await Promise.all([apiFetch<Detail>(`/api/v1/admin/trip-operations/${bookingId}`),apiFetch<Driver[]>(`/api/v1/admin/trip-operations/${bookingId}/suitable-drivers`)]);setDetail(d);setDrivers(ds);setNextStatus(d.booking.tripStatus);}catch(e){setError(e instanceof Error?e.message:'Booking detail failed.')}},[bookingId]);useEffect(()=>{load()},[load]);
 const chosen=drivers.find(x=>x.driverProfileId===selectedDriver);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load();onChanged()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}}
 if(!detail)return <div className="sideShade" onMouseDown={onClose}><aside className="operationsDrawer" onMouseDown={e=>e.stopPropagation()}><header><h2>Booking operations</h2><button className="iconButton" onClick={onClose}><X/></button></header>{error?<div className="errorBox">{error}</div>:<div className="loading"><span/><span/><span/></div>}</aside></div>;
 return <div className="sideShade" onMouseDown={onClose}><aside className="operationsDrawer" onMouseDown={e=>e.stopPropagation()}><header><div><small>{detail.booking.bookingReference}</small><h2>{detail.booking.pickupLabel} → {detail.booking.destinationLabel}</h2></div><button className="iconButton" onClick={onClose}><X/></button></header>{error&&<div className="errorBox">{error}</div>}
  <div className="drawerBody"><div className="drawerBadges"><span className={`badge badge-${detail.booking.tripStatus.toLowerCase()}`}>{detail.booking.tripStatus}</span><span className="badge">{detail.booking.operationalStatus}</span><span className={`badge badge-${detail.booking.paymentStatus.toLowerCase()}`}>{detail.booking.paymentStatus}</span></div>
  <section className="compactDetail"><h3>Booking & people</h3><div><span>Customer</span><strong>{detail.customer.fullName}</strong><small>{detail.customer.phoneNumber}</small></div><div><span>Driver</span><strong>{detail.driver?.fullName||'Not assigned'}</strong><small>{detail.driver?.phoneNumber||'—'}</small></div><div><span>Vehicle</span><strong>{detail.vehicle?`${detail.vehicle.make} ${detail.vehicle.model}`:'Not assigned'}</strong><small>{detail.vehicle?`${detail.vehicle.registrationNumber} · ${detail.vehicle.passengerCapacity} seats`:'—'}</small></div><div><span>Pickup</span><strong>{when(detail.booking.pickupAt)}</strong><small>{detail.booking.pickupLabel}</small></div><div><span>Booking</span><strong>{detail.booking.bookingType} · {detail.booking.passengerCount} passenger(s)</strong><small>{detail.tourismPackage||'Ride booking'}</small></div><div><span>Fare</span><strong>{money(detail.fare)}</strong><small>{detail.booking.paymentStatus}</small></div></section>
  <section className="drawerSection"><h3>Assign or send offer</h3><select value={selectedDriver} onChange={e=>setSelectedDriver(e.target.value)}><option value="">Select suitable driver</option>{drivers.map(d=><option key={d.driverProfileId} value={d.driverProfileId} disabled={!d.available}>{d.driverName} · {d.registration||'No vehicle'} · {d.capacity??0} seats {d.available?'':'('+d.unavailableReason+')'}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Assignment / offer notes" rows={2}/><div className="buttonRow compactButtons"><button className="primaryButton" disabled={busy||!chosen?.available||!chosen.vehicleId} onClick={()=>act(()=>apiFetch(`/api/v1/admin/trip-operations/${bookingId}/assign`,{method:'POST',body:JSON.stringify({driverProfileId:chosen!.driverProfileId,vehicleId:chosen!.vehicleId,notes:note})}))}><UserRoundCheck/>Assign now</button><button className="secondaryButton" disabled={busy||!chosen?.available||!chosen.vehicleId} onClick={()=>act(()=>apiFetch(`/api/v1/admin/trip-operations/${bookingId}/offers`,{method:'POST',body:JSON.stringify({driverProfileId:chosen!.driverProfileId,vehicleId:chosen!.vehicleId,expiresInMinutes:15,notes:note})}))}><Send/>Send offer</button></div></section>
  <section className="drawerSection"><h3>Trip lifecycle / override</h3><select value={nextStatus} onChange={e=>setNextStatus(e.target.value)}>{states.filter(Boolean).map(x=><option key={x}>{x}</option>)}</select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required reason for cancellations, disputes and overrides" rows={2}/><button className="primaryButton wide" disabled={busy} onClick={()=>act(()=>apiFetch(`/api/v1/admin/trip-operations/${bookingId}/status`,{method:'PUT',body:JSON.stringify({status:nextStatus,reason,expectedVersion:detail.version,override:false})}))}>Apply controlled transition</button></section>
  <section className="drawerSection"><h3>Offer history</h3>{detail.offers.length?detail.offers.map(o=><div className="offerLine" key={o.id}><div><strong>{o.driverName}</strong><small>{o.vehicle}</small></div><span className={`badge badge-${o.status.toLowerCase()}`}>{o.status}</span></div>):<p className="muted">No driver offers sent.</p>}</section>
  <section className="drawerSection"><h3>Operational timeline</h3><div className="timeline">{detail.timeline.map((x,i)=><div key={`${x.createdAt}-${i}`}><i/><div><strong>{x.status}</strong><span>{x.changedBy||x.source} · {when(x.createdAt)}</span>{x.reason&&<p>{x.reason}</p>}</div></div>)}</div></section>
  <section className="drawerSection"><h3>Internal notes</h3>{detail.notes.map(n=><div className="noteLine" key={n.id}><strong>{n.noteType}</strong><p>{n.note}</p><small>{n.author} · {when(n.createdAt)}</small></div>)}</section></div></aside></div>}
