import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../core/booking/trip_operations_repository.dart';
import '../../core/services/trip_location_service.dart';
import '../../core/state/app_controller.dart';
import '../../models/trip_operations_models.dart';

class DriverOperationsScreen extends StatefulWidget{const DriverOperationsScreen({super.key});@override State<DriverOperationsScreen> createState()=>_DriverOperationsScreenState();}
class _DriverOperationsScreenState extends State<DriverOperationsScreen>{TripOperationsRepository? _repo;TripLocationService? _location;List<DriverTripOffer> _offers=[];List<MobileTrip> _trips=[];bool _busy=true;String? _error;
 @override void didChangeDependencies(){super.didChangeDependencies();if(_repo==null){_repo=TripOperationsRepository(AppController.of(context).apiClient);_location=TripLocationService(_repo!);_load();}}
 @override void dispose(){_location?.stop();super.dispose();}
 Future<void> _load()async{setState(()=>_busy=true);try{final values=await Future.wait([_repo!.driverOffers(),_repo!.driverTrips()]);if(!mounted)return;_offers=values[0] as List<DriverTripOffer>;_trips=values[1] as List<MobileTrip>;_error=null;final active=_trips.where((x)=>['DriverAccepted','DriverEnRoute','DriverArrived','TripStarted','Emergency'].contains(x.tripStatus)).firstOrNull;if(active!=null){await _location!.start(active.bookingId,active.tripStatus);}else{_location!.stop();}}catch(e){_error=e.toString();}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _respond(DriverTripOffer offer,bool accept)async{String? reason;if(!accept){reason=await _reasonDialog('Why are you rejecting this offer?');if(reason==null)return;}await _run(()=>_repo!.respondOffer(offer.offerId,accept:accept,reason:reason));}
 Future<void> _status(MobileTrip trip,String status)async{String? reason;if(status=='Emergency'||status=='TripCompleted'){reason=await _reasonDialog(status=='Emergency'?'Describe the emergency':'Completion note (optional)',optional:status=='TripCompleted');if(reason==null&&status=='Emergency')return;}await _run(()=>_repo!.driverStatus(trip.bookingId,status,reason:reason));}
 Future<void> _run(Future<void> Function() fn)async{try{await fn();await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
 Future<String?> _reasonDialog(String title,{bool optional=false})async{final c=TextEditingController();final result=await showDialog<String?>(context:context,builder:(context)=>AlertDialog(title:Text(title),content:TextField(controller:c,maxLines:3,decoration:InputDecoration(hintText:optional?'Optional note':'Reason is required')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Submit'))]));c.dispose();return result;}
 @override Widget build(BuildContext context)=>SafeArea(child:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Trip Operations',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Offers, assigned trips and live trip controls.',style:TextStyle(color:Colors.black54)),if(_error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(_error!,style:const TextStyle(color:Colors.red))),const SizedBox(height:16),if(_busy)const Center(child:CircularProgressIndicator())else...[_SectionTitle('New booking offers',_offers.length),if(_offers.isEmpty)const _Empty('No pending offers.'),..._offers.map((x)=>_OfferCard(x,onAccept:()=>_respond(x,true),onReject:()=>_respond(x,false))),const SizedBox(height:18),_SectionTitle('Assigned and active trips',_trips.length),if(_trips.isEmpty)const _Empty('No assigned trips.'),..._trips.map((x)=>_TripCard(x,onStatus:(s)=>_status(x,s)))]])));
}
class _SectionTitle extends StatelessWidget{const _SectionTitle(this.label,this.count);final String label;final int count;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[Expanded(child:Text(label,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800))),Chip(label:Text('$count'))]));}
class _Empty extends StatelessWidget{const _Empty(this.text);final String text;@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Text(text)));}
class _OfferCard extends StatelessWidget{const _OfferCard(this.offer,{required this.onAccept,required this.onReject});final DriverTripOffer offer;final VoidCallback onAccept,onReject;@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(offer.bookingReference,style:const TextStyle(fontWeight:FontWeight.w900))),Text(DateFormat('dd MMM, HH:mm').format(offer.pickupAt.toLocal()))]),const SizedBox(height:8),Text('${offer.pickupLabel} → ${offer.destinationLabel}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('${offer.customerName} · ${offer.passengerCount} passenger(s) · ${offer.bookingType}'),Text('${offer.vehicle} · ${offer.registrationNumber}',style:const TextStyle(color:Colors.black54)),if(offer.notes?.isNotEmpty==true)Padding(padding:const EdgeInsets.only(top:8),child:Text(offer.notes!)),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton(onPressed:onReject,child:const Text('Reject'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:onAccept,child:const Text('Accept')))])])));}
class _TripCard extends StatelessWidget{const _TripCard(this.trip,{required this.onStatus});final MobileTrip trip;final ValueChanged<String> onStatus;List<String> get actions=>switch(trip.tripStatus){'DriverAccepted'=>['DriverEnRoute','Emergency'],'DriverEnRoute'=>['DriverArrived','Emergency'],'DriverArrived'=>['TripStarted','Emergency'],'TripStarted'=>['TripCompleted','Emergency'],'Emergency'=>['DriverEnRoute','DriverArrived','TripStarted'],_=>[]};@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(trip.bookingReference,style:const TextStyle(fontWeight:FontWeight.w900))),Chip(label:Text(trip.tripStatus))]),Text('${trip.pickupLabel} → ${trip.destinationLabel}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('${DateFormat('dd MMM, HH:mm').format(trip.pickupAt.toLocal())} · ${trip.passengerCount} passenger(s)'),Text('${trip.customerName} · ${trip.customerPhone}',style:const TextStyle(color:Colors.black54)),if(trip.instructions?.isNotEmpty==true)Padding(padding:const EdgeInsets.only(top:8),child:Text('Instructions: ${trip.instructions}')),if(actions.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Wrap(spacing:8,runSpacing:8,children:actions.map((s)=>FilledButton.tonal(onPressed:()=>onStatus(s),child:Text(s=='DriverEnRoute'?'Mark En Route':s=='DriverArrived'?'Mark Arrived':s=='TripStarted'?'Start Trip':s=='TripCompleted'?'Complete Trip':'Emergency'))).toList()))])));}
extension _FirstOrNull<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}
