import 'package:flutter/material.dart';

class AppStrings {
  static const supportedLocales = [Locale('en'), Locale('ur')];

  static const Map<String, Map<String, String>> _text = {
    'en': {
      'appName': 'uDrive',
      'tagline': 'Explore freely. Ride confidently.',
      'login': 'Login',
      'welcomeBack': 'Welcome to uDrive',
      'loginSubtitle': 'Book rides, discover Kashmir and earn as a verified driver.',
      'phone': 'Mobile number',
      'continue': 'Continue',
      'demoLogin': 'Use demo account',
      'otpTitle': 'Verify your number',
      'otpSubtitle': 'Enter the 4-digit code. Demo code is 1234.',
      'verify': 'Verify & continue',
      'logout': 'Logout',
      'home': 'Home',
      'bookRide': 'Book a ride',
      'explore': 'Explore Kashmir',
      'packages': 'Tour packages',
      'trips': 'My trips',
      'wallet': 'Wallet',
      'savedPlaces': 'Saved places',
      'safety': 'Safety centre',
      'notifications': 'Notifications',
      'support': 'Help & support',
      'settings': 'Settings',
      'profile': 'Profile',
      'customerMode': 'Customer mode',
      'driverMode': 'Driver mode',
      'switchDriver': 'Switch to Driver mode',
      'switchCustomer': 'Switch to Customer mode',
      'goodMorning': 'Good morning, Shahzad',
      'whereTo': 'Where are you going?',
      'pickup': 'Pickup location',
      'destination': 'Destination',
      'dateTime': 'Date & time',
      'passengers': 'Passengers',
      'luggage': 'Luggage',
      'vehicle': 'Vehicle',
      'suggestedFare': 'Suggested fare',
      'yourOffer': 'Your offer',
      'requestRide': 'Request drivers',
      'driverOffers': 'Driver offers',
      'selectDriver': 'Select driver',
      'localRide': 'Local ride',
      'intercity': 'Intercity',
      'fullDay': 'Full-day hire',
      'jeep': '4×4 Jeep',
      'sharedRide': 'Shared ride',
      'airport': 'Airport transfer',
      'activeTrip': 'Active trip',
      'viewTrip': 'View trip',
      'roadAlert': 'Road advisory',
      'popularPlaces': 'Popular places',
      'recommendedPackages': 'Recommended packages',
      'viewAll': 'View all',
      'bookNow': 'Book now',
      'sendOffer': 'Send price offer',
      'included': 'Included',
      'itinerary': 'Itinerary',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'addMoney': 'Add money',
      'sendMoney': 'Send money',
      'transactions': 'Transactions',
      'emergency': 'Emergency SOS',
      'shareTrip': 'Share live trip',
      'trustedContacts': 'Trusted contacts',
      'reportIssue': 'Report a safety issue',
      'online': 'Online',
      'offline': 'Offline',
      'driverDashboard': 'Driver dashboard',
      'rideRequests': 'Ride requests',
      'myPackages': 'My packages',
      'createPackage': 'Create package',
      'earnings': 'Earnings',
      'payouts': 'Wallet & payouts',
      'vehicles': 'Vehicle registration',
      'documents': 'Documents & verification',
      'availability': 'Availability',
      'reviews': 'Ratings & reviews',
      'accept': 'Accept',
      'counterOffer': 'Counteroffer',
      'decline': 'Decline',
      'todayEarnings': "Today's earnings",
      'weeklyEarnings': 'Weekly earnings',
      'availableBalance': 'Available balance',
      'withdraw': 'Request payout',
      'registerVehicle': 'Register a vehicle',
      'addVehicle': 'Add vehicle',
      'editVehicle': 'Edit vehicle',
      'vehicleDetails': 'Vehicle details',
      'capabilities': 'Capacity & capabilities',
      'uploadDocuments': 'Documents & photos',
      'reviewSubmit': 'Review & submit',
      'make': 'Make',
      'model': 'Model',
      'year': 'Year',
      'color': 'Color',
      'registrationNo': 'Registration number',
      'category': 'Vehicle category',
      'seats': 'Passenger seats',
      'luggageCapacity': 'Luggage capacity',
      'airConditioning': 'Air conditioning',
      'fourWheelDrive': '4×4 capability',
      'vehiclePhotos': 'Vehicle photos',
      'registrationDoc': 'Registration document',
      'insuranceDoc': 'Insurance document',
      'fitnessDoc': 'Fitness certificate',
      'upload': 'Upload',
      'uploaded': 'Uploaded',
      'submitVerification': 'Submit for verification',
      'saveDraft': 'Save draft',
      'packageTitle': 'Package title',
      'startLocation': 'Starting location',
      'duration': 'Duration',
      'maxGuests': 'Maximum guests',
      'packagePrice': 'Package price',
      'allowOffers': 'Allow customer offers',
      'description': 'Description',
      'inclusions': 'Inclusions',
      'exclusions': 'Exclusions',
      'submitApproval': 'Submit for approval',
      'dummyReady': 'Demo data is active',
      'search': 'Search',
      'close': 'Close',
      'save': 'Save',
      'next': 'Next',
      'back': 'Back',
      'done': 'Done',
      'language': 'Language',
      'english': 'English',
      'urdu': 'Urdu',
      'appearance': 'Appearance',
      'privacy': 'Privacy',
      'terms': 'Terms & conditions',
      'about': 'About uDrive',
      'noData': 'No data available',
      'required': 'This field is required',
      'invalidPhone': 'Enter a valid mobile number',
      'invalidOtp': 'Use demo code 1234',
      'success': 'Completed successfully',
      'verified': 'Verified',
      'pending': 'Pending review',
      'active': 'Active',
      'draft': 'Draft',
      'advanceBooking': 'Advance booking',
      'bookingStepOneHelp': 'Choose your route and preferred travel time.',
      'departureDate': 'Departure date',
      'departureTime': 'Departure time',
      'returnTrip': 'Add return journey',
      'returnTripHelp': 'Reserve both directions in one request.',
      'returnDate': 'Return date',
      'travelDetails': 'How are you travelling?',
      'bookingStepTwoHelp': 'Choose seats or reserve the complete vehicle.',
      'bookPerSeat': 'Book per seat',
      'perSeat': 'Per seat',
      'perSeatHelp': 'Pay only for the seats your group needs.',
      'bookWholeVehicle': 'Book whole vehicle',
      'wholeVehicle': 'Whole vehicle',
      'wholeVehicleHelp': 'Keep the complete vehicle private for your group.',
      'adults': 'Adults',
      'children': 'Children',
      'travellerPreference': 'Traveller preference',
      'family': 'Family',
      'individual': 'Individual',
      'womenOnly': 'Women only',
      'group': 'Group',
      'familyOnly': 'Family only',
      'familyOnlyPreference': 'Prefer a family-only shared trip',
      'femalePassengerPreference': 'Prefer female/family passenger group',
      'selectVehicle': 'Select the right vehicle',
      'bookingStepThreeHelp': 'We recommend vehicles according to route and group size.',
      'recommended': 'Recommended',
      'specialInstructions': 'Special instructions',
      'specialInstructionsHint': 'Child seat, elderly assistance, hotel pickup…',
      'reviewBooking': 'Review your booking',
      'bookingStepFourHelp': 'Clear pricing and verified drivers before confirmation.',
      'bookingOption': 'Booking option',
      'transparentPrice': 'Transparent price estimate',
      'seatFare': 'Seat fare',
      'vehicleFare': 'Vehicle fare',
      'estimatedTotal': 'Estimated total',
      'noHiddenCharges': 'No hidden charges. Final driver offer is shown before confirmation.',
      'secureBookingMessage': 'Only verified drivers and approved vehicles can respond to this tourism booking.',
      'findVerifiedDrivers': 'Find verified drivers',
      'joinTour': 'Join a Tour',
      'availableTours': 'Available tours',
      'registerInterest': 'Register interest',
      'joinTourHeadline': 'Travel together, safely',
      'joinTourSubtitle': 'Join verified departures, compare per-seat and whole-vehicle fares, and see privacy-safe passenger information.',
      'all': 'All',
      'noMatchingTours': 'No matching tours found',
      'match': 'Match',
      'seatsLeft': 'seats left',
      'securePassengerSummary': 'Secure passenger summary',
      'male': 'Male',
      'female': 'Female',
      'verifiedTripProtection': 'Verified trip protection',
      'otpTripStart': 'Trip starts with customer OTP verification',
      'liveLocationSharing': 'Live trip sharing with trusted contacts',
      'privatePassengerData': 'Passenger names and phone numbers remain private',
      'supportMonitoring': 'uDrive safety support can monitor reported incidents',
      'tourSeatReserved': 'Tour reservation saved',
      'perSeatReservationSuccess': 'Your seats are reserved in this dummy tour. Payment and live confirmation will be connected later.',
      'wholeVehicleReservationSuccess': 'The whole vehicle is reserved in this dummy tour. Payment and live confirmation will be connected later.',
      'pickupCity': 'Pickup city or point',
      'dateFrom': 'Date from',
      'dateTo': 'Date to',
      'tourType': 'Tour group type',
      'vehiclePreference': 'Vehicle preference',
      'budgetPerSeat': 'Budget per seat',
      'notifyMatchingTour': 'Register & notify me',
      'interestPrivacyMessage': 'Your contact details will not be shown publicly. You will only receive matching-tour notifications.',
      'cannotFindTour': 'Cannot find your tour?',
      'registerAndNotify': 'Register your destination and dates. We will show matching vehicles when a driver creates one.',
      'numberOfPersons': 'Number of persons',
      'tourInterestRegistered': 'Tour interest registered',
      'tourInterestSuccessMessage': 'We found sample matching departures and will notify you when a suitable vehicle is available.',
      'familyTourPlanner': 'Family Tour Planner',
      'familyTour': 'Family Tour',
      'planSafeFamilyTour': 'Plan a safe family tour',
      'familyPlannerSubtitle': 'Tell us about your family and budget. uDrive creates an easy itinerary and recommends the right vehicle.',
      'preferredDestination': 'Preferred destination',
      'numberOfDays': 'Number of days',
      'infants': 'Infants',
      'elderlyPersons': 'Elderly persons',
      'familyBudget': 'Family budget',
      'hotelRequired': 'Hotel required',
      'mealsRequired': 'Meals required',
      'childSeatRequired': 'Child seat required',
      'accessibilityRequired': 'Accessibility assistance',
      'generateFamilyPlan': 'Generate family plan',
      'yourFamilyPlanReady': 'Your family plan is ready',
      'safetyScore': 'Safety score',
      'recommendedItinerary': 'Recommended itinerary',
      'recommendedVehicle': 'Recommended vehicle',
      'hotelSuggestion': 'Hotel suggestion',
      'bestDepartureTime': 'Best departure time',
      'roadDifficulty': 'Road difficulty',
      'findFamilyDriver': 'Find a family driver',
      'editPlan': 'Edit plan',
      'familyDriverSearchStarted': 'Family-driver search started',
      'familyDriverSearchMessage': 'Verified family-recommended drivers will now receive this dummy plan.',
      'currentLocationDemo': 'Ghari Pan, Muzaffarabad',
      'offlineReady': 'Offline ready',
      'homeSearchSubtitle': 'Book seats, a full vehicle, or a complete Kashmir tour.',
      'searchDestination': 'Search destination or tour',
      'bookVehicle': 'Book a Vehicle',
      'bookVehicleHint': 'Advance, seat or full vehicle',
      'joinTourHint': 'Join a verified departure',
      'familyTourHint': 'Plan a safe family holiday',
      'exploreHint': 'Places, routes and advisories',
      'tripsHint': 'Bookings and travel cards',
      'emergencySafety': 'Emergency & Safety',
      'safetyHint': 'SOS and trusted contacts',
      'quickServices': 'Quick services',
      'departingSoon': 'Vehicles departing soon',
      'safeTourismPromise': 'Verified tourism travel',
      'safeTourismPromiseText': 'Driver, vehicle and trip checks designed for families and shared travel.',
      'muzaffarabadKeran': 'Muzaffarabad → Keran',
      'roadAlertDemo': 'Light rain expected. Daylight travel and a suitable vehicle are recommended.',
      'caution': 'Caution',
      'customTour': 'Custom tour',
      'seat': 'seat',
      'liveTracking': 'Live trip tracking',
      'tourGuardian': 'Tour Guardian',
      'offlineTravelCard': 'Offline Travel Card',
      'packageBookings': 'Package bookings',
      'vehicleSuitability': 'Vehicle suitability',
      'roadReports': 'Road reports',
      'safetyCheckIns': 'Safety check-ins',
      'routeDeviation': 'Route deviation',
      'shareLocation': 'Share location',
      'tripGuardianMonitoring': 'Guardian monitoring',
      'driverPackageTools': 'Driver tourism tools',
      'googleMapsDemo': 'Google Maps-ready demo is active. Add API keys later to enable the live map without changing the booking flow.',
      'tripInProgress': 'Trip in progress',
      'arrived': 'Arrived',
      'minutesEta': 'min ETA',
      'moveVehicle': 'Move vehicle',
      'pauseDemo': 'Pause demo',
      'routeDeviationSimulation': 'Route deviation simulation',
      'routeDeviationDetected': 'Route deviation detected',
      'routeDeviationCreated': 'A safety incident was created and your Guardian can be alerted.',
      'routeDeviationHelp': 'Enable to test route-deviation detection and escalation.',
      'liveTripControls': 'Live trip controls',
      'callDriver': 'Call driver',
      'messageDriver': 'Message driver',
      'contactSafety': 'Contact uDrive safety',
      'shareLiveLocation': 'Share live location',
      'sharePrivacyHelp': 'Share a privacy-safe tracking link with family or trusted contacts.',
      'oneHour': '1 hour',
      'untilArrival': 'Until arrival',
      'fullTrip': 'Full trip',
      'shareTrackingLink': 'Share tracking link',
      'stopLiveSharing': 'Stop live sharing',
      'emergencyShareHelp': 'Share your location, trip and vehicle details with your Tour Guardian and uDrive safety operations.',
      'activateEmergencySos': 'Activate emergency SOS',
      'sosActivated': 'SOS activated',
      'understand': 'I understand',
      'recentSafetyIncidents': 'Recent safety incidents',
      'trustedPrivacy': 'Trusted contacts receive only the trip and emergency details you choose to share. Their information stays private.',
      'addTrustedContact': 'Add trusted contact',
      'fullName': 'Full name',
      'relationship': 'Relationship',
      'mobileWhatsapp': 'Mobile / WhatsApp',
      'saveTrustedContact': 'Save trusted contact',
      'currentGuardian': 'Current Guardian',
      'setGuardian': 'Set as Guardian',
      'guardianCanView': 'Guardian can securely view',
      'guardianLiveLocation': 'Live trip location and last update time',
      'guardianDriverVehicle': 'Verified driver and vehicle information',
      'guardianRouteEta': 'Planned route, stops and estimated arrival',
      'guardianEmergencyAlerts': 'SOS, missed check-in and route-deviation alerts',
      'guardianCompletion': 'Trip completion confirmation',
      'selectTourGuardian': 'Select Tour Guardian',
      'startGuardianMonitoring': 'Start Guardian monitoring',
      'checkInHelp': 'Long tours use scheduled safety check-ins. An unsafe or missed response can notify your Guardian and uDrive operations.',
      'iAmSafe': 'I am safe',
      'needSupport': 'Need support',
      'unsafe': 'Unsafe',
      'medicalHelp': 'Medical help',
      'savedOffline': 'Saved offline',
      'tripOtp': 'Trip OTP',
      'driverVehicle': 'Driver and vehicle',
      'tripInformation': 'Trip information',
      'emergencyContacts': 'Emergency contacts',
      'refreshOfflineCard': 'Refresh offline card',
      'reportSafetyIssue': 'Report a safety issue',
      'whatHappened': 'What happened?',
      'submitSecureReport': 'Submit secure report',
      'totalBookings': 'Total bookings',
      'city': 'City',
      'familyTours': 'Family tours',
      'mountainRoads': 'Mountain roads',
      'snowRoutes': 'Snow routes',
      'fourByFourRoutes': '4×4 routes',
      'ready': 'ready',
      'seatsBooked': 'Seats booked',
      'requestDetails': 'Request details',
      'confirmBooking': 'Confirm booking',
      'vehicleSuitabilityHelp': 'Vehicle suitability matches route difficulty, passenger capacity and safety equipment with approved vehicles.',
      'mountainReadyMessage': 'This vehicle can be submitted for approved mountain tourism routes.',
      'mountainEquipmentMessage': 'Add 4×4 capability, a first-aid kit and safety equipment for mountain-route eligibility.',
      'reportRoadCondition': 'Report road condition',
      'driverReportNotice': 'Driver reports stay marked as community reports until uDrive operations verifies them.',
      'affectedRoute': 'Affected route',
      'roadConditionType': 'Condition',
      'touristAdvice': 'What should tourists know?',
      'submitReport': 'Submit report',
      'bookings': 'Bookings',
      'packageApprovalNotice': 'Packages remain private until admin approval. Route and vehicle suitability are checked before activation.',
      'preview': 'Preview',
      'pause': 'Pause',
      'activate': 'Activate',
      'approvedVehicle': 'Approved vehicle',
      'routeSuitable': 'Selected vehicle is suitable for this package.',
      'routeNotSuitable': 'This route requires a mountain-ready 4×4 with a first-aid kit and spare tyre.',
      'packageInclusions': 'Package inclusions',
      'detailedItinerary': 'Detailed itinerary',
      'addItineraryDay': 'Add itinerary day',
      'packageSubmitted': 'Package submitted',
      'packageSubmittedHelp': 'The package is private and Pending until an administrator reviews its route, vehicle, price and safety information.',
      'heating': 'Heating',
      'firstAidKit': 'First-aid kit',
      'fireExtinguisher': 'Fire extinguisher',
      'spareTyreTools': 'Spare tyre and tools',
      'snowChains': 'Snow chains',
      'roofCarrier': 'Roof carrier',
      'childSeatAvailable': 'Child seat available',
      'mountainProfile': 'Mountain-ready profile detected. Final route eligibility is assigned after admin inspection.',
      'mountainRequirements': 'Add 4×4 capability, a first-aid kit and spare tyre for mountain-route eligibility.',
      'tourismSafetyKit': 'Tourism safety kit',
      'familyReadiness': 'Family readiness',
    },
    'ur': {
      'appName': 'یو ڈرائیو',
      'tagline': 'آزادی سے گھومیں، اعتماد سے سفر کریں۔',
      'login': 'لاگ اِن',
      'welcomeBack': 'یو ڈرائیو میں خوش آمدید',
      'loginSubtitle': 'سواری بک کریں، کشمیر دریافت کریں اور تصدیق شدہ ڈرائیور کے طور پر کمائیں۔',
      'phone': 'موبائل نمبر',
      'continue': 'جاری رکھیں',
      'demoLogin': 'ڈیمو اکاؤنٹ استعمال کریں',
      'otpTitle': 'نمبر کی تصدیق کریں',
      'otpSubtitle': 'چار ہندسوں کا کوڈ درج کریں۔ ڈیمو کوڈ 1234 ہے۔',
      'verify': 'تصدیق اور جاری',
      'logout': 'لاگ آؤٹ',
      'home': 'ہوم',
      'bookRide': 'سواری بک کریں',
      'explore': 'کشمیر دریافت کریں',
      'packages': 'ٹور پیکجز',
      'trips': 'میرے سفر',
      'wallet': 'والیٹ',
      'savedPlaces': 'محفوظ مقامات',
      'safety': 'سیفٹی سنٹر',
      'notifications': 'اطلاعات',
      'support': 'مدد اور سپورٹ',
      'settings': 'سیٹنگز',
      'profile': 'پروفائل',
      'customerMode': 'کسٹمر موڈ',
      'driverMode': 'ڈرائیور موڈ',
      'switchDriver': 'ڈرائیور موڈ میں جائیں',
      'switchCustomer': 'کسٹمر موڈ میں جائیں',
      'goodMorning': 'صبح بخیر، شہزاد',
      'whereTo': 'آپ کہاں جا رہے ہیں؟',
      'pickup': 'پک اپ مقام',
      'destination': 'منزل',
      'dateTime': 'تاریخ اور وقت',
      'passengers': 'مسافر',
      'luggage': 'سامان',
      'vehicle': 'گاڑی',
      'suggestedFare': 'تجویز کردہ کرایہ',
      'yourOffer': 'آپ کی پیشکش',
      'requestRide': 'ڈرائیورز کو درخواست بھیجیں',
      'driverOffers': 'ڈرائیور آفرز',
      'selectDriver': 'ڈرائیور منتخب کریں',
      'localRide': 'مقامی سواری',
      'intercity': 'بین الاضلاعی',
      'fullDay': 'پورے دن کی گاڑی',
      'jeep': 'فور بائی فور جیپ',
      'sharedRide': 'مشترکہ سواری',
      'airport': 'ایئرپورٹ ٹرانسفر',
      'activeTrip': 'فعال سفر',
      'viewTrip': 'سفر دیکھیں',
      'roadAlert': 'سڑک کی اطلاع',
      'popularPlaces': 'مقبول مقامات',
      'recommendedPackages': 'تجویز کردہ پیکجز',
      'viewAll': 'سب دیکھیں',
      'bookNow': 'ابھی بک کریں',
      'sendOffer': 'قیمت کی آفر بھیجیں',
      'included': 'شامل',
      'itinerary': 'سفر کا منصوبہ',
      'upcoming': 'آنے والے',
      'completed': 'مکمل',
      'cancelled': 'منسوخ',
      'addMoney': 'رقم شامل کریں',
      'sendMoney': 'رقم بھیجیں',
      'transactions': 'لین دین',
      'emergency': 'ایمرجنسی ایس او ایس',
      'shareTrip': 'لائیو سفر شیئر کریں',
      'trustedContacts': 'قابل اعتماد رابطے',
      'reportIssue': 'سیفٹی مسئلہ رپورٹ کریں',
      'online': 'آن لائن',
      'offline': 'آف لائن',
      'driverDashboard': 'ڈرائیور ڈیش بورڈ',
      'rideRequests': 'سواری کی درخواستیں',
      'myPackages': 'میرے پیکجز',
      'createPackage': 'پیکج بنائیں',
      'earnings': 'آمدن',
      'payouts': 'والیٹ اور ادائیگیاں',
      'vehicles': 'گاڑی کی رجسٹریشن',
      'documents': 'دستاویزات اور تصدیق',
      'availability': 'دستیابی',
      'reviews': 'ریٹنگز اور جائزے',
      'accept': 'قبول کریں',
      'counterOffer': 'جوابی آفر',
      'decline': 'مسترد کریں',
      'todayEarnings': 'آج کی آمدن',
      'weeklyEarnings': 'ہفتہ وار آمدن',
      'availableBalance': 'دستیاب بیلنس',
      'withdraw': 'ادائیگی کی درخواست',
      'registerVehicle': 'گاڑی رجسٹر کریں',
      'addVehicle': 'گاڑی شامل کریں',
      'editVehicle': 'گاڑی میں تبدیلی',
      'vehicleDetails': 'گاڑی کی تفصیل',
      'capabilities': 'گنجائش اور خصوصیات',
      'uploadDocuments': 'دستاویزات اور تصاویر',
      'reviewSubmit': 'جائزہ اور جمع',
      'make': 'کمپنی',
      'model': 'ماڈل',
      'year': 'سال',
      'color': 'رنگ',
      'registrationNo': 'رجسٹریشن نمبر',
      'category': 'گاڑی کی قسم',
      'seats': 'مسافر نشستیں',
      'luggageCapacity': 'سامان کی گنجائش',
      'airConditioning': 'ایئر کنڈیشننگ',
      'fourWheelDrive': 'فور بائی فور صلاحیت',
      'vehiclePhotos': 'گاڑی کی تصاویر',
      'registrationDoc': 'رجسٹریشن دستاویز',
      'insuranceDoc': 'انشورنس دستاویز',
      'fitnessDoc': 'فٹنس سرٹیفکیٹ',
      'upload': 'اپ لوڈ',
      'uploaded': 'اپ لوڈ ہوگیا',
      'submitVerification': 'تصدیق کے لیے جمع کریں',
      'saveDraft': 'ڈرافٹ محفوظ کریں',
      'packageTitle': 'پیکج کا عنوان',
      'startLocation': 'ابتدائی مقام',
      'duration': 'مدت',
      'maxGuests': 'زیادہ سے زیادہ مہمان',
      'packagePrice': 'پیکج کی قیمت',
      'allowOffers': 'کسٹمر آفرز کی اجازت',
      'description': 'تفصیل',
      'inclusions': 'شامل سہولیات',
      'exclusions': 'غیر شامل سہولیات',
      'submitApproval': 'منظوری کے لیے جمع کریں',
      'dummyReady': 'ڈیمو ڈیٹا فعال ہے',
      'search': 'تلاش',
      'close': 'بند کریں',
      'save': 'محفوظ کریں',
      'next': 'اگلا',
      'back': 'واپس',
      'done': 'مکمل',
      'language': 'زبان',
      'english': 'انگریزی',
      'urdu': 'اردو',
      'appearance': 'ظاہری شکل',
      'privacy': 'رازداری',
      'terms': 'شرائط و ضوابط',
      'about': 'یو ڈرائیو کے بارے میں',
      'noData': 'کوئی ڈیٹا موجود نہیں',
      'required': 'یہ خانہ لازمی ہے',
      'invalidPhone': 'درست موبائل نمبر درج کریں',
      'invalidOtp': 'ڈیمو کوڈ 1234 استعمال کریں',
      'success': 'کامیابی سے مکمل ہوگیا',
      'verified': 'تصدیق شدہ',
      'pending': 'جائزہ زیر التوا',
      'active': 'فعال',
      'draft': 'ڈرافٹ',
      'advanceBooking': 'ایڈوانس بکنگ',
      'bookingStepOneHelp': 'اپنا راستہ اور پسندیدہ سفر کا وقت منتخب کریں۔',
      'departureDate': 'روانگی کی تاریخ',
      'departureTime': 'روانگی کا وقت',
      'returnTrip': 'واپسی کا سفر شامل کریں',
      'returnTripHelp': 'دونوں طرف کا سفر ایک درخواست میں محفوظ کریں۔',
      'returnDate': 'واپسی کی تاریخ',
      'travelDetails': 'آپ کس طرح سفر کر رہے ہیں؟',
      'bookingStepTwoHelp': 'نشستیں منتخب کریں یا پوری گاڑی محفوظ کریں۔',
      'bookPerSeat': 'فی نشست بک کریں',
      'perSeat': 'فی نشست',
      'perSeatHelp': 'صرف اپنی ضرورت کی نشستوں کی ادائیگی کریں۔',
      'bookWholeVehicle': 'پوری گاڑی بک کریں',
      'wholeVehicle': 'پوری گاڑی',
      'wholeVehicleHelp': 'اپنے گروپ کے لیے پوری گاڑی نجی رکھیں۔',
      'adults': 'بالغ',
      'children': 'بچے',
      'travellerPreference': 'مسافر کی ترجیح',
      'family': 'فیملی',
      'individual': 'انفرادی',
      'womenOnly': 'صرف خواتین',
      'group': 'گروپ',
      'familyOnly': 'صرف فیملی',
      'familyOnlyPreference': 'صرف فیملی والا مشترکہ سفر ترجیح دیں',
      'femalePassengerPreference': 'خواتین یا فیملی مسافر گروپ ترجیح دیں',
      'selectVehicle': 'درست گاڑی منتخب کریں',
      'bookingStepThreeHelp': 'ہم راستے اور گروپ کے سائز کے مطابق گاڑی تجویز کرتے ہیں۔',
      'recommended': 'تجویز کردہ',
      'specialInstructions': 'خصوصی ہدایات',
      'specialInstructionsHint': 'چائلڈ سیٹ، بزرگوں کی مدد، ہوٹل پک اپ وغیرہ',
      'reviewBooking': 'اپنی بکنگ کا جائزہ لیں',
      'bookingStepFourHelp': 'تصدیق سے پہلے واضح قیمت اور تصدیق شدہ ڈرائیور۔',
      'bookingOption': 'بکنگ آپشن',
      'transparentPrice': 'واضح قیمت کا تخمینہ',
      'seatFare': 'نشست کا کرایہ',
      'vehicleFare': 'گاڑی کا کرایہ',
      'estimatedTotal': 'تخمینی کل',
      'noHiddenCharges': 'کوئی پوشیدہ چارج نہیں۔ حتمی ڈرائیور آفر تصدیق سے پہلے دکھائی جائے گی۔',
      'secureBookingMessage': 'صرف تصدیق شدہ ڈرائیور اور منظور شدہ گاڑیاں اس ٹورزم بکنگ کا جواب دے سکتی ہیں۔',
      'findVerifiedDrivers': 'تصدیق شدہ ڈرائیور تلاش کریں',
      'joinTour': 'ٹور میں شامل ہوں',
      'availableTours': 'دستیاب ٹور',
      'registerInterest': 'دلچسپی رجسٹر کریں',
      'joinTourHeadline': 'محفوظ طریقے سے ساتھ سفر کریں',
      'joinTourSubtitle': 'تصدیق شدہ روانگی میں شامل ہوں، فی نشست اور پوری گاڑی کے کرایوں کا موازنہ کریں۔',
      'all': 'سب',
      'noMatchingTours': 'کوئی مناسب ٹور نہیں ملا',
      'match': 'میچ',
      'seatsLeft': 'نشستیں باقی',
      'securePassengerSummary': 'محفوظ مسافر خلاصہ',
      'male': 'مرد',
      'female': 'خواتین',
      'verifiedTripProtection': 'تصدیق شدہ سفر کی حفاظت',
      'otpTripStart': 'سفر کسٹمر او ٹی پی تصدیق سے شروع ہوگا',
      'liveLocationSharing': 'قابل اعتماد رابطوں کے ساتھ لائیو سفر شیئرنگ',
      'privatePassengerData': 'مسافروں کے نام اور فون نمبر نجی رہیں گے',
      'supportMonitoring': 'رپورٹ شدہ واقعہ کو یو ڈرائیو سیفٹی سپورٹ مانیٹر کر سکتی ہے',
      'tourSeatReserved': 'ٹور ریزرویشن محفوظ ہوگئی',
      'perSeatReservationSuccess': 'اس ڈمی ٹور میں آپ کی نشستیں محفوظ ہوگئیں۔ لائیو ادائیگی بعد میں منسلک ہوگی۔',
      'wholeVehicleReservationSuccess': 'اس ڈمی ٹور میں پوری گاڑی محفوظ ہوگئی۔ لائیو ادائیگی بعد میں منسلک ہوگی۔',
      'pickupCity': 'پک اپ شہر یا مقام',
      'dateFrom': 'تاریخ سے',
      'dateTo': 'تاریخ تک',
      'tourType': 'ٹور گروپ کی قسم',
      'vehiclePreference': 'گاڑی کی ترجیح',
      'budgetPerSeat': 'فی نشست بجٹ',
      'notifyMatchingTour': 'رجسٹر کریں اور اطلاع دیں',
      'interestPrivacyMessage': 'آپ کی رابطہ معلومات عوامی نہیں ہوں گی۔ صرف مناسب ٹور کی اطلاع ملے گی۔',
      'cannotFindTour': 'اپنا ٹور نہیں مل رہا؟',
      'registerAndNotify': 'منزل اور تاریخ رجسٹر کریں۔ ڈرائیور کے مناسب پیکج بنانے پر ہم اطلاع دیں گے۔',
      'numberOfPersons': 'افراد کی تعداد',
      'tourInterestRegistered': 'ٹور دلچسپی رجسٹر ہوگئی',
      'tourInterestSuccessMessage': 'نمونہ مناسب روانگیاں مل گئی ہیں اور مناسب گاڑی دستیاب ہونے پر اطلاع ملے گی۔',
      'familyTourPlanner': 'فیملی ٹور پلانر',
      'familyTour': 'فیملی ٹور',
      'planSafeFamilyTour': 'محفوظ فیملی ٹور پلان کریں',
      'familyPlannerSubtitle': 'اپنی فیملی اور بجٹ کی معلومات دیں۔ یو ڈرائیو آسان پلان اور درست گاڑی تجویز کرے گا۔',
      'preferredDestination': 'پسندیدہ منزل',
      'numberOfDays': 'دنوں کی تعداد',
      'infants': 'شیر خوار بچے',
      'elderlyPersons': 'بزرگ افراد',
      'familyBudget': 'فیملی بجٹ',
      'hotelRequired': 'ہوٹل درکار ہے',
      'mealsRequired': 'کھانا درکار ہے',
      'childSeatRequired': 'چائلڈ سیٹ درکار ہے',
      'accessibilityRequired': 'رسائی میں مدد',
      'generateFamilyPlan': 'فیملی پلان بنائیں',
      'yourFamilyPlanReady': 'آپ کا فیملی پلان تیار ہے',
      'safetyScore': 'سیفٹی اسکور',
      'recommendedItinerary': 'تجویز کردہ سفر کا منصوبہ',
      'recommendedVehicle': 'تجویز کردہ گاڑی',
      'hotelSuggestion': 'ہوٹل کی تجویز',
      'bestDepartureTime': 'بہترین روانگی کا وقت',
      'roadDifficulty': 'سڑک کی مشکل',
      'findFamilyDriver': 'فیملی ڈرائیور تلاش کریں',
      'editPlan': 'پلان میں تبدیلی کریں',
      'familyDriverSearchStarted': 'فیملی ڈرائیور کی تلاش شروع ہوگئی',
      'familyDriverSearchMessage': 'تصدیق شدہ فیملی ڈرائیورز کو یہ ڈمی پلان بھیج دیا گیا ہے۔',
      'currentLocationDemo': 'گھڑی پن، مظفرآباد',
      'offlineReady': 'آف لائن تیار',
      'homeSearchSubtitle': 'نشست، پوری گاڑی یا مکمل کشمیر ٹور بک کریں۔',
      'searchDestination': 'منزل یا ٹور تلاش کریں',
      'bookVehicle': 'گاڑی بک کریں',
      'bookVehicleHint': 'ایڈوانس، نشست یا پوری گاڑی',
      'joinTourHint': 'تصدیق شدہ روانگی میں شامل ہوں',
      'familyTourHint': 'محفوظ فیملی چھٹی پلان کریں',
      'exploreHint': 'مقامات، راستے اور اطلاعات',
      'tripsHint': 'بکنگ اور ٹریول کارڈ',
      'emergencySafety': 'ایمرجنسی اور سیفٹی',
      'safetyHint': 'ایس او ایس اور قابل اعتماد رابطے',
      'quickServices': 'فوری سہولیات',
      'departingSoon': 'جلد روانہ ہونے والی گاڑیاں',
      'safeTourismPromise': 'تصدیق شدہ سیاحتی سفر',
      'safeTourismPromiseText': 'فیملی اور مشترکہ سفر کے لیے ڈرائیور، گاڑی اور سفر کی جانچ۔',
      'muzaffarabadKeran': 'مظفرآباد ← کیرن',
      'roadAlertDemo': 'ہلکی بارش متوقع ہے۔ دن کے وقت اور مناسب گاڑی کے ساتھ سفر کی تجویز ہے۔',
      'caution': 'احتیاط',
      'customTour': 'کسٹم ٹور',
      'seat': 'نشست',
      'liveTracking': 'لائیو سفر ٹریکنگ',
      'tourGuardian': 'ٹور گارڈین',
      'offlineTravelCard': 'آف لائن ٹریول کارڈ',
      'packageBookings': 'پیکج بکنگز',
      'vehicleSuitability': 'گاڑی کی موزونیت',
      'roadReports': 'سڑک کی رپورٹس',
      'safetyCheckIns': 'سیفٹی چیک اِن',
      'routeDeviation': 'راستے سے انحراف',
      'shareLocation': 'لوکیشن شیئر کریں',
      'tripGuardianMonitoring': 'گارڈین نگرانی',
      'driverPackageTools': 'ڈرائیور ٹورزم ٹولز',
      'googleMapsDemo': 'گوگل میپس کے لیے تیار ڈیمو فعال ہے۔ لائیو نقشہ چلانے کے لیے بعد میں اے پی آئی کی شامل کریں۔',
      'tripInProgress': 'سفر جاری ہے',
      'arrived': 'پہنچ گئے',
      'minutesEta': 'منٹ باقی',
      'moveVehicle': 'گاڑی آگے بڑھائیں',
      'pauseDemo': 'ڈیمو روکیں',
      'routeDeviationSimulation': 'راستہ بدلنے کا ڈیمو',
      'routeDeviationDetected': 'راستے سے انحراف پایا گیا',
      'routeDeviationCreated': 'سیفٹی واقعہ بن گیا ہے اور گارڈین کو اطلاع دی جا سکتی ہے۔',
      'routeDeviationHelp': 'راستہ بدلنے کی شناخت اور اطلاع کا ڈیمو چلائیں۔',
      'liveTripControls': 'لائیو سفر کنٹرولز',
      'callDriver': 'ڈرائیور کو کال کریں',
      'messageDriver': 'ڈرائیور کو پیغام دیں',
      'contactSafety': 'یو ڈرائیو سیفٹی سے رابطہ',
      'shareLiveLocation': 'لائیو لوکیشن شیئر کریں',
      'sharePrivacyHelp': 'فیملی یا قابل اعتماد رابطوں کے ساتھ محفوظ ٹریکنگ لنک شیئر کریں۔',
      'oneHour': 'ایک گھنٹہ',
      'untilArrival': 'منزل تک',
      'fullTrip': 'پورا سفر',
      'shareTrackingLink': 'ٹریکنگ لنک شیئر کریں',
      'stopLiveSharing': 'لائیو شیئرنگ بند کریں',
      'emergencyShareHelp': 'اپنی لوکیشن، سفر اور گاڑی کی معلومات ٹور گارڈین اور یو ڈرائیو سیفٹی کے ساتھ شیئر کریں۔',
      'activateEmergencySos': 'ایمرجنسی ایس او ایس فعال کریں',
      'sosActivated': 'ایس او ایس فعال ہوگیا',
      'understand': 'سمجھ گیا',
      'recentSafetyIncidents': 'حالیہ سیفٹی واقعات',
      'trustedPrivacy': 'قابل اعتماد رابطوں کو صرف آپ کی منتخب کردہ سفر اور ایمرجنسی معلومات ملتی ہیں۔ ان کی معلومات نجی رہتی ہیں۔',
      'addTrustedContact': 'قابل اعتماد رابطہ شامل کریں',
      'fullName': 'پورا نام',
      'relationship': 'رشتہ',
      'mobileWhatsapp': 'موبائل / واٹس ایپ',
      'saveTrustedContact': 'رابطہ محفوظ کریں',
      'currentGuardian': 'موجودہ گارڈین',
      'setGuardian': 'گارڈین بنائیں',
      'guardianCanView': 'گارڈین محفوظ طریقے سے دیکھ سکتا ہے',
      'guardianLiveLocation': 'لائیو سفر کی لوکیشن اور آخری اپ ڈیٹ',
      'guardianDriverVehicle': 'تصدیق شدہ ڈرائیور اور گاڑی کی معلومات',
      'guardianRouteEta': 'منصوبہ شدہ راستہ، اسٹاپس اور پہنچنے کا وقت',
      'guardianEmergencyAlerts': 'ایس او ایس، مس شدہ چیک اِن اور راستہ بدلنے کی اطلاعات',
      'guardianCompletion': 'سفر مکمل ہونے کی تصدیق',
      'selectTourGuardian': 'ٹور گارڈین منتخب کریں',
      'startGuardianMonitoring': 'گارڈین نگرانی شروع کریں',
      'checkInHelp': 'طویل سفر میں سیفٹی چیک اِن ہوتے ہیں۔ غیر محفوظ یا مس شدہ جواب پر گارڈین اور آپریشنز کو اطلاع دی جا سکتی ہے۔',
      'iAmSafe': 'میں محفوظ ہوں',
      'needSupport': 'مدد درکار ہے',
      'unsafe': 'غیر محفوظ',
      'medicalHelp': 'طبی مدد',
      'savedOffline': 'آف لائن محفوظ',
      'tripOtp': 'سفر او ٹی پی',
      'driverVehicle': 'ڈرائیور اور گاڑی',
      'tripInformation': 'سفر کی معلومات',
      'emergencyContacts': 'ایمرجنسی رابطے',
      'refreshOfflineCard': 'آف لائن کارڈ تازہ کریں',
      'reportSafetyIssue': 'سیفٹی مسئلہ رپورٹ کریں',
      'whatHappened': 'کیا ہوا؟',
      'submitSecureReport': 'محفوظ رپورٹ جمع کریں',
      'totalBookings': 'کل بکنگز',
      'city': 'شہری سفر',
      'familyTours': 'فیملی ٹورز',
      'mountainRoads': 'پہاڑی راستے',
      'snowRoutes': 'برفانی راستے',
      'fourByFourRoutes': 'فور بائی فور راستے',
      'ready': 'تیار',
      'seatsBooked': 'بک شدہ نشستیں',
      'requestDetails': 'مزید تفصیل مانگیں',
      'confirmBooking': 'بکنگ کی تصدیق',
      'vehicleSuitabilityHelp': 'گاڑی کی موزونیت راستے، مسافروں اور حفاظتی سامان کے مطابق منظور شدہ گاڑی منتخب کرتی ہے۔',
      'mountainReadyMessage': 'یہ گاڑی منظور شدہ پہاڑی ٹورزم راستوں کے لیے جمع کی جا سکتی ہے۔',
      'mountainEquipmentMessage': 'پہاڑی راستوں کے لیے فور بائی فور، فرسٹ ایڈ کٹ اور حفاظتی سامان شامل کریں۔',
      'reportRoadCondition': 'سڑک کی حالت رپورٹ کریں',
      'driverReportNotice': 'ڈرائیور رپورٹ آپریشنز کی تصدیق تک کمیونٹی رپورٹ رہے گی۔',
      'affectedRoute': 'متاثرہ راستہ',
      'roadConditionType': 'حالت',
      'touristAdvice': 'سیاحوں کو کیا معلوم ہونا چاہیے؟',
      'submitReport': 'رپورٹ جمع کریں',
      'bookings': 'بکنگز',
      'packageApprovalNotice': 'پیکج ایڈمن منظوری تک نجی رہتا ہے۔ فعال کرنے سے پہلے راستہ اور گاڑی چیک کی جاتی ہے۔',
      'preview': 'پری ویو',
      'pause': 'روکیں',
      'activate': 'فعال کریں',
      'approvedVehicle': 'منظور شدہ گاڑی',
      'routeSuitable': 'منتخب گاڑی اس پیکج کے لیے موزوں ہے۔',
      'routeNotSuitable': 'اس راستے کے لیے پہاڑی فور بائی فور، فرسٹ ایڈ کٹ اور اسپیئر ٹائر درکار ہیں۔',
      'packageInclusions': 'پیکج میں شامل سہولیات',
      'detailedItinerary': 'تفصیلی سفر کا منصوبہ',
      'addItineraryDay': 'سفر کا دن شامل کریں',
      'packageSubmitted': 'پیکج جمع ہوگیا',
      'packageSubmittedHelp': 'ایڈمن کی جانب سے راستہ، گاڑی، قیمت اور سیفٹی کے جائزے تک پیکج نجی اور زیر التوا رہے گا۔',
      'heating': 'ہیٹنگ',
      'firstAidKit': 'فرسٹ ایڈ کٹ',
      'fireExtinguisher': 'آگ بجھانے والا آلہ',
      'spareTyreTools': 'اسپیئر ٹائر اور اوزار',
      'snowChains': 'سنو چینز',
      'roofCarrier': 'روف کیریئر',
      'childSeatAvailable': 'چائلڈ سیٹ دستیاب',
      'mountainProfile': 'پہاڑی راستے کے لیے پروفائل تیار ہے۔ حتمی منظوری ایڈمن معائنے کے بعد ہوگی۔',
      'mountainRequirements': 'پہاڑی راستوں کے لیے فور بائی فور، فرسٹ ایڈ کٹ اور اسپیئر ٹائر شامل کریں۔',
      'tourismSafetyKit': 'ٹورزم سیفٹی کٹ',
      'familyReadiness': 'فیملی کے لیے تیاری',
    },
  };

  static String get(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    return _text[code]?[key] ?? _text['en']?[key] ?? key;
  }
}

extension AppStringX on BuildContext {
  String tr(String key) => AppStrings.get(this, key);
}
