import 'package:flutter/material.dart';

class AppStrings {
  static const supportedLocales = [Locale('en'), Locale('ur')];

  static const Map<String, Map<String, String>> _text = {
    'en': {
      'appName': 'uDrive',
      'tagline': 'Explore freely. Ride confidently.',
      'login': 'Login',
      'welcomeBack': 'Welcome to uDrive',
      'loginSubtitle': 'Book rides, discover Kashmir and earn as a verified driver.',
      'phone': 'Mobile number',
      'continue': 'Continue',
      'demoLogin': 'Use demo account',
      'otpTitle': 'Verify your number',
      'otpSubtitle': 'Enter the 4-digit code. Demo code is 1234.',
      'verify': 'Verify & continue',
      'logout': 'Logout',
      'home': 'Home',
      'bookRide': 'Book a ride',
      'explore': 'Explore Kashmir',
      'packages': 'Tour packages',
      'trips': 'My trips',
      'wallet': 'Wallet',
      'savedPlaces': 'Saved places',
      'safety': 'Safety centre',
      'notifications': 'Notifications',
      'support': 'Help & support',
      'settings': 'Settings',
      'profile': 'Profile',
      'customerMode': 'Customer mode',
      'driverMode': 'Driver mode',
      'switchDriver': 'Switch to Driver mode',
      'switchCustomer': 'Switch to Customer mode',
      'goodMorning': 'Good morning, Shahzad',
      'whereTo': 'Where are you going?',
      'pickup': 'Pickup location',
      'destination': 'Destination',
      'dateTime': 'Date & time',
      'passengers': 'Passengers',
      'luggage': 'Luggage',
      'vehicle': 'Vehicle',
      'suggestedFare': 'Suggested fare',
      'yourOffer': 'Your offer',
      'requestRide': 'Request drivers',
      'driverOffers': 'Driver offers',
      'selectDriver': 'Select driver',
      'localRide': 'Local ride',
      'intercity': 'Intercity',
      'fullDay': 'Full-day hire',
      'jeep': '4×4 Jeep',
      'sharedRide': 'Shared ride',
      'airport': 'Airport transfer',
      'activeTrip': 'Active trip',
      'viewTrip': 'View trip',
      'roadAlert': 'Road advisory',
      'popularPlaces': 'Popular places',
      'recommendedPackages': 'Recommended packages',
      'viewAll': 'View all',
      'bookNow': 'Book now',
      'sendOffer': 'Send price offer',
      'included': 'Included',
      'itinerary': 'Itinerary',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'addMoney': 'Add money',
      'sendMoney': 'Send money',
      'transactions': 'Transactions',
      'emergency': 'Emergency SOS',
      'shareTrip': 'Share live trip',
      'trustedContacts': 'Trusted contacts',
      'reportIssue': 'Report a safety issue',
      'online': 'Online',
      'offline': 'Offline',
      'driverDashboard': 'Driver dashboard',
      'rideRequests': 'Ride requests',
      'myPackages': 'My packages',
      'createPackage': 'Create package',
      'earnings': 'Earnings',
      'payouts': 'Wallet & payouts',
      'vehicles': 'Vehicle registration',
      'documents': 'Documents & verification',
      'availability': 'Availability',
      'reviews': 'Ratings & reviews',
      'accept': 'Accept',
      'counterOffer': 'Counteroffer',
      'decline': 'Decline',
      'todayEarnings': "Today's earnings",
      'weeklyEarnings': 'Weekly earnings',
      'availableBalance': 'Available balance',
      'withdraw': 'Request payout',
      'registerVehicle': 'Register a vehicle',
      'addVehicle': 'Add vehicle',
      'editVehicle': 'Edit vehicle',
      'vehicleDetails': 'Vehicle details',
      'capabilities': 'Capacity & capabilities',
      'uploadDocuments': 'Documents & photos',
      'reviewSubmit': 'Review & submit',
      'make': 'Make',
      'model': 'Model',
      'year': 'Year',
      'color': 'Color',
      'registrationNo': 'Registration number',
      'category': 'Vehicle category',
      'seats': 'Passenger seats',
      'luggageCapacity': 'Luggage capacity',
      'airConditioning': 'Air conditioning',
      'fourWheelDrive': '4×4 capability',
      'vehiclePhotos': 'Vehicle photos',
      'registrationDoc': 'Registration document',
      'insuranceDoc': 'Insurance document',
      'fitnessDoc': 'Fitness certificate',
      'upload': 'Upload',
      'uploaded': 'Uploaded',
      'submitVerification': 'Submit for verification',
      'saveDraft': 'Save draft',
      'packageTitle': 'Package title',
      'startLocation': 'Starting location',
      'duration': 'Duration',
      'maxGuests': 'Maximum guests',
      'packagePrice': 'Package price',
      'allowOffers': 'Allow customer offers',
      'description': 'Description',
      'inclusions': 'Inclusions',
      'exclusions': 'Exclusions',
      'submitApproval': 'Submit for approval',
      'dummyReady': 'Demo data is active',
      'search': 'Search',
      'close': 'Close',
      'save': 'Save',
      'next': 'Next',
      'back': 'Back',
      'done': 'Done',
      'language': 'Language',
      'english': 'English',
      'urdu': 'Urdu',
      'appearance': 'Appearance',
      'privacy': 'Privacy',
      'terms': 'Terms & conditions',
      'about': 'About uDrive',
      'noData': 'No data available',
      'required': 'This field is required',
      'invalidPhone': 'Enter a valid mobile number',
      'invalidOtp': 'Use demo code 1234',
      'success': 'Completed successfully',
      'verified': 'Verified',
      'pending': 'Pending review',
      'active': 'Active',
      'draft': 'Draft',
    },
    'ur': {
      'appName': 'یو ڈرائیو',
      'tagline': 'آزادی سے گھومیں، اعتماد سے سفر کریں۔',
      'login': 'لاگ اِن',
      'welcomeBack': 'یو ڈرائیو میں خوش آمدید',
      'loginSubtitle': 'سواری بک کریں، کشمیر دریافت کریں اور تصدیق شدہ ڈرائیور کے طور پر کمائیں۔',
      'phone': 'موبائل نمبر',
      'continue': 'جاری رکھیں',
      'demoLogin': 'ڈیمو اکاؤنٹ استعمال کریں',
      'otpTitle': 'نمبر کی تصدیق کریں',
      'otpSubtitle': 'چار ہندسوں کا کوڈ درج کریں۔ ڈیمو کوڈ 1234 ہے۔',
      'verify': 'تصدیق اور جاری',
      'logout': 'لاگ آؤٹ',
      'home': 'ہوم',
      'bookRide': 'سواری بک کریں',
      'explore': 'کشمیر دریافت کریں',
      'packages': 'ٹور پیکجز',
      'trips': 'میرے سفر',
      'wallet': 'والیٹ',
      'savedPlaces': 'محفوظ مقامات',
      'safety': 'سیفٹی سنٹر',
      'notifications': 'اطلاعات',
      'support': 'مدد اور سپورٹ',
      'settings': 'سیٹنگز',
      'profile': 'پروفائل',
      'customerMode': 'کسٹمر موڈ',
      'driverMode': 'ڈرائیور موڈ',
      'switchDriver': 'ڈرائیور موڈ میں جائیں',
      'switchCustomer': 'کسٹمر موڈ میں جائیں',
      'goodMorning': 'صبح بخیر، شہزاد',
      'whereTo': 'آپ کہاں جا رہے ہیں؟',
      'pickup': 'پک اپ مقام',
      'destination': 'منزل',
      'dateTime': 'تاریخ اور وقت',
      'passengers': 'مسافر',
      'luggage': 'سامان',
      'vehicle': 'گاڑی',
      'suggestedFare': 'تجویز کردہ کرایہ',
      'yourOffer': 'آپ کی پیشکش',
      'requestRide': 'ڈرائیورز کو درخواست بھیجیں',
      'driverOffers': 'ڈرائیور آفرز',
      'selectDriver': 'ڈرائیور منتخب کریں',
      'localRide': 'مقامی سواری',
      'intercity': 'بین الاضلاعی',
      'fullDay': 'پورے دن کی گاڑی',
      'jeep': 'فور بائی فور جیپ',
      'sharedRide': 'مشترکہ سواری',
      'airport': 'ایئرپورٹ ٹرانسفر',
      'activeTrip': 'فعال سفر',
      'viewTrip': 'سفر دیکھیں',
      'roadAlert': 'سڑک کی اطلاع',
      'popularPlaces': 'مقبول مقامات',
      'recommendedPackages': 'تجویز کردہ پیکجز',
      'viewAll': 'سب دیکھیں',
      'bookNow': 'ابھی بک کریں',
      'sendOffer': 'قیمت کی آفر بھیجیں',
      'included': 'شامل',
      'itinerary': 'سفر کا منصوبہ',
      'upcoming': 'آنے والے',
      'completed': 'مکمل',
      'cancelled': 'منسوخ',
      'addMoney': 'رقم شامل کریں',
      'sendMoney': 'رقم بھیجیں',
      'transactions': 'لین دین',
      'emergency': 'ایمرجنسی ایس او ایس',
      'shareTrip': 'لائیو سفر شیئر کریں',
      'trustedContacts': 'قابل اعتماد رابطے',
      'reportIssue': 'سیفٹی مسئلہ رپورٹ کریں',
      'online': 'آن لائن',
      'offline': 'آف لائن',
      'driverDashboard': 'ڈرائیور ڈیش بورڈ',
      'rideRequests': 'سواری کی درخواستیں',
      'myPackages': 'میرے پیکجز',
      'createPackage': 'پیکج بنائیں',
      'earnings': 'آمدن',
      'payouts': 'والیٹ اور ادائیگیاں',
      'vehicles': 'گاڑی کی رجسٹریشن',
      'documents': 'دستاویزات اور تصدیق',
      'availability': 'دستیابی',
      'reviews': 'ریٹنگز اور جائزے',
      'accept': 'قبول کریں',
      'counterOffer': 'جوابی آفر',
      'decline': 'مسترد کریں',
      'todayEarnings': 'آج کی آمدن',
      'weeklyEarnings': 'ہفتہ وار آمدن',
      'availableBalance': 'دستیاب بیلنس',
      'withdraw': 'ادائیگی کی درخواست',
      'registerVehicle': 'گاڑی رجسٹر کریں',
      'addVehicle': 'گاڑی شامل کریں',
      'editVehicle': 'گاڑی میں تبدیلی',
      'vehicleDetails': 'گاڑی کی تفصیل',
      'capabilities': 'گنجائش اور خصوصیات',
      'uploadDocuments': 'دستاویزات اور تصاویر',
      'reviewSubmit': 'جائزہ اور جمع',
      'make': 'کمپنی',
      'model': 'ماڈل',
      'year': 'سال',
      'color': 'رنگ',
      'registrationNo': 'رجسٹریشن نمبر',
      'category': 'گاڑی کی قسم',
      'seats': 'مسافر نشستیں',
      'luggageCapacity': 'سامان کی گنجائش',
      'airConditioning': 'ایئر کنڈیشننگ',
      'fourWheelDrive': 'فور بائی فور صلاحیت',
      'vehiclePhotos': 'گاڑی کی تصاویر',
      'registrationDoc': 'رجسٹریشن دستاویز',
      'insuranceDoc': 'انشورنس دستاویز',
      'fitnessDoc': 'فٹنس سرٹیفکیٹ',
      'upload': 'اپ لوڈ',
      'uploaded': 'اپ لوڈ ہوگیا',
      'submitVerification': 'تصدیق کے لیے جمع کریں',
      'saveDraft': 'ڈرافٹ محفوظ کریں',
      'packageTitle': 'پیکج کا عنوان',
      'startLocation': 'ابتدائی مقام',
      'duration': 'مدت',
      'maxGuests': 'زیادہ سے زیادہ مہمان',
      'packagePrice': 'پیکج کی قیمت',
      'allowOffers': 'کسٹمر آفرز کی اجازت',
      'description': 'تفصیل',
      'inclusions': 'شامل سہولیات',
      'exclusions': 'غیر شامل سہولیات',
      'submitApproval': 'منظوری کے لیے جمع کریں',
      'dummyReady': 'ڈیمو ڈیٹا فعال ہے',
      'search': 'تلاش',
      'close': 'بند کریں',
      'save': 'محفوظ کریں',
      'next': 'اگلا',
      'back': 'واپس',
      'done': 'مکمل',
      'language': 'زبان',
      'english': 'انگریزی',
      'urdu': 'اردو',
      'appearance': 'ظاہری شکل',
      'privacy': 'رازداری',
      'terms': 'شرائط و ضوابط',
      'about': 'یو ڈرائیو کے بارے میں',
      'noData': 'کوئی ڈیٹا موجود نہیں',
      'required': 'یہ خانہ لازمی ہے',
      'invalidPhone': 'درست موبائل نمبر درج کریں',
      'invalidOtp': 'ڈیمو کوڈ 1234 استعمال کریں',
      'success': 'کامیابی سے مکمل ہوگیا',
      'verified': 'تصدیق شدہ',
      'pending': 'جائزہ زیر التوا',
      'active': 'فعال',
      'draft': 'ڈرافٹ',
    },
  };

  static String get(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    return _text[code]?[key] ?? _text['en']?[key] ?? key;
  }
}

extension AppStringX on BuildContext {
  String tr(String key) => AppStrings.get(this, key);
}
