import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import '../../core/auth/session_store.dart';
import '../../core/network/api_client.dart';
import '../../core/safety/safety_repository.dart';
import '../../core/theme/app_theme.dart';

class SafetyHubScreen extends StatefulWidget { const SafetyHubScreen({super.key}); @override State<SafetyHubScreen> createState()=>_SafetyHubScreenState(); }
class _SafetyHubScreenState extends State<SafetyHubScreen>{
 late final SafetyRepository repo; bool loading=true,sending=false; String? error; List<TrustedContact> contacts=[];
 @override void initState(){super.initState();repo=SafetyRepository(ApiClient(SessionStore()));load();}
 Future<void> load()async{setState((){loading=true;error=null;});try{final x=await repo.contacts();if(mounted)setState(()=>contacts=x);}catch(e){if(mounted)setState(()=>error='Safety details could not be loaded. Pull down to retry.');}finally{if(mounted)setState(()=>loading=false);}}
 Future<Position?> location()async{try{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever)return null;return await Geolocator.getCurrentPosition();}catch(_){return null;}}
 Future<void> sos()async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.sos_rounded,color:Colors.red,size:50),title:const Text('Activate emergency SOS?'),content:const Text('Your latest location and account details will be shared with uDrive safety operations.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red),onPressed:()=>Navigator.pop(c,true),child:const Text('Send SOS'))]));if(ok!=true)return;setState(()=>sending=true);try{final pos=await location();await repo.raiseSos(type:'SOS',description:'Immediate assistance requested from the mobile application.',latitude:pos?.latitude,longitude:pos?.longitude,accuracy:pos?.accuracy);if(mounted)showDialog<void>(context:context,barrierDismissible:false,builder:(c)=>AlertDialog(icon:const Icon(Icons.verified_user_rounded,color:Colors.green,size:50),title:const Text('SOS sent'),content:const Text('uDrive safety operations have received your emergency alert.'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Understood'))]));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('SOS could not be sent. Call local emergency services if you are in immediate danger.')));}finally{if(mounted)setState(()=>sending=false);}}
 @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF861B27),Color(0xFFE53935)])),child:Column(children:[const Icon(Icons.sos_rounded,color:Colors.white,size:52),const SizedBox(height:8),const Text('Emergency assistance',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:22)),const SizedBox(height:6),const Text('Share your latest location and trip context with uDrive safety operations.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70)),const SizedBox(height:15),FilledButton.icon(onPressed:sending?null:sos,style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Colors.red),icon:sending?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.warning_amber_rounded),label:Text(sending?'Sending…':'Activate SOS'))])),const SizedBox(height:16),if(error!=null)Card(color:Colors.red.shade50,child:Padding(padding:const EdgeInsets.all(12),child:Text(error!))),Row(children:[const Expanded(child:Text('Trusted contacts',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))),FilledButton.tonalIcon(onPressed:addContact,icon:const Icon(Icons.person_add_alt_1),label:const Text('Add'))]),const SizedBox(height:8),if(loading)const Center(child:Padding(padding:EdgeInsets.all(30),child:CircularProgressIndicator())),if(!loading&&contacts.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('No trusted contacts yet. Add a family member or emergency contact.'))),...contacts.map((x)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:AppColors.primary.withValues(alpha:.12),child:const Icon(Icons.person_rounded,color:AppColors.primaryDark)),title:Text(x.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x.relationship} · ${x.phone}'),trailing:x.isPrimary?const Chip(label:Text('Primary')):null))),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Trip safety controls',style:TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:10),_row(Icons.pin_rounded,'Boarding PIN','Driver verifies the 4-digit customer PIN before starting the trip.'),_row(Icons.location_searching_rounded,'GPS health','Customer and Admin see delayed/stale location indicators.'),_row(Icons.route_rounded,'Route monitoring','Deviation and long-stop events are stored for safety review.'),_row(Icons.badge_outlined,'Driver compliance','Expired licence, CNIC, registration and insurance can restrict new rides.')])))]));
 Widget _row(IconData i,String t,String s)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:AppColors.primaryDark),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),Text(s,style:const TextStyle(color:AppColors.muted,fontSize:12,height:1.35))]))]));
 Future<void> addContact()async{final n=TextEditingController(),p=TextEditingController(),r=TextEditingController();bool primary=contacts.isEmpty;final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Add trusted contact'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone number')),TextField(controller:r,decoration:const InputDecoration(labelText:'Relationship')),CheckboxListTile(contentPadding:EdgeInsets.zero,value:primary,onChanged:(v)=>set(()=>primary=v??false),title:const Text('Primary emergency contact'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))])));if(ok==true&&n.text.trim().isNotEmpty&&p.text.trim().isNotEmpty){await repo.addContact(name:n.text.trim(),phone:p.text.trim(),relationship:r.text.trim().isEmpty?'Family':r.text.trim(),primary:primary);await load();}}
}
