'use client';import {useEffect,useState} from 'react';import {AdminFrame} from '../components/admin-frame';import {ErrorBox,Loading} from '../components/ui';import {apiFetch,isSuperAdmin,when} from '../lib/admin-api';type S={key:string;valueJson:string;description?:string;isPublic:boolean;updatedAt:string};export default function Page(){const[rows,setRows]=useState<S[]>([]);const[busy,setBusy]=useState(true);const[error,setError]=useState('');useEffect(()=>{apiFetch<S[]>('/api/v1/admin/operations/settings').then(setRows).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[]);async function save(){const values:Object=Object.fromEntries(rows.map(r=>{let value;try{value=JSON.parse(r.valueJson)}catch{value=r.valueJson}return[r.key,value]}));await apiFetch('/api/v1/admin/operations/settings',{method:'PUT',body:JSON.stringify({values})});setError('Settings saved successfully.')}return <AdminFrame title="System settings" subtitle="Central operational controls for booking, safety and support."><section className="panel formPanel">{busy?<Loading/>:<>{error&&<div className={error.includes('successfully')?'successBox':'errorBox'}>{error}</div>}<div className="settingsList">{rows.map((r,i)=><label key={r.key}><div><strong>{r.key}</strong><span>{r.description} · Updated {when(r.updatedAt)}</span></div><input value={r.valueJson} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,valueJson:e.target.value}:x))}/></label>)}</div><button className="primaryButton" onClick={save}>Save system settings</button></>}</section><PasswordPanel/><PortalLoginsPanel/><DeleteAccountPanel/></AdminFrame>}

// Handles deletion requests people email in from the public /account-deletion
// page (Google Play requires a way to delete without the app). Same effect as
// in-app deletion; the audit log records which admin did it.
function DeleteAccountPanel(){const[phone,setPhone]=useState('');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');async function run(){const p=phone.trim();if(!p)return;if(!window.confirm(`Permanently delete the UDrive account for ${p}? This cannot be undone.`))return;setBusy(true);setMsg('');try{await apiFetch('/api/v1/admin/users/delete-account',{method:'POST',body:JSON.stringify({phoneNumber:p,reason:reason.trim()||null})});setMsg(`Account ${p} deleted successfully.`);setPhone('');setReason('')}catch(e){setMsg(e instanceof Error?e.message:'Deletion failed.')}finally{setBusy(false)}}return <section className="panel formPanel" style={{marginTop:18}}><h2>Delete a user account</h2><p>For deletion requests received by email. Check the request came from the account's own number before deleting.</p>{msg&&<div className={msg.includes('successfully')?'successBox':'errorBox'}>{msg}</div>}<div className="settingsList"><label><div><strong>Mobile number</strong><span>Registered number, e.g. 03001234567</span></div><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="03001234567"/></label><label><div><strong>Note</strong><span>Optional, saved in the audit log</span></div><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Email request received on ..."/></label></div><button className="primaryButton" disabled={busy||!phone.trim()} onClick={run}>{busy?'Deleting…':'Delete account'}</button></section>}


// Changing your own portal password. Every other session of yours ends, so a
// forgotten sign-in on someone else's computer stops working immediately.
function PasswordPanel(){const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[again,setAgain]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');async function save(){if(next!==again){setMsg('The two new passwords do not match.');return}setBusy(true);setMsg('');try{await apiFetch('/api/v1/auth/admin/password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next})});setMsg('Password changed successfully. Sign in again with the new password.');setCurrent('');setNext('');setAgain('')}catch(e){setMsg(e instanceof Error?e.message:'Could not change the password.')}finally{setBusy(false)}}return <section className="panel formPanel" style={{marginTop:18}}><h2>My password</h2><p>At least 10 characters, with letters and numbers. Changing it signs you out of every device.</p>{msg&&<div className={msg.includes('successfully')?'successBox':'errorBox'}>{msg}</div>}<div className="settingsList"><label><div><strong>Current password</strong><span>The one you signed in with</span></div><input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label><div><strong>New password</strong><span>Minimum 10 characters</span></div><input type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></label><label><div><strong>Repeat new password</strong><span>Must match</span></div><input type="password" autoComplete="new-password" value={again} onChange={e=>setAgain(e.target.value)}/></label></div><button className="primaryButton" disabled={busy||!current||!next} onClick={()=>void save()}>{busy?'Saving…':'Change my password'}</button></section>}

// SuperAdmin giving portal staff their username and password. The account must
// already exist (signed in once on the app) and already have a portal role.
function PortalLoginsPanel(){const[phone,setPhone]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[allowed,setAllowed]=useState(false);useEffect(()=>{setAllowed(isSuperAdmin())},[]);if(!allowed)return null;async function save(){setBusy(true);setMsg('');try{await apiFetch('/api/v1/admin/users/credentials',{method:'POST',body:JSON.stringify({phoneNumber:phone.trim(),username:username.trim(),password})});setMsg(`Saved successfully. ${username.trim()} can now sign in with this password.`);setPassword('')}catch(e){setMsg(e instanceof Error?e.message:'Could not save the credentials.')}finally{setBusy(false)}}return <section className="panel formPanel" style={{marginTop:18}}><h2>Portal logins</h2><p>Give an admin user their username and password, or reset a forgotten one. The account must already have a portal role. Saving ends that user&apos;s open sessions.</p>{msg&&<div className={msg.includes('successfully')?'successBox':'errorBox'}>{msg}</div>}<div className="settingsList"><label><div><strong>Mobile number</strong><span>The number that account signs up with</span></div><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="03001234567"/></label><label><div><strong>Username</strong><span>Letters, numbers, dot, underscore, hyphen</span></div><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="admin"/></label><label><div><strong>Password</strong><span>Minimum 10 characters, letters and numbers</span></div><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><button className="primaryButton" disabled={busy||!phone.trim()||!username.trim()||!password} onClick={()=>void save()}>{busy?'Saving…':'Save login'}</button></section>}
