'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, MessageSquareText, RefreshCw, Search, ShieldAlert } from 'lucide-react';
import { AdminFrame } from '../components/admin-frame';
import { apiFetch, apiProtectedFile, readSession } from '../lib/admin-api';

type Dashboard={open:number;inReview:number;awaitingResponse:number;resolved:number;urgent:number};
type Evidence={id:string;fileUrl:string;fileName:string;contentType:string;fileSize:number;description?:string;createdAt:string};
type Event={id:string;actorName?:string;eventType:string;isInternal:boolean;message:string;createdAt:string};
type Case={id:string;caseReference:string;bookingReference?:string;openedByName:string;againstUserId?:string;againstUserName?:string;category:string;priority:string;subject:string;description:string;requestedResolution?:string;disputedAmount?:number;status:string;assignedAdminUserId?:string;assignedAdminName?:string;resolutionSummary?:string;version:number;createdAt:string;resolvedAt?:string;evidence?:Evidence[];events?:Event[]};

const states=['','Open','InReview','AwaitingResponse','Escalated','Resolved','Closed','Rejected'];
const priorities=['','Emergency','Urgent','Normal','Low'];

export default function DisputesPage(){
 const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [rows,setRows]=useState<Case[]>([]);const [selected,setSelected]=useState<Case|null>(null);const [status,setStatus]=useState('');const [priority,setPriority]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [note,setNote]=useState('');const [internal,setInternal]=useState(true);const [resolution,setResolution]=useState('');
 const query=useMemo(()=>new URLSearchParams({...(status?{status}:{}),...(priority?{priority}:{}),...(search?{search}:{}),}).toString(),[status,priority,search]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [d,r]=await Promise.all([apiFetch<Dashboard>('/api/v1/admin/disputes/dashboard'),apiFetch<Case[]>(`/api/v1/admin/disputes${query?`?${query}`:''}`)]);setDashboard(d);setRows(r);if(selected){const fresh=r.find(x=>x.id===selected.id);if(!fresh)setSelected(null);}}catch(e){setError(e instanceof Error?e.message:'Could not load cases.');}finally{setLoading(false)}},[query,selected]);
 useEffect(()=>{void load()},[query]);
 async function openCase(id:string){try{const x=await apiFetch<Case>(`/api/v1/admin/disputes/${id}`);setSelected(x);setResolution(x.resolutionSummary??'');}catch(e){setError(e instanceof Error?e.message:'Could not open case.')}}
 async function addNote(){if(!selected||!note.trim())return;const x=await apiFetch<Case>(`/api/v1/admin/disputes/${selected.id}/events`,{method:'POST',body:JSON.stringify({message:note.trim(),isInternal:internal,eventType:'Note'})});setSelected(x);setNote('');await load()}
 async function openEvidence(path:string){const file=await apiProtectedFile(path);window.open(file.objectUrl,'_blank','noopener,noreferrer')}
 async function caseAction(actionType:string){if(!selected)return;const reason=window.prompt('Reason for this action:');if(!reason)return;const targetUserId=selected.againstUserId??null;const x=await apiFetch<Case>(`/api/v1/admin/disputes/${selected.id}/actions`,{method:'POST',body:JSON.stringify({actionType,targetUserId,reason,amount:null})});setSelected(x);await load()}
 async function assignMe(){if(!selected)return;const me=readSession()?.user.id;if(!me)return;const x=await apiFetch<Case>(`/api/v1/admin/disputes/${selected.id}/assign`,{method:'PUT',body:JSON.stringify({assignedAdminUserId:me,expectedVersion:selected.version})});setSelected(x);await load()}
 async function changeStatus(next:string){if(!selected)return;const x=await apiFetch<Case>(`/api/v1/admin/disputes/${selected.id}/status`,{method:'PUT',body:JSON.stringify({status:next,resolutionSummary:resolution||null,expectedVersion:selected.version})});setSelected(x);await load()}
 const cards=[['Open',dashboard?.open??0,Clock3],['In review',dashboard?.inReview??0,MessageSquareText],['Awaiting reply',dashboard?.awaitingResponse??0,AlertTriangle],['Urgent',dashboard?.urgent??0,ShieldAlert],['Resolved',dashboard?.resolved??0,CheckCircle2]] as const;
 return <AdminFrame title="Complaints & disputes" subtitle="Review evidence, communicate with both parties and resolve cases with a complete audit trail." actions={<button className="button secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>}>
  <div className="metricGrid">{cards.map(([label,value,Icon])=><div className="metricCard" key={label}><div className="metricIcon"><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>
  <div className="panel"><div className="toolbar"><label className="searchBox"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Case, subject or customer"/></label><select value={status} onChange={e=>setStatus(e.target.value)}>{states.map(x=><option key={x} value={x}>{x||'All statuses'}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(x=><option key={x} value={x}>{x||'All priorities'}</option>)}</select></div>{error&&<div className="errorBanner">{error}</div>}{loading?<div className="emptyState">Loading cases…</div>:rows.length===0?<div className="emptyState">No cases match these filters.</div>:<div className="tableWrap"><table><thead><tr><th>Case</th><th>Complainant</th><th>Category</th><th>Priority</th><th>Status</th><th>Assigned</th><th>Opened</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>void openCase(x.id)} className="clickable"><td><strong>{x.caseReference}</strong><small>{x.subject}</small></td><td>{x.openedByName}<small>{x.bookingReference??'No booking'}</small></td><td>{x.category}</td><td><span className={`statusPill ${x.priority.toLowerCase()}`}>{x.priority}</span></td><td><span className="statusPill">{x.status}</span></td><td>{x.assignedAdminName??'Unassigned'}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</div>
  {selected&&<div className="modalShade" onMouseDown={()=>setSelected(null)}><section className="detailDrawer" onMouseDown={e=>e.stopPropagation()}><header><div><span>{selected.caseReference}</span><h2>{selected.subject}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><div className="detailBody"><div className="detailGrid"><div><small>Opened by</small><strong>{selected.openedByName}</strong></div><div><small>Against</small><strong>{selected.againstUserName??'Not specified'}</strong></div><div><small>Booking</small><strong>{selected.bookingReference??'—'}</strong></div><div><small>Priority</small><strong>{selected.priority}</strong></div></div><article><h3>Description</h3><p>{selected.description}</p>{selected.requestedResolution&&<p><b>Requested:</b> {selected.requestedResolution}</p>}{selected.disputedAmount!=null&&<p><b>Disputed amount:</b> PKR {selected.disputedAmount.toLocaleString()}</p>}</article><article><h3>Evidence</h3>{selected.evidence?.length?<div className="evidenceList">{selected.evidence.map(x=><button key={x.id} className="evidenceButton" onClick={()=>void openEvidence(x.fileUrl)}>{x.fileName}<small>{x.description??x.contentType}</small></button>)}</div>:<p>No evidence attached.</p>}</article><article><h3>Case timeline</h3><div className="timeline">{selected.events?.map(x=><div key={x.id}><b>{x.eventType}{x.isInternal?' · Internal':''}</b><p>{x.message}</p><small>{x.actorName??'System'} · {new Date(x.createdAt).toLocaleString()}</small></div>)}</div></article><article><h3>Add case note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Write a clear update…"/><label className="check"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/>Internal staff note</label><button className="button" onClick={()=>void addNote()}>Add note</button></article><article><h3>Case actions</h3><div className="actionRow"><button className="button secondary" onClick={()=>void assignMe()}>Assign to me</button><button className="button secondary" onClick={()=>void caseAction('Warning')}>Issue warning</button><button className="button secondary" onClick={()=>void caseAction('TemporarySuspension')}>Suspend account</button><button className="button secondary" onClick={()=>void caseAction('RefundRecommendation')}>Recommend refund</button></div></article><article><h3>Resolution</h3><textarea value={resolution} onChange={e=>setResolution(e.target.value)} rows={3} placeholder="Resolution summary…"/><div className="actionRow"><button className="button secondary" onClick={()=>void changeStatus('AwaitingResponse')}>Awaiting response</button><button className="button secondary" onClick={()=>void changeStatus('Escalated')}>Escalate</button><button className="button" onClick={()=>void changeStatus('Resolved')}>Resolve case</button><button className="button danger" onClick={()=>void changeStatus('Rejected')}>Reject</button></div></article></div></section></div>}
 </AdminFrame>
}
