import 'package:flutter/material.dart';
import '../../core/auth/session_store.dart';
import '../../core/feedback/feedback_repository.dart';
import '../../core/network/api_client.dart';
import '../../models/feedback_models.dart';

class FeedbackCenterScreen extends StatefulWidget{const FeedbackCenterScreen({super.key});@override State<FeedbackCenterScreen> createState()=>_FeedbackCenterScreenState();}
class _FeedbackCenterScreenState extends State<FeedbackCenterScreen>{late final FeedbackRepository repo;bool loading=true;String? error;List<EligibleRatingBooking> eligible=[];List<DisputeCaseItem> cases=[];
 @override void initState(){super.initState();repo=FeedbackRepository(ApiClient(SessionStore()));load();}
 Future<void> load()async{setState((){loading=true;error=null;});try{final x=await Future.wait([repo.eligible(),repo.cases()]);if(!mounted)return;setState((){eligible=x[0] as List<EligibleRatingBooking>;cases=x[1] as List<DisputeCaseItem>;});}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Ratings & support')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>openCase(),icon:const Icon(Icons.report_problem_outlined),label:const Text('New complaint')),body:RefreshIndicator(onRefresh:load,child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[if(error!=null)Card(color:Colors.red.shade50,child:Padding(padding:const EdgeInsets.all(12),child:Text(error!))),const Text('Trips awaiting rating',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),if(eligible.where((x)=>!x.alreadyRated).isEmpty)const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('No completed trip is waiting for a rating.'))),...eligible.where((x)=>!x.alreadyRated).map((x)=>Card(child:ListTile(title:Text('${x.bookingReference} · ${x.otherPartyName}'),subtitle:Text('${x.pickupAt} · PKR ${x.totalAmount.toStringAsFixed(0)}'),trailing:FilledButton(onPressed:()=>rate(x),child:const Text('Rate'))))),const SizedBox(height:18),const Text('My complaints & disputes',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),if(cases.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('No complaint cases created.'))),...cases.map((x)=>Card(child:ListTile(title:Text('${x.caseReference} · ${x.subject}'),subtitle:Text('${x.category} · ${x.status}'),trailing:Chip(label:Text(x.priority))))),const SizedBox(height:80)])));
 Future<void> rate(EligibleRatingBooking b)async{int stars=5;final text=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:Text('Rate ${b.otherPartyName}'),content:Column(mainAxisSize:MainAxisSize.min,children:[Wrap(children:List.generate(5,(i)=>IconButton(onPressed:()=>set(()=>stars=i+1),icon:Icon(i<stars?Icons.star:Icons.star_border,color:Colors.amber))),),TextField(controller:text,maxLines:3,decoration:const InputDecoration(labelText:'Review (optional)',border:OutlineInputBorder()))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Submit'))])));if(ok==true){await repo.rate(bookingId:b.bookingId,overall:stars,review:text.text);await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Rating submitted.')));}}
 Future<void> openCase()async{final subject=TextEditingController(),description=TextEditingController();String category='Service',priority='Normal';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Create complaint'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField(value:category,items:['Service','Fare','Payment','Cancellation','Behaviour','Vehicle','Route','Safety','Other'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>set(()=>category=x!),decoration:const InputDecoration(labelText:'Category')),DropdownButtonFormField(value:priority,items:['Low','Normal','Urgent','Emergency'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>set(()=>priority=x!),decoration:const InputDecoration(labelText:'Priority')),TextField(controller:subject,decoration:const InputDecoration(labelText:'Subject')),TextField(controller:description,maxLines:4,decoration:const InputDecoration(labelText:'What happened?'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Submit'))])));if(ok==true&&subject.text.trim().isNotEmpty&&description.text.trim().isNotEmpty){await repo.createCase(category:category,priority:priority,subject:subject.text,description:description.text);await load();}}
}
