using System.Data;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using UDrive.Api.Common;
using UDrive.Api.Models;

namespace UDrive.Api.Services;

public sealed class AdminOperationsService(string connectionString)
{
    private NpgsqlConnection OpenConnection() => new(connectionString);

    public async Task<ServiceResult<AdminDashboardDto>> DashboardAsync(CancellationToken ct)
    {
        await using var cn = OpenConnection(); await cn.OpenAsync(ct);
        var metrics = new List<AdminMetricDto>();
        async Task AddMetric(string label, string sql, string tone)
        {
            await using var cmd = new NpgsqlCommand(sql, cn);
            var value = Convert.ToDecimal(await cmd.ExecuteScalarAsync(ct) ?? 0);
            metrics.Add(new(label, value, 0, tone));
        }
        await AddMetric("Total bookings", "select count(*) from udrive.bookings", "emerald");
        await AddMetric("Active trips", "select count(*) from udrive.bookings where status in ('Confirmed','DriverEnRoute','DriverArrived','InProgress')", "blue");
        await AddMetric("Pending drivers", "select count(*) from udrive.driver_profiles where verification_status in ('Submitted','UnderReview')", "amber");
        await AddMetric("Gross booking value", "select coalesce(sum(total_amount),0) from udrive.bookings where status <> 'Cancelled'", "violet");
        await AddMetric("Open safety cases", "select count(*) from udrive.safety_incidents where status not in ('Resolved','Closed')", "rose");
        await AddMetric("Open tickets", "select count(*) from udrive.support_tickets where status not in ('Resolved','Closed')", "slate");

        var bookingStatuses = await CountByAsync(cn, "select status, count(*) from udrive.bookings group by status", ct);
        var queues = new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase)
        {
            ["drivers"] = await ScalarIntAsync(cn, "select count(*) from udrive.driver_profiles where verification_status in ('Submitted','UnderReview')", ct),
            ["vehicles"] = await ScalarIntAsync(cn, "select count(*) from udrive.vehicles where status in ('Submitted','UnderReview')", ct),
            ["packages"] = await ScalarIntAsync(cn, "select count(*) from udrive.tour_packages where status='PendingApproval'", ct),
            ["payments"] = await ScalarIntAsync(cn, "select count(*) from udrive.payments where status in ('Pending','Submitted')", ct)
        };
        var recent = new List<AdminRecentActivityDto>();
        await using (var cmd = new NpgsqlCommand(@"select 'booking', booking_reference, coalesce(pickup_label,'Tour package'), created_at, status from udrive.bookings order by created_at desc limit 8", cn))
        await using (var reader = await cmd.ExecuteReaderAsync(ct))
            while (await reader.ReadAsync(ct)) recent.Add(new(reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetFieldValue<DateTimeOffset>(3), reader.GetString(4)));
        return ServiceResult<AdminDashboardDto>.Ok(new(metrics, recent, bookingStatuses, queues));
    }

    public async Task<ServiceResult<IReadOnlyList<AdminBookingListItemDto>>> BookingsAsync(string? status, string? search, CancellationToken ct)
    {
        await using var cn=OpenConnection(); await cn.OpenAsync(ct);
        const string sql=@"select b.id,b.booking_reference,u.full_name,u.phone_number,du.full_name,
          case when v.id is null then null else concat(v.make,' ',v.model,' · ',v.registration_number) end,
          b.booking_type,b.status,b.seats_booked,b.total_amount,b.advance_amount,b.remaining_amount,
          b.pickup_label,b.destination_label,b.pickup_at,b.created_at
          from udrive.bookings b join udrive.users u on u.id=b.customer_user_id
          left join udrive.driver_profiles dp on dp.id=b.driver_profile_id left join udrive.users du on du.id=dp.user_id
          left join udrive.vehicles v on v.id=b.vehicle_id
          where (@status is null or b.status=@status) and (@search is null or b.booking_reference ilike '%'||@search||'%' or u.full_name ilike '%'||@search||'%' or u.phone_number ilike '%'||@search||'%')
          order by b.created_at desc limit 250";
        await using var cmd=new NpgsqlCommand(sql,cn); AddText(cmd,"status",status); AddText(cmd,"search",search);
        var list=new List<AdminBookingListItemDto>(); await using var r=await cmd.ExecuteReaderAsync(ct);
        while(await r.ReadAsync(ct)) list.Add(MapBooking(r));
        return ServiceResult<IReadOnlyList<AdminBookingListItemDto>>.Ok(list);
    }

    public async Task<ServiceResult<AdminBookingDetailDto>> BookingDetailAsync(Guid id,CancellationToken ct)
    {
        await using var cn=OpenConnection(); await cn.OpenAsync(ct);
        var booking=(await BookingsByIdAsync(cn,id,ct)); if(booking is null) return ServiceResult<AdminBookingDetailDto>.Fail(404,"booking_not_found","Booking not found.");
        var passengers=new List<AdminPassengerDto>(); await using(var cmd=new NpgsqlCommand("select id,full_name,gender,age_group,phone_number_masked,identity_verified,emergency_contact from udrive.booking_passengers where booking_id=@id order by created_at",cn)){cmd.Parameters.AddWithValue("id",id); await using var r=await cmd.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) passengers.Add(new(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetBoolean(5),r.GetBoolean(6)));}
        var history=new List<AdminStatusHistoryDto>(); await using(var cmd=new NpgsqlCommand(@"select h.from_status,h.to_status,h.reason,h.created_at,u.full_name from udrive.booking_status_history h left join udrive.users u on u.id=h.changed_by_user_id where h.entity_id=@id order by h.created_at desc",cn)){cmd.Parameters.AddWithValue("id",id); await using var r=await cmd.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) history.Add(new(r.IsDBNull(0)?null:r.GetString(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.GetFieldValue<DateTimeOffset>(3),r.IsDBNull(4)?null:r.GetString(4)));}
        var payments=await PaymentsByBookingAsync(cn,id,ct);
        return ServiceResult<AdminBookingDetailDto>.Ok(new(booking,passengers,history,payments));
    }

    public async Task<ServiceResult<bool>> UpdateBookingStatusAsync(Guid actor,Guid id,UpdateBookingStatusRequest request,CancellationToken ct)
    {
        var allowed=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"Confirmed","DriverEnRoute","DriverArrived","InProgress","Completed","Cancelled","Disputed"};
        if(!allowed.Contains(request.Status)) return ServiceResult<bool>.Fail(400,"invalid_status","Unsupported booking status.");
        await using var cn=OpenConnection(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(IsolationLevel.Serializable,ct);
        string? old; await using(var get=new NpgsqlCommand("select status from udrive.bookings where id=@id for update",cn,tx)){get.Parameters.AddWithValue("id",id); old=await get.ExecuteScalarAsync(ct) as string;}
        if(old is null) return ServiceResult<bool>.Fail(404,"booking_not_found","Booking not found.");
        await using(var update=new NpgsqlCommand("update udrive.bookings set status=@status, cancellation_reason=case when @status='Cancelled' then @reason else cancellation_reason end, updated_at=now(),version=version+1 where id=@id",cn,tx)){update.Parameters.AddWithValue("id",id);update.Parameters.AddWithValue("status",request.Status);AddText(update,"reason",request.Reason);await update.ExecuteNonQueryAsync(ct);}
        await using(var hist=new NpgsqlCommand("insert into udrive.booking_status_history(id,entity_type,entity_id,from_status,to_status,changed_by_user_id,reason,created_at) values(gen_random_uuid(),'Booking',@id,@old,@new,@actor,@reason,now())",cn,tx)){hist.Parameters.AddWithValue("id",id);hist.Parameters.AddWithValue("old",old);hist.Parameters.AddWithValue("new",request.Status);hist.Parameters.AddWithValue("actor",actor);AddText(hist,"reason",request.Reason);await hist.ExecuteNonQueryAsync(ct);}
        await AuditAsync(cn,tx,actor,"booking.status.updated","Booking",id.ToString(),JsonSerializer.Serialize(new{old,status=request.Status,request.Reason}),ct); await tx.CommitAsync(ct);
        return ServiceResult<bool>.Ok(true,"Booking status updated.");
    }

    public async Task<ServiceResult<IReadOnlyList<AdminRideRequestDto>>> RideRequestsAsync(CancellationToken ct)
    {
        await using var cn=OpenConnection();await cn.OpenAsync(ct); const string sql=@"select rr.id,u.full_name,rr.pickup_label,rr.destination_label,rr.pickup_at,rr.booking_type,rr.seats_requested,rr.customer_offer,rr.vehicle_category,rr.status,count(o.id),rr.created_at from udrive.ride_requests rr join udrive.users u on u.id=rr.customer_user_id left join udrive.driver_offers o on o.ride_request_id=rr.id group by rr.id,u.full_name order by rr.created_at desc limit 250";
        var list=new List<AdminRideRequestDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.GetString(5),r.GetInt32(6),r.GetDecimal(7),r.GetString(8),r.GetString(9),Convert.ToInt32(r.GetInt64(10)),r.GetFieldValue<DateTimeOffset>(11)));return ServiceResult<IReadOnlyList<AdminRideRequestDto>>.Ok(list);
    }

    public async Task<ServiceResult<IReadOnlyList<AdminUserDto>>> UsersAsync(string? search,CancellationToken ct)
    {
        await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select u.id,u.full_name,u.phone_number,u.email,u.status,u.preferred_language,coalesce(array_agg(ur.role) filter(where ur.role is not null),'{}'),u.last_login_at,u.created_at from udrive.users u left join udrive.user_roles ur on ur.user_id=u.id where (@search is null or u.full_name ilike '%'||@search||'%' or u.phone_number ilike '%'||@search||'%') group by u.id order by u.created_at desc limit 300";await using var cmd=new NpgsqlCommand(sql,cn);AddText(cmd,"search",search);var list=new List<AdminUserDto>();await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetString(4),r.GetString(5),r.GetFieldValue<string[]>(6),r.IsDBNull(7)?null:r.GetFieldValue<DateTimeOffset>(7),r.GetFieldValue<DateTimeOffset>(8)));return ServiceResult<IReadOnlyList<AdminUserDto>>.Ok(list);
    }
    public async Task<ServiceResult<bool>> UpdateUserStatusAsync(Guid actor,Guid id,UpdateUserStatusRequest request,CancellationToken ct){var allowed=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"Approved","Active","Suspended","Rejected"};if(!allowed.Contains(request.Status))return ServiceResult<bool>.Fail(400,"invalid_status","Unsupported user status.");await using var cn=OpenConnection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);await using(var cmd=new NpgsqlCommand("update udrive.users set status=@s,token_version=token_version+1,updated_at=now() where id=@id",cn,tx)){cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("s",request.Status);if(await cmd.ExecuteNonQueryAsync(ct)==0)return ServiceResult<bool>.Fail(404,"user_not_found","User not found.");}await AuditAsync(cn,tx,actor,"user.status.updated","User",id.ToString(),JsonSerializer.Serialize(request),ct);await tx.CommitAsync(ct);return ServiceResult<bool>.Ok(true);}
    public async Task<ServiceResult<bool>> UpdateUserRolesAsync(Guid actor,Guid id,UpdateUserRolesRequest request,CancellationToken ct){var permitted=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"Customer","Driver","SuperAdmin","Admin","Manager","Operations","VerificationOfficer","SupportAgent","FinanceOfficer","SafetyOfficer","TourismManager"};var roles=request.Roles.Where(permitted.Contains).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();if(roles.Length==0)return ServiceResult<bool>.Fail(400,"invalid_roles","At least one supported role is required.");await using var cn=OpenConnection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);await using(var del=new NpgsqlCommand("delete from udrive.user_roles where user_id=@id",cn,tx)){del.Parameters.AddWithValue("id",id);await del.ExecuteNonQueryAsync(ct);}foreach(var role in roles){await using var ins=new NpgsqlCommand("insert into udrive.user_roles(user_id,role,created_at) values(@id,@role,now()) on conflict do nothing",cn,tx);ins.Parameters.AddWithValue("id",id);ins.Parameters.AddWithValue("role",role);await ins.ExecuteNonQueryAsync(ct);}await AuditAsync(cn,tx,actor,"user.roles.updated","User",id.ToString(),JsonSerializer.Serialize(roles),ct);await tx.CommitAsync(ct);return ServiceResult<bool>.Ok(true);}

    public async Task<ServiceResult<IReadOnlyList<AdminDriverDto>>> DriversAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select dp.id,u.id,u.full_name,u.phone_number,dp.verification_status,dp.average_rating,dp.completed_trips,dp.safety_score,dp.is_online,count(v.id),dp.updated_at from udrive.driver_profiles dp join udrive.users u on u.id=dp.user_id left join udrive.vehicles v on v.driver_profile_id=dp.id group by dp.id,u.id order by dp.updated_at desc";var list=new List<AdminDriverDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDecimal(5),r.GetInt32(6),r.GetInt32(7),r.GetBoolean(8),Convert.ToInt32(r.GetInt64(9)),r.GetFieldValue<DateTimeOffset>(10)));return ServiceResult<IReadOnlyList<AdminDriverDto>>.Ok(list);}
    public async Task<ServiceResult<IReadOnlyList<AdminVehicleDto>>> VehiclesAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select v.id,u.full_name,v.registration_number,concat(v.make,' ',v.model,' ',v.year),v.category,v.passenger_capacity,v.is_four_by_four,v.mountain_readiness_score,v.status,v.updated_at from udrive.vehicles v join udrive.driver_profiles dp on dp.id=v.driver_profile_id join udrive.users u on u.id=dp.user_id order by v.updated_at desc";var list=new List<AdminVehicleDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetInt32(5),r.GetBoolean(6),r.GetInt32(7),r.GetString(8),r.GetFieldValue<DateTimeOffset>(9)));return ServiceResult<IReadOnlyList<AdminVehicleDto>>.Ok(list);}

    public async Task<ServiceResult<IReadOnlyList<AdminDestinationDto>>> DestinationsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select id,slug,name_en,name_ur,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,st_y(location::geometry),st_x(location::geometry),is_active,cover_image_url from udrive.destinations order by name_en";var list=new List<AdminDestinationDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetInt32(8),r.GetInt32(9),r.GetDouble(10),r.GetDouble(11),r.GetBoolean(12),r.IsDBNull(13)?null:r.GetString(13)));return ServiceResult<IReadOnlyList<AdminDestinationDto>>.Ok(list);}
    public Task<ServiceResult<Guid>> CreateDestinationAsync(Guid actor,UpsertDestinationRequest request,CancellationToken ct)=>UpsertDestinationAsync(actor,null,request,ct);
    public Task<ServiceResult<Guid>> UpdateDestinationAsync(Guid actor,Guid id,UpsertDestinationRequest request,CancellationToken ct)=>UpsertDestinationAsync(actor,id,request,ct);
    private async Task<ServiceResult<Guid>> UpsertDestinationAsync(Guid actor,Guid? id,UpsertDestinationRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);var entity=id??Guid.NewGuid();const string sql=@"insert into udrive.destinations(id,slug,name_en,name_ur,summary_en,summary_ur,location,district,best_season,recommended_vehicle,network_status,family_suitability_score,route_safety_score,cover_image_url,is_active,created_at,updated_at) values(@id,@slug,@en,@ur,@sen,@sur,st_setsrid(st_makepoint(@lng,@lat),4326)::geography,@district,@season,@vehicle,@network,@family,@safety,@image,@active,now(),now()) on conflict(id) do update set slug=excluded.slug,name_en=excluded.name_en,name_ur=excluded.name_ur,summary_en=excluded.summary_en,summary_ur=excluded.summary_ur,location=excluded.location,district=excluded.district,best_season=excluded.best_season,recommended_vehicle=excluded.recommended_vehicle,network_status=excluded.network_status,family_suitability_score=excluded.family_suitability_score,route_safety_score=excluded.route_safety_score,cover_image_url=excluded.cover_image_url,is_active=excluded.is_active,updated_at=now()";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",entity);cmd.Parameters.AddWithValue("slug",request.Slug);cmd.Parameters.AddWithValue("en",request.NameEn);cmd.Parameters.AddWithValue("ur",request.NameUr);cmd.Parameters.AddWithValue("sen",request.SummaryEn);cmd.Parameters.AddWithValue("sur",request.SummaryUr);cmd.Parameters.AddWithValue("lng",request.Longitude);cmd.Parameters.AddWithValue("lat",request.Latitude);cmd.Parameters.AddWithValue("district",request.District);cmd.Parameters.AddWithValue("season",request.BestSeason);cmd.Parameters.AddWithValue("vehicle",request.RecommendedVehicle);cmd.Parameters.AddWithValue("network",request.NetworkStatus);cmd.Parameters.AddWithValue("family",request.FamilySuitabilityScore);cmd.Parameters.AddWithValue("safety",request.RouteSafetyScore);AddText(cmd,"image",request.CoverImageUrl);cmd.Parameters.AddWithValue("active",request.IsActive);await cmd.ExecuteNonQueryAsync(ct);await AuditStandaloneAsync(cn,actor,id is null?"destination.created":"destination.updated","Destination",entity.ToString(),JsonSerializer.Serialize(request),ct);return id is null?ServiceResult<Guid>.Created(entity):ServiceResult<Guid>.Ok(entity);}

    public async Task<ServiceResult<IReadOnlyList<AdminRouteDto>>> RoutesAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select r.id,r.name,o.name_en,d.name_en,r.distance_km,r.estimated_minutes,r.recommended_vehicle,r.four_by_four_required,r.daylight_only,r.safety_score,r.is_active from udrive.routes r left join udrive.destinations o on o.id=r.origin_destination_id left join udrive.destinations d on d.id=r.destination_id order by r.name";var list=new List<AdminRouteDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetDecimal(4),r.GetInt32(5),r.GetString(6),r.GetBoolean(7),r.GetBoolean(8),r.GetInt32(9),r.GetBoolean(10)));return ServiceResult<IReadOnlyList<AdminRouteDto>>.Ok(list);}
    public Task<ServiceResult<Guid>> CreateRouteAsync(Guid actor,UpsertRouteRequest request,CancellationToken ct)=>UpsertRouteAsync(actor,null,request,ct);public Task<ServiceResult<Guid>> UpdateRouteAsync(Guid actor,Guid id,UpsertRouteRequest request,CancellationToken ct)=>UpsertRouteAsync(actor,id,request,ct);
    private async Task<ServiceResult<Guid>> UpsertRouteAsync(Guid actor,Guid? id,UpsertRouteRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);var entity=id??Guid.NewGuid();const string sql=@"insert into udrive.routes(id,name,origin_destination_id,destination_id,origin_location,destination_location,distance_km,estimated_minutes,recommended_vehicle,four_by_four_required,daylight_only,safety_score,is_active,created_at,updated_at) values(@id,@name,@origin,@destination,st_setsrid(st_makepoint(@olng,@olat),4326)::geography,st_setsrid(st_makepoint(@dlng,@dlat),4326)::geography,@distance,@minutes,@vehicle,@four,@day,@safety,@active,now(),now()) on conflict(id) do update set name=excluded.name,origin_destination_id=excluded.origin_destination_id,destination_id=excluded.destination_id,origin_location=excluded.origin_location,destination_location=excluded.destination_location,distance_km=excluded.distance_km,estimated_minutes=excluded.estimated_minutes,recommended_vehicle=excluded.recommended_vehicle,four_by_four_required=excluded.four_by_four_required,daylight_only=excluded.daylight_only,safety_score=excluded.safety_score,is_active=excluded.is_active,updated_at=now()";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",entity);cmd.Parameters.AddWithValue("name",request.Name);AddGuid(cmd,"origin",request.OriginDestinationId);AddGuid(cmd,"destination",request.DestinationId);cmd.Parameters.AddWithValue("olng",request.OriginLongitude);cmd.Parameters.AddWithValue("olat",request.OriginLatitude);cmd.Parameters.AddWithValue("dlng",request.DestinationLongitude);cmd.Parameters.AddWithValue("dlat",request.DestinationLatitude);cmd.Parameters.AddWithValue("distance",request.DistanceKm);cmd.Parameters.AddWithValue("minutes",request.EstimatedMinutes);cmd.Parameters.AddWithValue("vehicle",request.RecommendedVehicle);cmd.Parameters.AddWithValue("four",request.FourByFourRequired);cmd.Parameters.AddWithValue("day",request.DaylightOnly);cmd.Parameters.AddWithValue("safety",request.SafetyScore);cmd.Parameters.AddWithValue("active",request.IsActive);await cmd.ExecuteNonQueryAsync(ct);await AuditStandaloneAsync(cn,actor,id is null?"route.created":"route.updated","Route",entity.ToString(),JsonSerializer.Serialize(request),ct);return id is null?ServiceResult<Guid>.Created(entity):ServiceResult<Guid>.Ok(entity);}

    public async Task<ServiceResult<IReadOnlyList<AdminAdvisoryDto>>> AdvisoriesAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select a.id,a.route_id,r.name,a.severity,a.title_en,a.title_ur,a.details_en,a.details_ur,a.source_name,a.starts_at,a.ends_at,a.is_active from udrive.route_advisories a left join udrive.routes r on r.id=a.route_id order by a.created_at desc";var list=new List<AdminAdvisoryDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.IsDBNull(1)?null:r.GetGuid(1),r.IsDBNull(2)?null:r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetFieldValue<DateTimeOffset>(9),r.IsDBNull(10)?null:r.GetFieldValue<DateTimeOffset>(10),r.GetBoolean(11)));return ServiceResult<IReadOnlyList<AdminAdvisoryDto>>.Ok(list);}
    public Task<ServiceResult<Guid>> CreateAdvisoryAsync(Guid actor,UpsertAdvisoryRequest request,CancellationToken ct)=>UpsertAdvisoryAsync(actor,null,request,ct);public Task<ServiceResult<Guid>> UpdateAdvisoryAsync(Guid actor,Guid id,UpsertAdvisoryRequest request,CancellationToken ct)=>UpsertAdvisoryAsync(actor,id,request,ct);
    private async Task<ServiceResult<Guid>> UpsertAdvisoryAsync(Guid actor,Guid? id,UpsertAdvisoryRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);var entity=id??Guid.NewGuid();const string sql=@"insert into udrive.route_advisories(id,route_id,severity,title_en,title_ur,details_en,details_ur,source_name,starts_at,ends_at,is_active,created_at,updated_at) values(@id,@route,@severity,@en,@ur,@den,@dur,@source,@starts,@ends,@active,now(),now()) on conflict(id) do update set route_id=excluded.route_id,severity=excluded.severity,title_en=excluded.title_en,title_ur=excluded.title_ur,details_en=excluded.details_en,details_ur=excluded.details_ur,source_name=excluded.source_name,starts_at=excluded.starts_at,ends_at=excluded.ends_at,is_active=excluded.is_active,updated_at=now()";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",entity);AddGuid(cmd,"route",request.RouteId);cmd.Parameters.AddWithValue("severity",request.Severity);cmd.Parameters.AddWithValue("en",request.TitleEn);cmd.Parameters.AddWithValue("ur",request.TitleUr);cmd.Parameters.AddWithValue("den",request.DetailsEn);cmd.Parameters.AddWithValue("dur",request.DetailsUr);cmd.Parameters.AddWithValue("source",request.SourceName);cmd.Parameters.AddWithValue("starts",request.StartsAt);AddDateTime(cmd,"ends",request.EndsAt);cmd.Parameters.AddWithValue("active",request.IsActive);await cmd.ExecuteNonQueryAsync(ct);await AuditStandaloneAsync(cn,actor,id is null?"advisory.created":"advisory.updated","RouteAdvisory",entity.ToString(),JsonSerializer.Serialize(request),ct);return id is null?ServiceResult<Guid>.Created(entity):ServiceResult<Guid>.Ok(entity);}

    public async Task<ServiceResult<IReadOnlyList<AdminSafetyIncidentDto>>> SafetyIncidentsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select s.id,b.booking_reference,u.full_name,s.severity,s.incident_type,s.description,s.status,a.full_name,s.resolution_notes,s.created_at,s.resolved_at from udrive.safety_incidents s join udrive.users u on u.id=s.reported_by_user_id left join udrive.bookings b on b.id=s.booking_id left join udrive.users a on a.id=s.assigned_admin_user_id order by case s.severity when 'Critical' then 1 when 'High' then 2 else 3 end,s.created_at desc";var list=new List<AdminSafetyIncidentDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.IsDBNull(1)?null:r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.IsDBNull(8)?null:r.GetString(8),r.GetFieldValue<DateTimeOffset>(9),r.IsDBNull(10)?null:r.GetFieldValue<DateTimeOffset>(10)));return ServiceResult<IReadOnlyList<AdminSafetyIncidentDto>>.Ok(list);}
    public async Task<ServiceResult<bool>> UpdateSafetyIncidentAsync(Guid actor,Guid id,UpdateSafetyIncidentRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"update udrive.safety_incidents set status=@status,assigned_admin_user_id=@assigned,assigned_at=case when @assigned is null then assigned_at else coalesce(assigned_at,now()) end,resolution_notes=@notes,resolved_at=case when @status in ('Resolved','Closed') then now() else null end,updated_at=now() where id=@id";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("status",request.Status);AddGuid(cmd,"assigned",request.AssignedAdminUserId);AddText(cmd,"notes",request.ResolutionNotes);if(await cmd.ExecuteNonQueryAsync(ct)==0)return ServiceResult<bool>.Fail(404,"incident_not_found","Safety incident not found.");await AuditStandaloneAsync(cn,actor,"safety.updated","SafetyIncident",id.ToString(),JsonSerializer.Serialize(request),ct);return ServiceResult<bool>.Ok(true);}

    public async Task<ServiceResult<IReadOnlyList<AdminPaymentDto>>> PaymentsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select p.id,b.booking_reference,u.full_name,p.method,p.amount,p.currency,p.status,p.provider_reference,p.refund_amount,p.review_notes,p.created_at from udrive.payments p join udrive.bookings b on b.id=p.booking_id join udrive.users u on u.id=b.customer_user_id order by p.created_at desc";var list=new List<AdminPaymentDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(MapPayment(r));return ServiceResult<IReadOnlyList<AdminPaymentDto>>.Ok(list);}
    public async Task<ServiceResult<bool>> UpdatePaymentAsync(Guid actor,Guid id,UpdatePaymentRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"update udrive.payments set status=@status,refund_amount=@refund,review_notes=@notes,reviewed_by_user_id=@actor,reviewed_at=now(),updated_at=now() where id=@id";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("status",request.Status);cmd.Parameters.AddWithValue("refund",request.RefundAmount);AddText(cmd,"notes",request.ReviewNotes);cmd.Parameters.AddWithValue("actor",actor);if(await cmd.ExecuteNonQueryAsync(ct)==0)return ServiceResult<bool>.Fail(404,"payment_not_found","Payment not found.");await AuditStandaloneAsync(cn,actor,"payment.reviewed","Payment",id.ToString(),JsonSerializer.Serialize(request),ct);return ServiceResult<bool>.Ok(true);}

    public async Task<ServiceResult<IReadOnlyList<AdminSupportTicketDto>>> TicketsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select t.id,t.reference,u.full_name,b.booking_reference,t.category,t.priority,t.subject,t.description,t.status,a.full_name,t.resolution_notes,t.created_at,t.updated_at from udrive.support_tickets t left join udrive.users u on u.id=t.created_by_user_id left join udrive.bookings b on b.id=t.booking_id left join udrive.users a on a.id=t.assigned_admin_user_id order by t.created_at desc";var list=new List<AdminSupportTicketDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.IsDBNull(9)?null:r.GetString(9),r.IsDBNull(10)?null:r.GetString(10),r.GetFieldValue<DateTimeOffset>(11),r.GetFieldValue<DateTimeOffset>(12)));return ServiceResult<IReadOnlyList<AdminSupportTicketDto>>.Ok(list);}
    public async Task<ServiceResult<Guid>> CreateTicketAsync(Guid actor,CreateSupportTicketRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);var id=Guid.NewGuid();var reference=$"SUP-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(1000,9999)}";const string sql=@"insert into udrive.support_tickets(id,reference,created_by_user_id,booking_id,category,priority,subject,description,status,created_at,updated_at) values(@id,@ref,@customer,@booking,@category,@priority,@subject,@description,'Open',now(),now())";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("ref",reference);AddGuid(cmd,"customer",request.CustomerUserId);AddGuid(cmd,"booking",request.BookingId);cmd.Parameters.AddWithValue("category",request.Category);cmd.Parameters.AddWithValue("priority",request.Priority);cmd.Parameters.AddWithValue("subject",request.Subject);cmd.Parameters.AddWithValue("description",request.Description);await cmd.ExecuteNonQueryAsync(ct);await AuditStandaloneAsync(cn,actor,"support.created","SupportTicket",id.ToString(),JsonSerializer.Serialize(request),ct);return ServiceResult<Guid>.Created(id,reference);}
    public async Task<ServiceResult<bool>> UpdateTicketAsync(Guid actor,Guid id,UpdateSupportTicketRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"update udrive.support_tickets set status=@status,assigned_admin_user_id=@assigned,resolution_notes=@notes,resolved_at=case when @status in ('Resolved','Closed') then now() else null end,updated_at=now() where id=@id";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("status",request.Status);AddGuid(cmd,"assigned",request.AssignedAdminUserId);AddText(cmd,"notes",request.ResolutionNotes);if(await cmd.ExecuteNonQueryAsync(ct)==0)return ServiceResult<bool>.Fail(404,"ticket_not_found","Support ticket not found.");await AuditStandaloneAsync(cn,actor,"support.updated","SupportTicket",id.ToString(),JsonSerializer.Serialize(request),ct);return ServiceResult<bool>.Ok(true);}
    public async Task<ServiceResult<int>> BroadcastAsync(Guid actor,BroadcastNotificationRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"insert into udrive.notifications(id,user_id,type,title,body,data_json,created_at,updated_at) select gen_random_uuid(),u.id,@type,@title,@body,cast(@data as jsonb),now(),now() from udrive.users u where (@role is null or exists(select 1 from udrive.user_roles ur where ur.user_id=u.id and ur.role=@role))";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("type",request.Type);cmd.Parameters.AddWithValue("title",request.Title);cmd.Parameters.AddWithValue("body",request.Body);AddText(cmd,"role",request.AudienceRole);cmd.Parameters.AddWithValue("data",request.Data?.GetRawText()??"{}");var count=await cmd.ExecuteNonQueryAsync(ct);await AuditStandaloneAsync(cn,actor,"notification.broadcast","Notification","broadcast",JsonSerializer.Serialize(new{request.Type,request.Title,request.AudienceRole,count}),ct);return ServiceResult<int>.Created(count,$"Notification queued for {count} users.");}

    public async Task<ServiceResult<IReadOnlyList<AdminAuditLogDto>>> AuditLogsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);const string sql=@"select l.id,u.full_name,l.action,l.entity_type,l.entity_id,l.ip_address,l.changes_json::text,l.created_at from udrive.audit_logs l left join udrive.users u on u.id=l.actor_user_id order by l.created_at desc limit 500";var list=new List<AdminAuditLogDto>();await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.IsDBNull(1)?null:r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetString(6),r.GetFieldValue<DateTimeOffset>(7)));return ServiceResult<IReadOnlyList<AdminAuditLogDto>>.Ok(list);}
    public async Task<ServiceResult<IReadOnlyList<AdminSettingDto>>> SettingsAsync(CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);var list=new List<AdminSettingDto>();await using var cmd=new NpgsqlCommand("select key,value_json::text,description,is_public,updated_at from udrive.system_settings order by key",cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetString(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.GetBoolean(3),r.GetFieldValue<DateTimeOffset>(4)));return ServiceResult<IReadOnlyList<AdminSettingDto>>.Ok(list);}
    public async Task<ServiceResult<int>> UpdateSettingsAsync(Guid actor,UpdateSettingsRequest request,CancellationToken ct){await using var cn=OpenConnection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var count=0;foreach(var item in request.Values){await using var cmd=new NpgsqlCommand("insert into udrive.system_settings(key,value_json,updated_by_user_id,created_at,updated_at) values(@key,cast(@value as jsonb),@actor,now(),now()) on conflict(key) do update set value_json=excluded.value_json,updated_by_user_id=excluded.updated_by_user_id,updated_at=now()",cn,tx);cmd.Parameters.AddWithValue("key",item.Key);cmd.Parameters.AddWithValue("value",item.Value.GetRawText());cmd.Parameters.AddWithValue("actor",actor);count+=await cmd.ExecuteNonQueryAsync(ct);}await AuditAsync(cn,tx,actor,"settings.updated","SystemSettings","multiple",JsonSerializer.Serialize(request.Values.Keys),ct);await tx.CommitAsync(ct);return ServiceResult<int>.Ok(count);}

    private static AdminBookingListItemDto MapBooking(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetString(6),r.GetString(7),r.GetInt32(8),r.GetDecimal(9),r.GetDecimal(10),r.GetDecimal(11),r.IsDBNull(12)?null:r.GetString(12),r.IsDBNull(13)?null:r.GetString(13),r.GetFieldValue<DateTimeOffset>(14),r.GetFieldValue<DateTimeOffset>(15));
    private async Task<AdminBookingListItemDto?> BookingsByIdAsync(NpgsqlConnection cn,Guid id,CancellationToken ct){const string sql=@"select b.id,b.booking_reference,u.full_name,u.phone_number,du.full_name,case when v.id is null then null else concat(v.make,' ',v.model,' · ',v.registration_number) end,b.booking_type,b.status,b.seats_booked,b.total_amount,b.advance_amount,b.remaining_amount,b.pickup_label,b.destination_label,b.pickup_at,b.created_at from udrive.bookings b join udrive.users u on u.id=b.customer_user_id left join udrive.driver_profiles dp on dp.id=b.driver_profile_id left join udrive.users du on du.id=dp.user_id left join udrive.vehicles v on v.id=b.vehicle_id where b.id=@id";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",id);await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?MapBooking(r):null;}
    private static AdminPaymentDto MapPayment(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetDecimal(4),r.GetString(5),r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.GetDecimal(8),r.IsDBNull(9)?null:r.GetString(9),r.GetFieldValue<DateTimeOffset>(10));
    private async Task<IReadOnlyList<AdminPaymentDto>> PaymentsByBookingAsync(NpgsqlConnection cn,Guid bookingId,CancellationToken ct){const string sql=@"select p.id,b.booking_reference,u.full_name,p.method,p.amount,p.currency,p.status,p.provider_reference,p.refund_amount,p.review_notes,p.created_at from udrive.payments p join udrive.bookings b on b.id=p.booking_id join udrive.users u on u.id=b.customer_user_id where p.booking_id=@id order by p.created_at desc";await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue("id",bookingId);var list=new List<AdminPaymentDto>();await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(MapPayment(r));return list;}
    private static async Task<int> ScalarIntAsync(NpgsqlConnection cn,string sql,CancellationToken ct){await using var cmd=new NpgsqlCommand(sql,cn);return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct)??0);}
    private static async Task<Dictionary<string,int>> CountByAsync(NpgsqlConnection cn,string sql,CancellationToken ct){var d=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);await using var cmd=new NpgsqlCommand(sql,cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))d[r.GetString(0)]=Convert.ToInt32(r.GetInt64(1));return d;}
    private static void AddText(NpgsqlCommand cmd,string name,string? value)=>cmd.Parameters.Add(new NpgsqlParameter(name,NpgsqlDbType.Text){Value=(object?)value??DBNull.Value});
    private static void AddGuid(NpgsqlCommand cmd,string name,Guid? value)=>cmd.Parameters.Add(new NpgsqlParameter(name,NpgsqlDbType.Uuid){Value=value.HasValue?(object)value.Value:DBNull.Value});
    private static void AddDateTime(NpgsqlCommand cmd,string name,DateTimeOffset? value)=>cmd.Parameters.Add(new NpgsqlParameter(name,NpgsqlDbType.TimestampTz){Value=value.HasValue?(object)value.Value:DBNull.Value});
    private static async Task AuditStandaloneAsync(NpgsqlConnection cn,Guid actor,string action,string type,string entity,string changes,CancellationToken ct){await using var cmd=new NpgsqlCommand("insert into udrive.audit_logs(id,actor_user_id,action,entity_type,entity_id,changes_json,created_at,updated_at) values(gen_random_uuid(),@actor,@action,@type,@entity,cast(@changes as jsonb),now(),now())",cn);cmd.Parameters.AddWithValue("actor",actor);cmd.Parameters.AddWithValue("action",action);cmd.Parameters.AddWithValue("type",type);cmd.Parameters.AddWithValue("entity",entity);cmd.Parameters.AddWithValue("changes",changes);await cmd.ExecuteNonQueryAsync(ct);}
    private static async Task AuditAsync(NpgsqlConnection cn,NpgsqlTransaction tx,Guid actor,string action,string type,string entity,string changes,CancellationToken ct){await using var cmd=new NpgsqlCommand("insert into udrive.audit_logs(id,actor_user_id,action,entity_type,entity_id,changes_json,created_at,updated_at) values(gen_random_uuid(),@actor,@action,@type,@entity,cast(@changes as jsonb),now(),now())",cn,tx);cmd.Parameters.AddWithValue("actor",actor);cmd.Parameters.AddWithValue("action",action);cmd.Parameters.AddWithValue("type",type);cmd.Parameters.AddWithValue("entity",entity);cmd.Parameters.AddWithValue("changes",changes);await cmd.ExecuteNonQueryAsync(ct);}
}
