using Npgsql;
using UDrive.Api.Common;
using UDrive.Api.Models;

namespace UDrive.Api.Services;

public sealed class CommunicationService(string connectionString)
{
    NpgsqlConnection Open()=>new(connectionString);
    static void P(NpgsqlCommand c,string n,object? v)=>c.Parameters.AddWithValue(n,v??DBNull.Value);

    public async Task<ServiceResult<NotificationPageDto>> NotificationsAsync(Guid user,int take,CancellationToken ct)
    {
        take=Math.Clamp(take,1,100);await using var cn=Open();await cn.OpenAsync(ct);
        var list=new List<NotificationDto>();await using(var cmd=new NpgsqlCommand(@"select id,type,title,body,action_path,read_at,created_at from udrive.notifications where user_id=@u order by created_at desc limit @take",cn)){P(cmd,"u",user);P(cmd,"take",take);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),!r.IsDBNull(5),r.GetFieldValue<DateTimeOffset>(6)));}
        await using var count=new NpgsqlCommand("select count(*) from udrive.notifications where user_id=@u and read_at is null",cn);P(count,"u",user);var unread=Convert.ToInt32(await count.ExecuteScalarAsync(ct));return ServiceResult<NotificationPageDto>.Ok(new(list,unread));
    }
    public async Task<ServiceResult<bool>> MarkReadAsync(Guid user,Guid? id,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);var sql=id is null?"update udrive.notifications set read_at=coalesce(read_at,now()),updated_at=now() where user_id=@u":"update udrive.notifications set read_at=coalesce(read_at,now()),updated_at=now() where user_id=@u and id=@id";await using var c=new NpgsqlCommand(sql,cn);P(c,"u",user);if(id is not null)P(c,"id",id);await c.ExecuteNonQueryAsync(ct);return ServiceResult<bool>.Ok(true);}
    public async Task<ServiceResult<NotificationPreferencesDto>> PreferencesAsync(Guid user,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);await using var c=new NpgsqlCommand(@"insert into udrive.notification_preferences(user_id) values(@u) on conflict(user_id) do nothing;select booking_alerts,package_alerts,payout_alerts,complaint_alerts,promotional_alerts,push_enabled,sms_enabled from udrive.notification_preferences where user_id=@u",cn);P(c,"u",user);await using var r=await c.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return ServiceResult<NotificationPreferencesDto>.Ok(new(r.GetBoolean(0),r.GetBoolean(1),r.GetBoolean(2),r.GetBoolean(3),r.GetBoolean(4),r.GetBoolean(5),r.GetBoolean(6)));}
    public async Task<ServiceResult<NotificationPreferencesDto>> SavePreferencesAsync(Guid user,NotificationPreferencesDto x,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);await using var c=new NpgsqlCommand(@"insert into udrive.notification_preferences(user_id,booking_alerts,package_alerts,payout_alerts,complaint_alerts,promotional_alerts,push_enabled,sms_enabled,updated_at) values(@u,@b,@p,@w,@c,@m,@push,@sms,now()) on conflict(user_id) do update set booking_alerts=excluded.booking_alerts,package_alerts=excluded.package_alerts,payout_alerts=excluded.payout_alerts,complaint_alerts=excluded.complaint_alerts,promotional_alerts=excluded.promotional_alerts,push_enabled=excluded.push_enabled,sms_enabled=excluded.sms_enabled,updated_at=now()",cn);P(c,"u",user);P(c,"b",x.BookingAlerts);P(c,"p",x.PackageAlerts);P(c,"w",x.PayoutAlerts);P(c,"c",x.ComplaintAlerts);P(c,"m",x.PromotionalAlerts);P(c,"push",x.PushEnabled);P(c,"sms",x.SmsEnabled);await c.ExecuteNonQueryAsync(ct);return ServiceResult<NotificationPreferencesDto>.Ok(x);}
    public async Task<ServiceResult<bool>> RegisterDeviceAsync(Guid user,RegisterDeviceRequest x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.DeviceToken)||string.IsNullOrWhiteSpace(x.Platform))return ServiceResult<bool>.Fail(400,"invalid_device","Device token and platform are required.");await using var cn=Open();await cn.OpenAsync(ct);await using var c=new NpgsqlCommand(@"insert into udrive.user_devices(id,user_id,device_token,platform,device_name,is_active,last_seen_at,created_at,updated_at) values(gen_random_uuid(),@u,@t,@p,@n,true,now(),now(),now()) on conflict(device_token) do update set user_id=excluded.user_id,platform=excluded.platform,device_name=excluded.device_name,is_active=true,last_seen_at=now(),updated_at=now()",cn);P(c,"u",user);P(c,"t",x.DeviceToken.Trim());P(c,"p",x.Platform.Trim());P(c,"n",x.DeviceName);await c.ExecuteNonQueryAsync(ct);return ServiceResult<bool>.Ok(true);}
    async Task<bool> CanAccessBooking(NpgsqlConnection cn,Guid user,Guid booking,CancellationToken ct){await using var c=new NpgsqlCommand(@"select exists(select 1 from udrive.bookings b left join udrive.driver_profiles d on d.id=b.driver_profile_id where b.id=@b and (b.customer_user_id=@u or d.user_id=@u))",cn);P(c,"b",booking);P(c,"u",user);return (bool)(await c.ExecuteScalarAsync(ct)??false);}
    public async Task<ServiceResult<IReadOnlyList<BookingMessageDto>>> MessagesAsync(Guid user,Guid booking,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);if(!await CanAccessBooking(cn,user,booking,ct))return ServiceResult<IReadOnlyList<BookingMessageDto>>.Fail(403,"booking_access_denied","You cannot access this booking conversation.");await using(var ensure=new NpgsqlCommand("insert into udrive.booking_conversations(id,booking_id) values(gen_random_uuid(),@b) on conflict(booking_id) do nothing",cn)){P(ensure,"b",booking);await ensure.ExecuteNonQueryAsync(ct);}await using(var mark=new NpgsqlCommand(@"update udrive.booking_messages m set read_at=coalesce(read_at,now()) from udrive.booking_conversations c where c.id=m.conversation_id and c.booking_id=@b and m.sender_user_id<>@u",cn)){P(mark,"b",booking);P(mark,"u",user);await mark.ExecuteNonQueryAsync(ct);}var list=new List<BookingMessageDto>();await using var cmd=new NpgsqlCommand(@"select m.id,c.booking_id,m.sender_user_id,coalesce(u.full_name,u.phone_number,'User'),m.body,m.read_at,m.sent_at from udrive.booking_messages m join udrive.booking_conversations c on c.id=m.conversation_id join udrive.users u on u.id=m.sender_user_id where c.booking_id=@b order by m.sent_at",cn);P(cmd,"b",booking);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3),r.GetString(4),r.GetGuid(2)==user,!r.IsDBNull(5),r.GetFieldValue<DateTimeOffset>(6)));return ServiceResult<IReadOnlyList<BookingMessageDto>>.Ok(list);}
    public async Task<ServiceResult<BookingMessageDto>> SendAsync(Guid user,Guid booking,SendBookingMessageRequest x,CancellationToken ct){var body=x.Body?.Trim();if(string.IsNullOrWhiteSpace(body)||body.Length>2000)return ServiceResult<BookingMessageDto>.Fail(400,"invalid_message","Message must contain 1 to 2000 characters.");await using var cn=Open();await cn.OpenAsync(ct);if(!await CanAccessBooking(cn,user,booking,ct))return ServiceResult<BookingMessageDto>.Fail(403,"booking_access_denied","You cannot access this booking conversation.");await using var tx=await cn.BeginTransactionAsync(ct);Guid conversation;await using(var ensure=new NpgsqlCommand(@"insert into udrive.booking_conversations(id,booking_id) values(gen_random_uuid(),@b) on conflict(booking_id) do update set updated_at=now() returning id",cn,tx)){P(ensure,"b",booking);conversation=(Guid)(await ensure.ExecuteScalarAsync(ct))!;}Guid id;await using(var insert=new NpgsqlCommand(@"insert into udrive.booking_messages(id,conversation_id,sender_user_id,body) values(gen_random_uuid(),@c,@u,@body) returning id",cn,tx)){P(insert,"c",conversation);P(insert,"u",user);P(insert,"body",body);id=(Guid)(await insert.ExecuteScalarAsync(ct))!;}await using(var notify=new NpgsqlCommand(@"insert into udrive.notifications(id,user_id,type,title,body,data_json,action_path,created_at,updated_at) select gen_random_uuid(),x.user_id,'BookingMessage','New trip message',@body,jsonb_build_object('bookingId',@b),'/bookings/'||@b||'/messages',now(),now() from (select b.customer_user_id user_id from udrive.bookings b where b.id=@b union select d.user_id from udrive.bookings b join udrive.driver_profiles d on d.id=b.driver_profile_id where b.id=@b)x where x.user_id<>@u",cn,tx)){P(notify,"b",booking);P(notify,"u",user);P(notify,"body",body);await notify.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return ServiceResult<BookingMessageDto>.Created(new(id,booking,user,"You",body,true,false,DateTimeOffset.UtcNow),"Message sent.");}
}
