using System.Text.Json;
using Npgsql;
using UDrive.Api.Common;
using UDrive.Api.Models;

namespace UDrive.Api.Services;

public sealed class HotelService(string connectionString)
{
    public async Task<ServiceResult<object>> SearchAsync(HotelSearchRequest request, CancellationToken ct)
    {
        var page = Math.Max(1, request.Page); var size = Math.Clamp(request.PageSize, 1, 30); var offset=(page-1)*size;
        await using var c=new NpgsqlConnection(connectionString); await c.OpenAsync(ct);
        await using var cmd=c.CreateCommand();
        cmd.CommandText="""
        SELECT h.id,h.name,h.address,h.city,h.district,h.latitude,h.longitude,h.contact_phone,h.rating,h.main_image_url,h.amenities,h.transport_available,
               COALESCE(MIN(CASE WHEN r.is_active THEN COALESCE(i.rate,r.base_rate) END),0) starting_rate,
               COALESCE(SUM(CASE WHEN r.is_active THEN COALESCE(i.available_rooms,r.total_rooms) ELSE 0 END),0) available_rooms
        FROM udrive.hotels h
        LEFT JOIN udrive.hotel_rooms r ON r.hotel_id=h.id
        LEFT JOIN udrive.hotel_room_inventory i ON i.room_id=r.id AND i.inventory_date=@check_in
        WHERE h.approval_status='Approved' AND h.is_active
          AND (@query='' OR h.name ILIKE '%'||@query||'%' OR h.city ILIKE '%'||@query||'%' OR h.address ILIKE '%'||@query||'%')
          AND (@city='' OR h.city ILIKE @city)
        GROUP BY h.id
        HAVING (@check_in IS NULL OR COALESCE(SUM(CASE WHEN r.is_active THEN COALESCE(i.available_rooms,r.total_rooms) ELSE 0 END),0) >= @rooms)
        ORDER BY h.rating DESC,h.created_at DESC
        LIMIT @limit OFFSET @offset;
        """;
        cmd.Parameters.AddWithValue("query",request.Query?.Trim()??""); cmd.Parameters.AddWithValue("city",request.City?.Trim()??"");
        cmd.Parameters.AddWithValue("check_in",(object?)request.CheckIn??DBNull.Value); cmd.Parameters.AddWithValue("rooms",Math.Max(1,request.Rooms)); cmd.Parameters.AddWithValue("limit",size); cmd.Parameters.AddWithValue("offset",offset);
        var list=new List<object>(); await using var r=await cmd.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) list.Add(MapHotel(r));
        return ServiceResult<object>.Ok(new {items=list,page,pageSize=size,hasMore=list.Count==size});
    }

    public async Task<ServiceResult<object>> GetAsync(Guid id, DateOnly? checkIn, DateOnly? checkOut, CancellationToken ct)
    {
        await using var c=new NpgsqlConnection(connectionString); await c.OpenAsync(ct);
        object? hotel=null; await using(var cmd=c.CreateCommand()) {cmd.CommandText="""SELECT h.id,h.name,h.address,h.city,h.district,h.latitude,h.longitude,h.contact_phone,h.rating,h.main_image_url,h.amenities,h.transport_available,h.description,0::numeric,0::bigint FROM udrive.hotels h WHERE h.id=@id AND h.approval_status='Approved' AND h.is_active""";cmd.Parameters.AddWithValue("id",id);await using var r=await cmd.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))hotel=MapHotel(r,true);} if(hotel is null)return ServiceResult<object>.Fail(404,"hotel_not_found","Hotel not found.");
        var rooms=new List<object>(); await using(var cmd=c.CreateCommand()){cmd.CommandText="""SELECT r.id,r.room_type,r.description,r.capacity,r.total_rooms,r.base_rate,r.image_url,r.amenities,COALESCE(i.available_rooms,r.total_rooms),COALESCE(i.rate,r.base_rate) FROM udrive.hotel_rooms r LEFT JOIN udrive.hotel_room_inventory i ON i.room_id=r.id AND i.inventory_date=@d WHERE r.hotel_id=@id AND r.is_active ORDER BY r.base_rate""";cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("d",(object?)checkIn??DateOnly.FromDateTime(DateTime.UtcNow));await using var rr=await cmd.ExecuteReaderAsync(ct);while(await rr.ReadAsync(ct))rooms.Add(new{id=rr.GetGuid(0),roomType=rr.GetString(1),description=rr.GetString(2),capacity=rr.GetInt32(3),totalRooms=rr.GetInt32(4),baseRate=rr.GetDecimal(5),imageUrl=rr.GetString(6),amenities=JsonSerializer.Deserialize<string[]>(rr.GetFieldValue<string>(7))??[],availableRooms=rr.GetInt32(8),rate=rr.GetDecimal(9)});}
        return ServiceResult<object>.Ok(new {hotel,rooms});
    }

    public async Task<ServiceResult<object>> MyHotelsAsync(Guid ownerId,CancellationToken ct){await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""SELECT id,name,address,city,district,latitude,longitude,contact_phone,rating,main_image_url,amenities,transport_available,approval_status,rejection_reason,is_active,created_at FROM udrive.hotels WHERE owner_user_id=@u ORDER BY created_at DESC""";cmd.Parameters.AddWithValue("u",ownerId);var list=new List<object>();await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new{id=r.GetGuid(0),name=r.GetString(1),address=r.GetString(2),city=r.GetString(3),district=r.GetString(4),latitude=r.GetDouble(5),longitude=r.GetDouble(6),contactPhone=r.GetString(7),rating=r.GetDecimal(8),mainImageUrl=r.GetString(9),amenities=JsonSerializer.Deserialize<string[]>(r.GetFieldValue<string>(10))??[],transportAvailable=r.GetBoolean(11),approvalStatus=r.GetString(12),rejectionReason=r.IsDBNull(13)?null:r.GetString(13),isActive=r.GetBoolean(14),createdAt=r.GetDateTime(15)});return ServiceResult<object>.Ok(list);}

    public async Task<ServiceResult<object>> CreateAsync(Guid ownerId,CreateHotelRequest x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.Address))return ServiceResult<object>.Fail(400,"validation","Hotel name and address are required.");await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""INSERT INTO udrive.hotels(owner_user_id,name,description,address,city,district,latitude,longitude,contact_phone,main_image_url,amenities,transport_available) VALUES(@u,@n,@d,@a,@c,@di,@lat,@lng,@p,@img,@am::jsonb,@t) RETURNING id""";cmd.Parameters.AddWithValue("u",ownerId);cmd.Parameters.AddWithValue("n",x.Name.Trim());cmd.Parameters.AddWithValue("d",x.Description??"");cmd.Parameters.AddWithValue("a",x.Address.Trim());cmd.Parameters.AddWithValue("c",x.City.Trim());cmd.Parameters.AddWithValue("di",x.District??"");cmd.Parameters.AddWithValue("lat",x.Latitude);cmd.Parameters.AddWithValue("lng",x.Longitude);cmd.Parameters.AddWithValue("p",x.ContactPhone??"");cmd.Parameters.AddWithValue("img",x.MainImageUrl??"");cmd.Parameters.AddWithValue("am",JsonSerializer.Serialize(x.Amenities??[]));cmd.Parameters.AddWithValue("t",x.TransportAvailable);var id=(Guid)(await cmd.ExecuteScalarAsync(ct))!;return ServiceResult<object>.Ok(new{id,approvalStatus="Pending"});}

    public async Task<ServiceResult<object>> AddRoomAsync(Guid ownerId,Guid hotelId,CreateHotelRoomRequest x,CancellationToken ct){await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""INSERT INTO udrive.hotel_rooms(hotel_id,room_type,description,capacity,total_rooms,base_rate,image_url,amenities) SELECT @h,@rt,@d,@cap,@total,@rate,@img,@am::jsonb FROM udrive.hotels WHERE id=@h AND owner_user_id=@u RETURNING id""";cmd.Parameters.AddWithValue("h",hotelId);cmd.Parameters.AddWithValue("u",ownerId);cmd.Parameters.AddWithValue("rt",x.RoomType.Trim());cmd.Parameters.AddWithValue("d",x.Description??"");cmd.Parameters.AddWithValue("cap",x.Capacity);cmd.Parameters.AddWithValue("total",x.TotalRooms);cmd.Parameters.AddWithValue("rate",x.BaseRate);cmd.Parameters.AddWithValue("img",x.ImageUrl??"");cmd.Parameters.AddWithValue("am",JsonSerializer.Serialize(x.Amenities??[]));var o=await cmd.ExecuteScalarAsync(ct);return o is Guid id?ServiceResult<object>.Ok(new{id}):ServiceResult<object>.Fail(404,"hotel_not_found","Hotel not found.");}

    public async Task<ServiceResult<object>> BookAsync(Guid userId,Guid hotelId,CreateHotelBookingRequest x,CancellationToken ct){if(x.CheckOut<=x.CheckIn)return ServiceResult<object>.Fail(400,"dates","Check-out must be after check-in.");await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);try{decimal rate;int available;await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="""SELECT COALESCE(i.rate,r.base_rate),COALESCE(i.available_rooms,r.total_rooms) FROM udrive.hotel_rooms r JOIN udrive.hotels h ON h.id=r.hotel_id LEFT JOIN udrive.hotel_room_inventory i ON i.room_id=r.id AND i.inventory_date=@d WHERE r.id=@r AND h.id=@h AND h.approval_status='Approved' AND h.is_active AND r.is_active FOR UPDATE""";q.Parameters.AddWithValue("d",x.CheckIn);q.Parameters.AddWithValue("r",x.RoomId);q.Parameters.AddWithValue("h",hotelId);await using var rr=await q.ExecuteReaderAsync(ct);if(!await rr.ReadAsync(ct))return ServiceResult<object>.Fail(404,"room_not_found","Room is unavailable.");rate=rr.GetDecimal(0);available=rr.GetInt32(1);}if(available<x.Rooms)return ServiceResult<object>.Fail(409,"rooms_unavailable","Not enough rooms are available.");var nights=x.CheckOut.DayNumber-x.CheckIn.DayNumber;var amount=rate*x.Rooms*nights;Guid bookingId;await using(var ins=c.CreateCommand()){ins.Transaction=tx;ins.CommandText="""INSERT INTO udrive.hotel_bookings(customer_user_id,hotel_id,room_id,check_in,check_out,guests,rooms,amount,include_transport) VALUES(@u,@h,@r,@ci,@co,@g,@rooms,@a,@t) RETURNING id""";ins.Parameters.AddWithValue("u",userId);ins.Parameters.AddWithValue("h",hotelId);ins.Parameters.AddWithValue("r",x.RoomId);ins.Parameters.AddWithValue("ci",x.CheckIn);ins.Parameters.AddWithValue("co",x.CheckOut);ins.Parameters.AddWithValue("g",x.Guests);ins.Parameters.AddWithValue("rooms",x.Rooms);ins.Parameters.AddWithValue("a",amount);ins.Parameters.AddWithValue("t",x.IncludeTransport);bookingId=(Guid)(await ins.ExecuteScalarAsync(ct))!;}await tx.CommitAsync(ct);return ServiceResult<object>.Ok(new{bookingId,amount,includeTransport=x.IncludeTransport,transportDestination=new{hotelId,latitude=(double?)null,longitude=(double?)null}});}catch{await tx.RollbackAsync(ct);throw;}}

    public async Task<ServiceResult<object>> OwnerBookingsAsync(Guid ownerId,Guid? hotelId,CancellationToken ct){await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""SELECT b.id,b.hotel_id,h.name,r.room_type,b.check_in,b.check_out,b.guests,b.rooms,b.amount,b.status,b.payment_status,b.include_transport,b.created_at FROM udrive.hotel_bookings b JOIN udrive.hotels h ON h.id=b.hotel_id JOIN udrive.hotel_rooms r ON r.id=b.room_id WHERE h.owner_user_id=@u AND (@h IS NULL OR h.id=@h) ORDER BY b.created_at DESC LIMIT 100""";cmd.Parameters.AddWithValue("u",ownerId);cmd.Parameters.AddWithValue("h",(object?)hotelId??DBNull.Value);var list=new List<object>();await using var rr=await cmd.ExecuteReaderAsync(ct);while(await rr.ReadAsync(ct))list.Add(new{id=rr.GetGuid(0),hotelId=rr.GetGuid(1),hotelName=rr.GetString(2),roomType=rr.GetString(3),checkIn=rr.GetFieldValue<DateOnly>(4),checkOut=rr.GetFieldValue<DateOnly>(5),guests=rr.GetInt32(6),rooms=rr.GetInt32(7),amount=rr.GetDecimal(8),status=rr.GetString(9),paymentStatus=rr.GetString(10),includeTransport=rr.GetBoolean(11),createdAt=rr.GetDateTime(12)});return ServiceResult<object>.Ok(list);}

    public async Task<ServiceResult<object>> PendingAsync(CancellationToken ct){await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""SELECT h.id,h.name,h.address,h.city,h.district,h.contact_phone,h.main_image_url,h.created_at,u.full_name owner_name,u.phone owner_phone FROM udrive.hotels h JOIN udrive.users u ON u.id=h.owner_user_id WHERE h.approval_status='Pending' ORDER BY h.created_at""";var list=new List<object>();await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new{id=r.GetGuid(0),name=r.GetString(1),address=r.GetString(2),city=r.GetString(3),district=r.GetString(4),contactPhone=r.GetString(5),mainImageUrl=r.GetString(6),createdAt=r.GetDateTime(7),ownerName=r.GetString(8),ownerPhone=r.GetString(9)});return ServiceResult<object>.Ok(list);}
    public async Task<ServiceResult<object>> ReviewAsync(Guid adminId,Guid id,ReviewHotelRequest x,CancellationToken ct){await using var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.CommandText="""UPDATE udrive.hotels SET approval_status=@s,rejection_reason=@r,approved_by=CASE WHEN @ok THEN @a ELSE NULL END,approved_at=CASE WHEN @ok THEN now() ELSE NULL END,updated_at=now() WHERE id=@id RETURNING id""";cmd.Parameters.AddWithValue("s",x.Approve?"Approved":"Rejected");cmd.Parameters.AddWithValue("r",(object?)x.Reason??DBNull.Value);cmd.Parameters.AddWithValue("ok",x.Approve);cmd.Parameters.AddWithValue("a",adminId);cmd.Parameters.AddWithValue("id",id);var o=await cmd.ExecuteScalarAsync(ct);return o is Guid?ServiceResult<object>.Ok(new{id,status=x.Approve?"Approved":"Rejected"}):ServiceResult<object>.Fail(404,"hotel_not_found","Hotel not found.");}

    static object MapHotel(NpgsqlDataReader r,bool detail=false)=>new{id=r.GetGuid(0),name=r.GetString(1),address=r.GetString(2),city=r.GetString(3),district=r.GetString(4),latitude=r.GetDouble(5),longitude=r.GetDouble(6),contactPhone=r.GetString(7),rating=r.GetDecimal(8),mainImageUrl=r.GetString(9),amenities=JsonSerializer.Deserialize<string[]>(r.GetFieldValue<string>(10))??[],transportAvailable=r.GetBoolean(11),description=detail?r.GetString(12):null,startingRate=detail?0:r.GetDecimal(12),availableRooms=detail?0:r.GetInt64(13)};
}
