import 'dart:async';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../core/booking/trip_operations_repository.dart';
import '../../core/state/app_controller.dart';
import '../../models/trip_operations_models.dart';

class CustomerOperationsScreen extends StatefulWidget{const CustomerOperationsScreen({super.key});@override State<CustomerOperationsScreen> createState()=>_CustomerOperationsScreenState();}
class _CustomerOperationsScreenState extends State<CustomerOperationsScreen>{TripOperationsRepository? _repo;List<MobileTrip> _trips=[];bool _busy=true;String? _error;
 @override void didChangeDependencies(){super.didChangeDependencies();if(_repo==null){_repo=TripOperationsRepository(AppController.of(context).apiClient);_load();}}
 Future<void> _load()async{try{final value=await _repo!.customerTrips();if(mounted)setState((){_trips=value;_error=null;});}catch(e){if(mounted)setState(()=>_error=e.toString());}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _cancel(MobileTrip trip)async{final c=TextEditingController();final reason=await showDialog<String?>(context:context,builder:(context)=>AlertDialog(title:const Text('Cancel booking'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(labelText:'Cancellation reason')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Keep booking')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Cancel booking'))]));c.dispose();if(reason==null||reason.isEmpty)return;try{await _repo!.customerStatus(trip.bookingId,'Cancelled',reason:reason);await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
 @override Widget build(BuildContext context)=>SafeArea(child:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('My Trips',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Driver assignment, live progress and tracking.',style:TextStyle(color:Colors.black54)),if(_error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(_error!,style:const TextStyle(color:Colors.red))),const SizedBox(height:16),if(_busy)const Center(child:CircularProgressIndicator())else if(_trips.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(22),child:Text('No live bookings found.')))else..._trips.map((x)=>_CustomerTripCard(x,onCancel:()=>_cancel(x),onTrack:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomerTripTrackingScreen(trip:x,repository:_repo!)))))])));
}

class _CustomerTripCard extends StatelessWidget{const _CustomerTripCard(this.trip,{required this.onCancel,required this.onTrack});final MobileTrip trip;final VoidCallback onCancel,onTrack;bool get cancellable=>['Pending','Confirmed','DriverAssigned','DriverAccepted'].contains(trip.tripStatus);@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(trip.bookingReference,style:const TextStyle(fontWeight:FontWeight.w900))),Chip(label:Text(trip.tripStatus))]),Text('${trip.pickupLabel} → ${trip.destinationLabel}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(DateFormat('dd MMM yyyy, HH:mm').format(trip.pickupAt.toLocal())),const Divider(height:24),Row(children:[const CircleAvatar(child:Icon(Icons.person)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(trip.driverName??'Driver assignment pending',style:const TextStyle(fontWeight:FontWeight.w800)),Text(trip.driverPhone??'',style:const TextStyle(color:Colors.black54))])),IconButton(onPressed:trip.driverPhone==null?null:(){},icon:const Icon(Icons.call_outlined))]),if(trip.vehicle!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text('${trip.vehicle} · ${trip.registrationNumber}',style:const TextStyle(fontWeight:FontWeight.w700))),const SizedBox(height:10),_StatusTimeline(current:trip.tripStatus),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.tonal(onPressed:trip.driverName==null?null:onTrack,child:const Text('Live tracking'))),if(cancellable)...[const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:onCancel,child:const Text('Cancel')))]])])));}

class _StatusTimeline extends StatelessWidget{const _StatusTimeline({required this.current});final String current;static const steps=['Confirmed','DriverAssigned','DriverAccepted','DriverEnRoute','DriverArrived','TripStarted','TripCompleted'];@override Widget build(BuildContext context){final index=steps.indexOf(current);return SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:steps.asMap().entries.map((e){final done=index>=e.key||current=='TripCompleted';return Row(children:[Column(children:[CircleAvatar(radius:11,backgroundColor:done?Theme.of(context).colorScheme.primary:Colors.black12,child:done?const Icon(Icons.check,size:13,color:Colors.white):null),const SizedBox(height:4),Text(e.value.replaceAll('Driver','').replaceAll('Trip',''),style:const TextStyle(fontSize:9))]),if(e.key<steps.length-1)Container(width:24,height:2,color:done?Theme.of(context).colorScheme.primary:Colors.black12)]);}).toList()));}}

class CustomerTripTrackingScreen extends StatefulWidget{const CustomerTripTrackingScreen({super.key,required this.trip,required this.repository});final MobileTrip trip;final TripOperationsRepository repository;@override State<CustomerTripTrackingScreen> createState()=>_CustomerTripTrackingScreenState();}
class _CustomerTripTrackingScreenState extends State<CustomerTripTrackingScreen>{TripTracking? _tracking;String? _error;Timer? _timer;@override void initState(){super.initState();_load();_timer=Timer.periodic(const Duration(seconds:15),(_)=>_load());}@override void dispose(){_timer?.cancel();super.dispose();}Future<void> _load()async{try{final x=await widget.repository.tracking(widget.trip.bookingId);if(mounted)setState((){_tracking=x;_error=null;});}catch(e){if(mounted)setState(()=>_error=e.toString());}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.trip.bookingReference)),body:_tracking==null?Center(child:_error==null?const CircularProgressIndicator():Text(_error!)):ListView(padding:const EdgeInsets.all(16),children:[_TrackingCanvas(tracking:_tracking!),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_tracking!.tripStatus,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${_tracking!.driverName??'Driver'} · ${_tracking!.vehicle??''} · ${_tracking!.registrationNumber??''}'),const SizedBox(height:8),Text(_tracking!.driverLocation==null?'Driver location is not available yet.':'Last update: ${DateFormat('HH:mm:ss').format(_tracking!.driverLocation!.serverTimestamp.toLocal())} · ${_tracking!.driverLocation!.online?'Online':'Offline / stale'}'),if(_tracking!.driverLocation?.speedKph!=null)Text('Speed: ${_tracking!.driverLocation!.speedKph!.toStringAsFixed(0)} km/h · Accuracy: ${_tracking!.driverLocation!.accuracy?.toStringAsFixed(0)??'—'} m')]))),Card(child:ListTile(leading:const Icon(Icons.trip_origin),title:const Text('Pickup'),subtitle:Text(_tracking!.pickupLabel))),Card(child:ListTile(leading:const Icon(Icons.location_on),title:const Text('Destination'),subtitle:Text(_tracking!.destinationLabel))),FilledButton.icon(onPressed:widget.trip.driverPhone==null?null:(){},icon:const Icon(Icons.call),label:const Text('Contact driver'))]));}
}
class _TrackingCanvas extends StatelessWidget{const _TrackingCanvas({required this.tracking});final TripTracking tracking;@override Widget build(BuildContext context)=>Container(height:250,decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xFFEAF5F0),Color(0xFFDDECE6)])),child:CustomPaint(painter:_RoutePainter(tracking),child:Stack(children:[const Positioned(left:20,top:18,child:Chip(label:Text('LIVE TRIP'))),if(tracking.driverLocation?.stale==true)const Positioned(right:16,top:18,child:Chip(avatar:Icon(Icons.warning_amber,size:17),label:Text('Stale')))])));}
class _RoutePainter extends CustomPainter{_RoutePainter(this.tracking);final TripTracking tracking;@override void paint(Canvas c,Size s){final line=Paint()..color=const Color(0xFF0A8A62)..strokeWidth=5..style=PaintingStyle.stroke..strokeCap=StrokeCap.round;final path=Path()..moveTo(35,s.height-45)..cubicTo(s.width*.25,s.height*.2,s.width*.65,s.height*.8,s.width-40,45);c.drawPath(path,line);c.drawCircle(Offset(35,s.height-45),10,Paint()..color=Colors.blue);c.drawCircle(Offset(s.width-40,45),10,Paint()..color=Colors.orange);final driver=tracking.driverLocation;if(driver!=null){final x=s.width*.55,y=s.height*.5;c.drawCircle(Offset(x,y),18,Paint()..color=(driver.emergency?Colors.red:const Color(0xFF0B3B2E)).withOpacity(.2));c.drawCircle(Offset(x,y),9,Paint()..color=driver.emergency?Colors.red:const Color(0xFF0B3B2E));}}@override bool shouldRepaint(covariant _RoutePainter old)=>old.tracking.driverLocation?.serverTimestamp!=tracking.driverLocation?.serverTimestamp;}
