import '../../models/hotel_models.dart';
import '../network/api_client.dart';
class HotelRepository {HotelRepository(this.api);final ApiClient api;dynamic _data(Map<String,dynamic>j)=>j['data']??j;
Future<List<HotelSummary>> search({String query='',DateTime? checkIn,DateTime? checkOut,int guests=1,int rooms=1,int page=1})async{final q=<String,String>{'query':query,'guests':'$guests','rooms':'$rooms','page':'$page','pageSize':'20'};if(checkIn!=null)q['checkIn']=checkIn.toIso8601String().substring(0,10);if(checkOut!=null)q['checkOut']=checkOut.toIso8601String().substring(0,10);final r=await api.getJson('/api/v1/hotels?${Uri(queryParameters:q).query}',authenticated:false);final d=_data(r) as Map;return ((d['items']as List?)??const[]).map((e)=>HotelSummary.fromJson(Map<String,dynamic>.from(e))).toList();}
Future<HotelDetails> details(String id,{DateTime? checkIn,DateTime? checkOut})async{final q=<String,String>{};if(checkIn!=null)q['checkIn']=checkIn.toIso8601String().substring(0,10);if(checkOut!=null)q['checkOut']=checkOut.toIso8601String().substring(0,10);final r=await api.getJson('/api/v1/hotels/$id${q.isEmpty?'':'?${Uri(queryParameters:q).query}'}',authenticated:false);final d=Map<String,dynamic>.from(_data(r));final h=Map<String,dynamic>.from(d['hotel']);return HotelDetails(hotel:HotelSummary.fromJson(h),rooms:((d['rooms']as List?)??const[]).map((e)=>HotelRoom.fromJson(Map<String,dynamic>.from(e))).toList(),description:'${h['description']??''}',amenities:(h['amenities']as List? ?? const[]).map((e)=>'$e').toList());}
Future<List<HotelSummary>> myHotels()async{final r=await api.getJson('/api/v1/hotels/owner/my');return (_data(r)as List).map((e)=>HotelSummary.fromJson(Map<String,dynamic>.from(e))).toList();}
Future<List<Map<String,dynamic>>> ownerBookings({String? hotelId})async{final r=await api.getJson('/api/v1/hotels/owner/bookings${hotelId==null?'':'?hotelId=$hotelId'}');return (_data(r)as List).map((e)=>Map<String,dynamic>.from(e)).toList();}
Future<void> createHotel(Map<String,dynamic>x)async{await api.postJson('/api/v1/hotels/owner',x);}Future<void> addRoom(String id,Map<String,dynamic>x)async{await api.postJson('/api/v1/hotels/owner/$id/rooms',x);}Future<Map<String,dynamic>> book(String hotelId,Map<String,dynamic>x)async=>Map<String,dynamic>.from(_data(await api.postJson('/api/v1/hotels/$hotelId/bookings',x)));
}
