'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {ArrowRight,KeyRound,Loader2,ShieldCheck} from 'lucide-react';import {login,readSession} from '../lib/admin-api';import {BrandWordmark} from '../components/brand';
export default function Login(){const router=useRouter();
  // Where to go after signing in.
  //
  // A dead session redirects here with ?next=, so the person lands back on the
  // screen they were using rather than the dashboard — being bounced to the top
  // of the portal after every token expiry is its own small punishment.
  const next=typeof window==='undefined'?'/':(new URLSearchParams(window.location.search).get('next')||'/');
  const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(readSession())router.replace(next)},[router,next]);
  async function signIn(){if(!username.trim()||!password){setError('Enter your username and password.');return}setBusy(true);setError('');try{await login(username.trim(),password);router.replace(next)}catch(e){setError(e instanceof Error?e.message:'Login failed.')}finally{setBusy(false)}}
  return <main className="loginPage"><section className="loginShowcase"><div className="loginLogo"><BrandWordmark height={72}/></div><div><div className="eyebrow">KASHMIR TOURISM CONTROL</div><h1>Every journey.<br/>One secure command centre.</h1><p>Manage bookings, verified drivers, route safety, payments and traveller support from one professional workspace.</p></div><div className="trustStrip"><ShieldCheck/><span>Role-based access · JWT sessions · Complete audit trail</span></div></section><section className="loginPanel"><div className="loginCard"><div className="loginIcon"><KeyRound/></div><h2>Operations sign in</h2><p>Sign in with your portal username and password. Riders and drivers use the app with a WhatsApp code.</p>{error&&<div className="errorBox">{error}</div>}<form onSubmit={e=>{e.preventDefault();void signIn()}}><label className="field"><span>Username</span><input value={username} autoComplete="username" onChange={e=>setUsername(e.target.value)} placeholder="admin"/></label><label className="field"><span>Password</span><input type="password" value={password} autoComplete="current-password" onChange={e=>setPassword(e.target.value)}/></label><button className="primaryButton wide" type="submit" disabled={busy}>{busy?<Loader2 className="spin"/>:'Enter operations portal'}<ArrowRight/></button></form><p className="pingNote" style={{marginTop:12}}>Forgot your password? A SuperAdmin can reset it in Settings → Portal logins.</p></div></section></main>}
