using System.Text.Json;
using Npgsql;
using UDrive.Api.Common;
using UDrive.Api.Models;

namespace UDrive.Api.Services;

public sealed class FeedbackService(string connectionString, LocalFileStorageService files)
{
    NpgsqlConnection Open()=>new(connectionString);

    public async Task<ServiceResult<IReadOnlyList<EligibleRatingBookingDto>>> EligibleAsync(Guid userId,CancellationToken ct){
        await using var cn=Open();await cn.OpenAsync(ct);var list=new List<EligibleRatingBookingDto>();
        const string sql=@"select b.id,coalesce(b.booking_reference,b.id::text),case when b.customer_user_id=@u then du.full_name else cu.full_name end,case when b.customer_user_id=@u then 'Customer' else 'Driver' end,b.pickup_at,b.total_amount,exists(select 1 from udrive.trip_ratings r where r.booking_id=b.id and r.reviewer_user_id=@u) from udrive.bookings b join udrive.users cu on cu.id=b.customer_user_id left join udrive.driver_profiles dp on dp.id=b.driver_profile_id left join udrive.users du on du.id=dp.user_id where b.status='Completed' and (b.customer_user_id=@u or dp.user_id=@u) order by b.pickup_at desc limit 100";
        await using var c=new NpgsqlCommand(sql,cn);c.Parameters.AddWithValue("u",userId);await using var r=await c.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?"uDrive user":r.GetString(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.GetDecimal(5),r.GetBoolean(6)));return ServiceResult<IReadOnlyList<EligibleRatingBookingDto>>.Ok(list);
    }

    public async Task<ServiceResult<RatingDto>> SubmitRatingAsync(Guid userId,SubmitRatingRequest req,CancellationToken ct){
        if(!Valid(req.OverallRating)||!ValidNullable(req.DrivingRating)||!ValidNullable(req.BehaviourRating)||!ValidNullable(req.CleanlinessRating)||!ValidNullable(req.PunctualityRating)||!ValidNullable(req.CommunicationRating))return ServiceResult<RatingDto>.Fail(422,"invalid_rating","Ratings must be between 1 and 5.");
        await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);
        Guid reviewee;string role;
        await using(var c=new NpgsqlCommand(@"select b.customer_user_id,dp.user_id,b.status from udrive.bookings b left join udrive.driver_profiles dp on dp.id=b.driver_profile_id where b.id=@b",cn,tx)){c.Parameters.AddWithValue("b",req.BookingId);await using var r=await c.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return ServiceResult<RatingDto>.Fail(404,"booking_not_found","Booking was not found.");var customer=r.GetGuid(0);var driver=r.IsDBNull(1)?Guid.Empty:r.GetGuid(1);if(r.GetString(2)!="Completed")return ServiceResult<RatingDto>.Fail(409,"trip_not_completed","Rating is available after trip completion.");if(userId==customer&&driver!=Guid.Empty){reviewee=driver;role="Customer";}else if(userId==driver){reviewee=customer;role="Driver";}else return ServiceResult<RatingDto>.Fail(403,"not_booking_party","You are not part of this booking.");}
        var id=Guid.NewGuid();
        try{await Exec(cn,tx,@"insert into udrive.trip_ratings(id,booking_id,reviewer_user_id,reviewee_user_id,reviewer_role,overall_rating,driving_rating,behaviour_rating,cleanliness_rating,punctuality_rating,communication_rating,review_text) values(@id,@b,@r,@e,@role,@o,@d,@be,@cl,@p,@co,@t)",ct,("id",id),("b",req.BookingId),("r",userId),("e",reviewee),("role",role),("o",req.OverallRating),("d",req.DrivingRating),("be",req.BehaviourRating),("cl",req.CleanlinessRating),("p",req.PunctualityRating),("co",req.CommunicationRating),("t",Trim(req.ReviewText,1200)));}catch(PostgresException e)when(e.SqlState=="23505"){return ServiceResult<RatingDto>.Fail(409,"already_rated","You have already rated this trip.");}
        await Notify(cn,tx,reviewee,"RatingReceived","New trip rating","You received a new trip rating.",new{bookingId=req.BookingId},ct);await Audit(cn,tx,userId,"rating.created","TripRating",id.ToString(),req,ct);await tx.CommitAsync(ct);return await GetRatingAsync(id,ct);
    }

    public async Task<ServiceResult<RatingSummaryDto>> SummaryAsync(Guid userId,CancellationToken ct){
        await using var cn=Open();await cn.OpenAsync(ct);decimal avg=0;int count=0;await using(var c=new NpgsqlCommand("select coalesce(avg(overall_rating),0),count(*) from udrive.trip_ratings where reviewee_user_id=@u and is_visible=true and moderation_status='Published'",cn)){c.Parameters.AddWithValue("u",userId);await using var r=await c.ExecuteReaderAsync(ct);await r.ReadAsync(ct);avg=r.GetDecimal(0);count=Convert.ToInt32(r.GetInt64(1));}
        var ratings=await LoadRatingsAsync(cn,"where tr.reviewee_user_id=@u and tr.is_visible=true and tr.moderation_status='Published'",("u",userId),ct);return ServiceResult<RatingSummaryDto>.Ok(new(userId,Math.Round(avg,2),count,ratings.Take(20).ToList()));
    }

    public async Task<ServiceResult<DisputeCaseDto>> CreateCaseAsync(Guid userId,CreateDisputeCaseRequest req,CancellationToken ct){
        if(string.IsNullOrWhiteSpace(req.Subject)||string.IsNullOrWhiteSpace(req.Description))return ServiceResult<DisputeCaseDto>.Fail(422,"missing_details","Subject and description are required.");
        await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);Guid? against=null;
        if(req.BookingId.HasValue){await using var c=new NpgsqlCommand(@"select b.customer_user_id,dp.user_id from udrive.bookings b left join udrive.driver_profiles dp on dp.id=b.driver_profile_id where b.id=@b",cn,tx);c.Parameters.AddWithValue("b",req.BookingId.Value);await using var r=await c.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return ServiceResult<DisputeCaseDto>.Fail(404,"booking_not_found","Booking was not found.");var customer=r.GetGuid(0);var driver=r.IsDBNull(1)?Guid.Empty:r.GetGuid(1);if(userId!=customer&&userId!=driver)return ServiceResult<DisputeCaseDto>.Fail(403,"not_booking_party","You are not part of this booking.");against=userId==customer&&driver!=Guid.Empty?driver:customer;}
        var id=Guid.NewGuid();var reference=$"CASE-{DateTime.UtcNow:yyMMdd}-{id.ToString("N")[..6].ToUpperInvariant()}";await Exec(cn,tx,@"insert into udrive.dispute_cases(id,case_reference,booking_id,opened_by_user_id,against_user_id,category,priority,subject,description,requested_resolution,disputed_amount) values(@id,@ref,@b,@u,@a,@c,@p,@s,@d,@rr,@amt)",ct,("id",id),("ref",reference),("b",req.BookingId),("u",userId),("a",against),("c",Trim(req.Category,50)??"Other"),("p",NormalizePriority(req.Priority)),("s",Trim(req.Subject,180)),("d",req.Description.Trim()),("rr",Trim(req.RequestedResolution,80)),("amt",req.DisputedAmount));await Event(cn,tx,id,userId,"Opened",false,"Case opened by user.",new{},ct);await Audit(cn,tx,userId,"case.created","DisputeCase",id.ToString(),req,ct);await tx.CommitAsync(ct);return await CaseDetailAsync(userId,id,false,ct);
    }

    public async Task<ServiceResult<IReadOnlyList<DisputeCaseDto>>> MyCasesAsync(Guid userId,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);return ServiceResult<IReadOnlyList<DisputeCaseDto>>.Ok(await LoadCasesAsync(cn,"where dc.opened_by_user_id=@u or dc.against_user_id=@u",new[]{("u",(object?)userId)},ct));}
    public async Task<ServiceResult<DisputeDashboardDto>> DashboardAsync(CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);await using var c=new NpgsqlCommand(@"select count(*) filter(where status='Open'),count(*) filter(where status='InReview'),count(*) filter(where status='AwaitingResponse'),count(*) filter(where status in ('Resolved','Closed')),count(*) filter(where priority in ('Urgent','Emergency') and status not in ('Resolved','Closed')) from udrive.dispute_cases",cn);await using var r=await c.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return ServiceResult<DisputeDashboardDto>.Ok(new(I(r,0),I(r,1),I(r,2),I(r,3),I(r,4)));}
    public async Task<ServiceResult<IReadOnlyList<DisputeCaseDto>>> AdminCasesAsync(string? status,string? priority,string? search,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);var clauses=new List<string>();var p=new List<(string,object?)>();if(!string.IsNullOrWhiteSpace(status)){clauses.Add("dc.status=@status");p.Add(("status",status));}if(!string.IsNullOrWhiteSpace(priority)){clauses.Add("dc.priority=@priority");p.Add(("priority",priority));}if(!string.IsNullOrWhiteSpace(search)){clauses.Add("(dc.case_reference ilike @q or dc.subject ilike @q or ou.full_name ilike @q)");p.Add(("q",$"%{search.Trim()}%"));}return ServiceResult<IReadOnlyList<DisputeCaseDto>>.Ok(await LoadCasesAsync(cn,clauses.Count==0?"":"where "+string.Join(" and ",clauses),p,ct));}
    public async Task<ServiceResult<DisputeCaseDto>> CaseDetailAsync(Guid actor,Guid id,bool admin,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);var items=await LoadCasesAsync(cn,"where dc.id=@id",new[]{("id",(object?)id)},ct);if(items.Count==0)return ServiceResult<DisputeCaseDto>.Fail(404,"case_not_found","Case was not found.");var item=items[0];if(!admin&&item.OpenedByUserId!=actor&&item.AgainstUserId!=actor)return ServiceResult<DisputeCaseDto>.Fail(403,"case_forbidden","You cannot access this case.");var evidence=await LoadEvidence(cn,id,ct);var events=await LoadEvents(cn,id,admin,ct);return ServiceResult<DisputeCaseDto>.Ok(item with{Evidence=evidence,Events=events});}
    public async Task<ServiceResult<DisputeEvidenceDto>> UploadEvidenceAsync(Guid userId,Guid caseId,IFormFile file,string? description,bool admin,CancellationToken ct){var access=await CaseDetailAsync(userId,caseId,admin,ct);if(!access.Success)return ServiceResult<DisputeEvidenceDto>.Fail(access.StatusCode,access.ErrorCode!,access.Message!);var stored=await files.SaveAsync(file,"disputes",caseId,ct);var id=Guid.NewGuid();await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var url=stored.RelativeUrl.Replace("/api/v1/admin/verification/files/","/api/v1/feedback/files/");await Exec(cn,tx,"insert into udrive.dispute_evidence(id,case_id,uploaded_by_user_id,file_url,file_name,content_type,file_size,description) values(@id,@c,@u,@url,@n,@t,@s,@d)",ct,("id",id),("c",caseId),("u",userId),("url",url),("n",Path.GetFileName(file.FileName)),("t",stored.ContentType),("s",stored.Size),("d",Trim(description,500)));await Event(cn,tx,caseId,userId,"EvidenceAdded",false,"Evidence attachment added.",new{id},ct);await tx.CommitAsync(ct);return ServiceResult<DisputeEvidenceDto>.Ok(new(id,url,Path.GetFileName(file.FileName),stored.ContentType,stored.Size,description,DateTimeOffset.UtcNow));}
    public async Task<ServiceResult<DisputeCaseDto>> AssignAsync(Guid actor,Guid id,AssignCaseRequest req,CancellationToken ct)=>await AdminUpdate(actor,id,req.ExpectedVersion,"assigned_admin_user_id=@v, status=case when status='Open' then 'InReview' else status end",req.AssignedAdminUserId,"Assigned",ct);
    public async Task<ServiceResult<DisputeCaseDto>> UpdateAsync(Guid actor,Guid id,UpdateCaseRequest req,CancellationToken ct){var allowed=new[]{"Open","InReview","AwaitingResponse","Escalated","Resolved","Closed","Rejected"};if(!allowed.Contains(req.Status))return ServiceResult<DisputeCaseDto>.Fail(422,"invalid_status","Invalid case status.");await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var changed=await ExecCount(cn,tx,@"update udrive.dispute_cases set status=@s,resolution_summary=@r,resolved_at=case when @s='Resolved' then now() else resolved_at end,closed_at=case when @s='Closed' then now() else closed_at end,version=version+1,updated_at=now() where id=@id and version=@v",ct,("s",req.Status),("r",Trim(req.ResolutionSummary,4000)),("id",id),("v",req.ExpectedVersion));if(changed==0)return ServiceResult<DisputeCaseDto>.Fail(409,"case_changed","Case changed. Refresh and retry.");await Event(cn,tx,id,actor,"StatusChanged",true,$"Status changed to {req.Status}.",new{req.Status,req.ResolutionSummary},ct);await Audit(cn,tx,actor,"case.updated","DisputeCase",id.ToString(),req,ct);await tx.CommitAsync(ct);return await CaseDetailAsync(actor,id,true,ct);}
    public async Task<ServiceResult<DisputeCaseDto>> ActionAsync(Guid actor,Guid id,CaseActionRequest req,bool allowPermanentSuspension,CancellationToken ct){
        var allowed=new[]{"Warning","TemporarySuspension","PermanentSuspension","RefundRecommendation","FinancialAdjustmentRecommendation","NoAction"};
        if(!allowed.Contains(req.ActionType))return ServiceResult<DisputeCaseDto>.Fail(422,"invalid_action","Invalid case action.");
        if(req.ActionType=="PermanentSuspension"&&!allowPermanentSuspension)return ServiceResult<DisputeCaseDto>.Fail(403,"superadmin_required","Permanent suspension requires SuperAdmin access.");
        var current=await CaseDetailAsync(actor,id,true,ct);if(!current.Success)return current;
        var target=req.TargetUserId??current.Data!.AgainstUserId;
        if((req.ActionType is "Warning" or "TemporarySuspension" or "PermanentSuspension") && !target.HasValue)return ServiceResult<DisputeCaseDto>.Fail(422,"target_required","Select a user for this action.");
        await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);
        if(req.ActionType=="TemporarySuspension")await Exec(cn,tx,"update udrive.users set account_status='Suspended',token_version=token_version+1,updated_at=now() where id=@u",ct,("u",target));
        if(req.ActionType=="PermanentSuspension")await Exec(cn,tx,"update udrive.users set account_status='Rejected',token_version=token_version+1,updated_at=now() where id=@u",ct,("u",target));
        if(target.HasValue)await Notify(cn,tx,target.Value,"CaseAction",$"Case action: {req.ActionType}",req.Reason,new{caseId=id,req.ActionType,req.Amount},ct);
        await Event(cn,tx,id,actor,req.ActionType,true,req.Reason,new{targetUserId=target,req.Amount},ct);
        await Exec(cn,tx,"update udrive.dispute_cases set status=case when @a in ('RefundRecommendation','FinancialAdjustmentRecommendation') then 'Escalated' else status end,version=version+1,updated_at=now() where id=@id",ct,("a",req.ActionType),("id",id));
        await Audit(cn,tx,actor,"case.action","DisputeCase",id.ToString(),req,ct);await tx.CommitAsync(ct);return await CaseDetailAsync(actor,id,true,ct);
    }

    public async Task<ServiceResult<DisputeCaseDto>> AddEventAsync(Guid actor,Guid id,AddCaseEventRequest req,bool admin,CancellationToken ct){var access=await CaseDetailAsync(actor,id,admin,ct);if(!access.Success)return ServiceResult<DisputeCaseDto>.Fail(access.StatusCode,access.ErrorCode!,access.Message!);if(req.IsInternal&&!admin)return ServiceResult<DisputeCaseDto>.Fail(403,"internal_note_forbidden","Only staff can add internal notes.");await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);await Event(cn,tx,id,actor,Trim(req.EventType,50)??"Note",req.IsInternal,req.Message.Trim(),new{},ct);if(!admin)await Exec(cn,tx,"update udrive.dispute_cases set status=case when status='AwaitingResponse' then 'InReview' else status end,version=version+1,updated_at=now() where id=@id",ct,("id",id));await tx.CommitAsync(ct);return await CaseDetailAsync(actor,id,admin,ct);}

    async Task<ServiceResult<DisputeCaseDto>> AdminUpdate(Guid actor,Guid id,int version,string assignment,object? value,string eventType,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var changed=await ExecCount(cn,tx,$"update udrive.dispute_cases set {assignment},version=version+1,updated_at=now() where id=@id and version=@ver",ct,("v",value),("id",id),("ver",version));if(changed==0)return ServiceResult<DisputeCaseDto>.Fail(409,"case_changed","Case changed. Refresh and retry.");await Event(cn,tx,id,actor,eventType,true,"Case assignment updated.",new{value},ct);await tx.CommitAsync(ct);return await CaseDetailAsync(actor,id,true,ct);}
    async Task<ServiceResult<RatingDto>> GetRatingAsync(Guid id,CancellationToken ct){await using var cn=Open();await cn.OpenAsync(ct);var list=await LoadRatingsAsync(cn,"where tr.id=@id",("id",id),ct);return list.Count==0?ServiceResult<RatingDto>.Fail(404,"rating_not_found","Rating not found."):ServiceResult<RatingDto>.Ok(list[0]);}
    static async Task<List<RatingDto>> LoadRatingsAsync(NpgsqlConnection cn,string where,(string,object?) p,CancellationToken ct){var list=new List<RatingDto>();await using var c=new NpgsqlCommand($@"select tr.id,tr.booking_id,coalesce(b.booking_reference,b.id::text),tr.reviewer_user_id,ru.full_name,tr.reviewee_user_id,eu.full_name,tr.reviewer_role,tr.overall_rating,tr.driving_rating,tr.behaviour_rating,tr.cleanliness_rating,tr.punctuality_rating,tr.communication_rating,tr.review_text,tr.created_at from udrive.trip_ratings tr join udrive.bookings b on b.id=tr.booking_id join udrive.users ru on ru.id=tr.reviewer_user_id join udrive.users eu on eu.id=tr.reviewee_user_id {where} order by tr.created_at desc",cn);c.Parameters.AddWithValue(p.Item1,p.Item2??DBNull.Value);await using var r=await c.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetGuid(3),r.GetString(4),r.GetGuid(5),r.GetString(6),r.GetString(7),r.GetInt16(8),NInt(r,9),NInt(r,10),NInt(r,11),NInt(r,12),NInt(r,13),r.IsDBNull(14)?null:r.GetString(14),r.GetFieldValue<DateTimeOffset>(15)));return list;}
    static async Task<List<DisputeCaseDto>> LoadCasesAsync(NpgsqlConnection cn,string where,IEnumerable<(string,object?)> parameters,CancellationToken ct){var list=new List<DisputeCaseDto>();await using var c=new NpgsqlCommand($@"select dc.id,dc.case_reference,dc.booking_id,coalesce(b.booking_reference,b.id::text),dc.opened_by_user_id,ou.full_name,dc.against_user_id,au.full_name,dc.category,dc.priority,dc.subject,dc.description,dc.requested_resolution,dc.disputed_amount,dc.status,dc.assigned_admin_user_id,ad.full_name,dc.resolution_summary,dc.version,dc.created_at,dc.resolved_at from udrive.dispute_cases dc join udrive.users ou on ou.id=dc.opened_by_user_id left join udrive.users au on au.id=dc.against_user_id left join udrive.users ad on ad.id=dc.assigned_admin_user_id left join udrive.bookings b on b.id=dc.booking_id {where} order by case dc.priority when 'Emergency' then 1 when 'Urgent' then 2 else 3 end,dc.created_at desc limit 500",cn);foreach(var p in parameters)c.Parameters.AddWithValue(p.Item1,p.Item2??DBNull.Value);await using var r=await c.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),NGuid(r,2),r.IsDBNull(3)?null:r.GetString(3),r.GetGuid(4),r.GetString(5),NGuid(r,6),r.IsDBNull(7)?null:r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.IsDBNull(12)?null:r.GetString(12),r.IsDBNull(13)?null:r.GetDecimal(13),r.GetString(14),NGuid(r,15),r.IsDBNull(16)?null:r.GetString(16),r.IsDBNull(17)?null:r.GetString(17),r.GetInt32(18),r.GetFieldValue<DateTimeOffset>(19),r.IsDBNull(20)?null:r.GetFieldValue<DateTimeOffset>(20)));return list;}
    static async Task<List<DisputeEvidenceDto>> LoadEvidence(NpgsqlConnection cn,Guid id,CancellationToken ct){var x=new List<DisputeEvidenceDto>();await using var c=new NpgsqlCommand("select id,file_url,file_name,content_type,file_size,description,created_at from udrive.dispute_evidence where case_id=@id order by created_at",cn);c.Parameters.AddWithValue("id",id);await using var r=await c.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))x.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetInt64(4),r.IsDBNull(5)?null:r.GetString(5),r.GetFieldValue<DateTimeOffset>(6)));return x;}
    static async Task<List<DisputeCaseEventDto>> LoadEvents(NpgsqlConnection cn,Guid id,bool admin,CancellationToken ct){var x=new List<DisputeCaseEventDto>();await using var c=new NpgsqlCommand("select e.id,e.actor_user_id,u.full_name,e.event_type,e.is_internal,e.message,e.created_at from udrive.dispute_case_events e left join udrive.users u on u.id=e.actor_user_id where e.case_id=@id and (@admin or not e.is_internal) order by e.created_at",cn);c.Parameters.AddWithValue("id",id);c.Parameters.AddWithValue("admin",admin);await using var r=await c.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))x.Add(new(r.GetGuid(0),NGuid(r,1),r.IsDBNull(2)?null:r.GetString(2),r.GetString(3),r.GetBoolean(4),r.GetString(5),r.GetFieldValue<DateTimeOffset>(6)));return x;}
    static bool Valid(int x)=>x is>=1 and<=5;static bool ValidNullable(int? x)=>!x.HasValue||Valid(x.Value);static int? NInt(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetInt16(i);static Guid? NGuid(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetGuid(i);static int I(NpgsqlDataReader r,int i)=>Convert.ToInt32(r.GetInt64(i));static string NormalizePriority(string? x)=>x?.Trim() switch{"Emergency"=>"Emergency","Urgent"=>"Urgent","Low"=>"Low",_=>"Normal"};static string? Trim(string? x,int n)=>string.IsNullOrWhiteSpace(x)?null:x.Trim()[..Math.Min(x.Trim().Length,n)];
    static async Task Exec(NpgsqlConnection cn,NpgsqlTransaction tx,string sql,CancellationToken ct,params(string,object?)[] p)=>_ = await ExecCount(cn,tx,sql,ct,p);static async Task<int> ExecCount(NpgsqlConnection cn,NpgsqlTransaction tx,string sql,CancellationToken ct,params(string,object?)[] p){await using var c=new NpgsqlCommand(sql,cn,tx);foreach(var x in p)c.Parameters.AddWithValue(x.Item1,x.Item2??DBNull.Value);return await c.ExecuteNonQueryAsync(ct);}static Task Event(NpgsqlConnection cn,NpgsqlTransaction tx,Guid caseId,Guid? actor,string type,bool internalNote,string message,object metadata,CancellationToken ct)=>Exec(cn,tx,"insert into udrive.dispute_case_events(id,case_id,actor_user_id,event_type,is_internal,message,metadata_json) values(gen_random_uuid(),@c,@a,@t,@i,@m,cast(@j as jsonb))",ct,("c",caseId),("a",actor),("t",type),("i",internalNote),("m",message),("j",JsonSerializer.Serialize(metadata)));static Task Notify(NpgsqlConnection cn,NpgsqlTransaction tx,Guid user,string type,string title,string body,object data,CancellationToken ct)=>Exec(cn,tx,"insert into udrive.notifications(id,user_id,type,title,body,data_json,created_at,updated_at) values(gen_random_uuid(),@u,@t,@h,@b,cast(@j as jsonb),now(),now())",ct,("u",user),("t",type),("h",title),("b",body),("j",JsonSerializer.Serialize(data)));static Task Audit(NpgsqlConnection cn,NpgsqlTransaction tx,Guid actor,string action,string entity,string id,object changes,CancellationToken ct)=>Exec(cn,tx,"insert into udrive.audit_logs(id,actor_user_id,action,entity_type,entity_id,changes_json,created_at,updated_at) values(gen_random_uuid(),@a,@x,@e,@id,cast(@j as jsonb),now(),now())",ct,("a",actor),("x",action),("e",entity),("id",id),("j",JsonSerializer.Serialize(changes)));
}
